### ISSUE TITLE
"within" only works for element type frame

### ISSUE THREAD

**Issue by ZozoZoeLi** [codeceptjs/CodeceptJS#1000]
#### What are you trying to achieve?
I was trying to use "within" to specify the exact area on a page, as described in the [document](https://codecept.io/basics/#within). I have tried to set the container either as XPath or CSS selector. 
#### What do you get instead?
I observed that instead of finding an element within the container, it's within the default root again. I did some investigation and realized that if the container type is not "frame", (in my case I used XPath and CSS selector), then the browser will ignore the scope you defined with "within". 

Below is the source code of CodeceptJS and where I found the problem was.
Method _withinBegin is called when "within" is used during CodeceptJS test, and *const frame = isFrameLocator(locator);* can screw up everything. **If I use a locator that is not a frame (ID, CSS, XPath...), isFrameLocator will return false, hence const frame is false, hence switchTo(false) brings you nowhere.**

The example that is given in the [document](https://codecept.io/basics/#within) is not using a frame element, so I am curious how it works. 

**node_modules/codeceptjs/lib/helper/WebdriverIO.js line 362**
```js
  async _withinBegin(locator) {
    const frame = isFrameLocator(locator);
    const client = this.browser;
    if (frame) {
      if (Array.isArray(frame)) {
        withinStore.frame = frame.join('>');
        return client
          .frame(null)
          .then(() => frame.reduce((p, frameLocator) => p.then(() => this.switchTo(frameLocator)), Promise.resolve()));
      }
      withinStore.frame = frame;
      return this.switchTo(frame);
    }

    withinStore.elFn = this.browser.element;
    withinStore.elsFn = this.browser.elements;
    this.context = locator;

    const res = await client.element(withStrictLocator.call(this, locator));
    this.browser.element = function (l) {
      return this.elementIdElement(res.value.ELEMENT, l);
    };
    this.browser.elements = function (l) {
      return this.elementIdElements(res.value.ELEMENT, l);
    };
    return this.browser;
  }
```
**node_modules/codeceptjs/lib/helper/WebdriverIO.js line 2040**
```js
function isFrameLocator(locator) {
  locator = new Locator(locator);
  if (locator.isFrame()) return locator.value;
  return false;
}
```
**node_modules/codeceptjs/lib/helper/locator.js**
```js
  isFrame() {
    return this.type === 'frame';
  }
```
### Details

* CodeceptJS version: 1.1.6
* NodeJS Version: 8.10.0
* Operating System: Mac OS X
* WebDriverIO
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Yeah, but this part of code should handle cases where the locator is not a frame:

```js
    withinStore.elFn = this.browser.element;
    withinStore.elsFn = this.browser.elements;
    this.context = locator;

    const res = await client.element(withStrictLocator.call(this, locator));
    this.browser.element = function (l) {
      return this.elementIdElement(res.value.ELEMENT, l);
    };
    this.browser.elements = function (l) {
      return this.elementIdElements(res.value.ELEMENT, l);
    };
    return this.browser;
```

We search for an element `res` then chaning `element` and `elements` function to run from that element.
As I said please provide a reproducable example with HTML and a failing test so we could take this further. Thanks!

**Comment by atrufin** [comment]
Any update to this  Bug ?

**Comment by cjwiseman11** [comment]
Having a similar issue where `within` is seemingly being ignored.

The test works fine with Puppeteer but not with Playwright

I noticed in function proceedClick, the first line in codecept/node_modules/codeceptjs/lib/helper/Puppeteer.js is:
`let matcher = await this.context;`

In Playwright it is:
`let matcher = await this._getContext();`

If I update Playwright to be the same as Puppeteer, within appears to work as expected...

**Comment by bcexopolllo** [comment]
please reopen
