### ISSUE TITLE
Passing arguments to underlying Appium driver

### ISSUE THREAD

**Issue by noumaans** [codeceptjs/CodeceptJS#1010]
#### What are you trying to achieve?
Custom Appium driver relies on yargs options which were being passed to mocha+Appium+chai setup as follows:
mocha --recursive e2e --runType sim.iPhoneX.iOS11 --reuseDevice

The options runType and reuseDevice are interpreted by the custom Appium driver.

Running similar command with codecept gives an error.

What would be the best way to pass CLI options to codecept where they are in-turn passed on to mocha / custom Appium driver?

#### What do you get instead?
```bash
> codeceptjs run --runType sim.iPhoneX.iOS11 --reuseDevice
error: unknown option `--runType`
```

### Details

* CodeceptJS version: 1.1.7
* NodeJS Version: 8.10.0
* Operating System: macOS

**Comment by guilhermenass** [comment]
Same issue here.
