### ISSUE TITLE
source-map-support for stack trace

### ISSUE THREAD

**Issue by noumaans** [codeceptjs/CodeceptJS#1011]
#### What are you trying to achieve?
With a TypeScript + mocha setup, the following mocha option generates stack traces using source-maps:
```
--require source-map-support/register
```

What would be the suggested way to accomplish the same with CodeceptJS?

Passing the following object in codecept.json does not work as stack trace still shows .js line number instead of .ts:
```json
  "mocha": {
    "require": "source-map-support/register"
  }
```

My current workaround is to add the following line to top of every test (but this is not desirable):
```typescript
import 'source-map-support/register';
```

**Comment by DavertMik** [comment]
Sorry, I'm very unfamiliar with transpilers. So any help to improve support of them in CodeceptJS is highly appreciated.
