### ISSUE TITLE
codecept.json inside test directory causes Error: Cannot find module

### ISSUE THREAD

**Issue by noumaans** [codeceptjs/CodeceptJS#1014]
#### What are you trying to achieve?
Have codecept.json located inside test directory to minimize clutter at project root.

Directory structure:
```
projectA
|-test
   |-codecept.json
   |-01_basic
      |-01_check_sanity.spec.js
```

codecept.json:
```json
{
   "tests": "**/*.spec.js"
}
```

Command executed in projectA directory:
```bash
projectA> codecept run -c test
```

#### What do you get instead?

```bash
UnhandledPromiseRejectionWarning: Error: Cannot find module '/path_to_projectA/01_basic/01_check_sanity.spec.js'
```
Path to test is obviously wrong, since it is not looking for module in test subdirectory.

### Details

Modifying tests in codecept.json to:
- `./**/*.spec.js` produces same error
- `test/**/*.spec.js` doesn't find / run any of the tests

Everything works fine if we move codecept.json outside the test directory and place it at project root, but as mentioned earlier, I'd like to minimize clutter at project root level and have codecept.json inside the test directory.

**Comment by Rob-Doherty** [comment]
We're also seeing this issue where our config file sits 2 directories down from root:
```
projectA
|-test
   |-pages
   |-configs
      |-codecept.json
```
This blocks us from easily updating to the latest release

**Comment by LukoyanovE** [comment]
Looks like bug is closed, is it?
