### ISSUE TITLE
Commands Comparison Table

### ISSUE THREAD

**Issue by allenhwkim** [codeceptjs/CodeceptJS#1019]
Hi, I have written command comparison table.
I wish this can be shareable with other users who needs to decide which helpers as a document linked from README.md

You can close this issue whether it is useful or not.

Command\Helper | WebDriverIO | Puppeteer | Nightmare | Protractor
--- | --- | --- | --- | ---
_addPopupListener |  | x |  | 
_locate | x | x | x | x
_locateCheckable | x | x |  | x
_locateClickable | x | x |  | x
_locateFields | x |  |  | 
_getWindowHandle |  |  |  | x
_locateFields |  | x |  | x
_setPage |  | x |  | 
acceptPopup | x | x |  | x
amAcceptingPopups |  | x |  | 
amCancellingPopups |  | x |  | 
amInsideAngularApp |  |  |  | x
amOnPage | x | x | x | x
amOutsideAngularApp |  |  |  | x
appendField | x | x | x | x
attachFile | x | x | x | x
cancelPopup | x | x |  | x
checkOption | x | x | x | x
clearCookie | x | x | x | x
clearField | x | x | x | x
click | x | x | x | x
closeCurrentTab | x | x |  | x
closeOtherTabs | x | x |  | x
defineTimeout | x |  |  | 
dontSee | x | x | x | x
dontSeeCheckboxIsChecked | x | x | x | x
dontSeeCookie | x | x | x | x
dontSeeCurrentUrlEquals | x | x | x | x
dontSeeElement | x | x | x | x
dontSeeElementInDOM | x | x | x | x
dontSeeInCurrentUrl | x | x | x | x
dontSeeInField | x | x | x | x
dontSeeInSource | x | x | x | x
dontSeeInTitle | x | x | x | x
doubleClick | x | x | x | x
dragAndDrop | x | x |  | x
executeAsyncScript | x | x | x | x
executeScript | x | x | x | x
fillField | x | x | x | x
grabAttributeFrom | x | x | x | x
grabBrowserLogs | x | x |  | x
grabCookie | x | x | x | x
grabCssPropertyFrom | x | x |  | x
grabCurrentUrl | x | x | x | x
grabHAR |  |  | x | 
grabHTMLFrom | x | x |  | x
grabNumberOfOpenTabs | x | x |  | x
grabNumberOfVisibleElements | x | x | x | x
grabPageScrollPosition | x | x | x | x
grabPopupText | x | x |  | x
grabSource | x | x |  | x
grabTextFrom | x | x | x | x
grabTitle | x | x | x | x
grabValueFrom | x | x | x | x
haveHeader |  |  | x | 
haveModule |  |  |  | x
haveRequestHeaders |  | x |  | 
moveCursorTo | x | x | x | x
moveTo |  |  |  | x
openNewTab | x | x |  | x
pressKey | x | x | x | x
refresh |  |  | x | x
refreshPage | x | x | x | x
resetModule |  |  |  | x
resizeWindow | x | x | x | x
rightClick | x | x |  | x
runInWeb | x |  |  | 
runOnAndroid | x |  |  | 
runOnIOS | x |  |  | 
saveScreenshot | x | x | x | x
scrollPageToBottom | x | x | x | x
scrollPageToTop | x | x | x | x
scrollTo | x | x | x | x
see | x | x | x | x
seeAttributesOnElements | x | x |  | x
seeCheckboxIsChecked | x | x | x | x
seeCookie | x | x | x | x
seeCssPropertiesOnElements | x | x | x | x
seeCurrentUrlEquals | x | x |  | x
seeElement | x | x | x | x
seeElementInDOM | x | x | x | x
seeInCurrentUrl | x | x | x | x
seeInField | x | x | x | x
seeInPopup | x | x |  | x
seeInSource | x | x | x | x
seeInTitle | x | x | x | x
seeNumberOfElements | x | x | x | x
seeNumberOfVisibleElements | x | x | x | x
seeTextEquals | x | x |  | x
seeTitleEquals | x | x |  | x
selectOption | x | x | x | x
setCookie | x | x | x | x
switchTo | x | x |  | x
switchToNextTab | x | x |  | x
switchToPreviousTab | x | x |  | x
triggerMouseEvent |  |  | x | 
uncheckOption | x |  |  | 
wait | x | x | x | x
waitForClickable |  |  |  | x
waitForDetached | x | x | x | x
waitForElement | x | x | x | x
waitForEnabled | x | x |  | x
waitForInvisible | x | x | x | x
waitForText | x | x | x | x
waitForValue | x | x | x | x
waitForVisible | x | x |  | x
waitInUrl | x | x |  | x
waitNumberOfVisibleElements | x | x |  | x
waitToHide | x | x | x | x
waitUntil | x | x |  | x
waitUrlEquals | x | x |  | x

**Comment by DavertMik** [comment]
Thanks. I think this is very useful. It would be nice if we could generate this table from the source code. To follow up with all updates.

**Comment by allenhwkim** [comment]
@DavertMik 
Source code analysis is one way. My suggestion is to run web scraping CodeceptJS documentation.
Talking about web scraping, I think it's possible with CodeceptJS, but not well-documented.

**Comment by DavertMik** [comment]
well, we have a script that builds documentation for helpers. I think I can improve it to generate a table like you proposed.

**Comment by thiagodp** [comment]
Nice work, @allenhwkim. Maybe the final table could also include Appium.

**Comment by thiagodp** [comment]
I'm extending the table to include Appium.

Legend:
- 🗸 means supported
- ☑ means inherited

<table>
    <thead>
        <tr>
            <th>Command\Helper</th>
            <th>WebDriverIO</th>
            <th>Puppeteer</th>
            <th>Nightmare</th>
            <th>Protractor</th>
            <th>Appium</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>_addPopupListener</td>
            <td></td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>_locate</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>_locateCheckable</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>_locateClickable</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>_locateFields</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>_getWindowHandle</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>_setPage</td>
            <td></td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>_switchToContext</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>acceptPopup</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>amAcceptingPopups</td>
            <td></td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>amCancellingPopups</td>
            <td></td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>amInsideAngularApp</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>amOnPage</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>amOutsideAngularApp</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>appendField</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>attachFile</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>cancelPopup</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>checkOption</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>clearCookie</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>clearField</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>click</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>closeApp</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>closeCurrentTab</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>closeOtherTabs</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>constructor</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>defineTimeout</td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
            <td>☑</td>
        </tr>
        <tr>
            <td>dontSee</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>dontSeeCheckboxIsChecked</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>dontSeeCookie</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>dontSeeCurrentUrlEquals</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>dontSeeElement</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>dontSeeElementInDOM</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>dontSeeInCurrentUrl</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>dontSeeInField</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>dontSeeInSource</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>dontSeeInTitle</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>doubleClick</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>dragAndDrop</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>executeAsyncScript</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>executeScript</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>fillField</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>grabAllContents</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>grabAttributeFrom</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabBrowserLogs</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabContext</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>grabCookie</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabCssPropertyFrom</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabCurrentActivity</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>grabCurrentUrl</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabHAR</td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>grabHTMLFrom</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabNetworkConnection</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>grabNumberOfOpenTabs</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabNumberOfVisibleElements</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabOrientation</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>grabPageScrollPosition</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabPopupText</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabSettings</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>grabSource</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabTextFrom</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>grabTitle</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>grabValueFrom</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>haveHeader</td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>haveModule</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>haveRequestHeaders</td>
            <td></td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>hideDeviceKeyboard</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>installApp</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>makeTouchAction</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>moveCursorTo</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>moveTo</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>openNewTab</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>openNotifications</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>pressKey</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>pullFile</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>refresh</td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>refreshPage</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>removeApp</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>resetModule</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>resizeWindow</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>rightClick</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>rotate</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>runInWeb</td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>runOnAndroid</td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>runOnIOS</td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>saveScreenshot</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>scrollPageToBottom</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>scrollPageToTop</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>scrollTo</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>see</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeAppIsInstalled</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeAppIsNotInstalled</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeAttributesOnElements</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeCheckboxIsChecked</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeCookie</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeCssPropertiesOnElements</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeCurrentActivityIs</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeCurrentUrlEquals</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeDeviceIsLocked</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeDeviceIsUnlocked</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeElement</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeElementInDOM</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeInCurrentUrl</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeInField</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeInPopup</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeInSource</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeInTitle</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeNumberOfElements</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeNumberOfVisibleElements</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeOrientationIs</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>seeTextEquals</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>seeTitleEquals</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>selectOption</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>setCookie</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>setSettings</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>shakeDevice</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>simulateTouchId</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>startActivity</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>swipe</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>swipeDown</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>swipeLeft</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>swipeRight</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>swipeTo</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>swipeUp</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>switchTo</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>switchToNative</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>switchToNextTab</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>switchToPreviousTab</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>switchToWeb</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>tap</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>touchPerform</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
        </tr>
        <tr>
            <td>triggerMouseEvent</td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>uncheckOption</td>
            <td>🗸</td>
            <td></td>
            <td></td>
            <td></td>
            <td>☑</td>
        </tr>
        <tr>
            <td>wait</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitForClickable</td>
            <td></td>
            <td></td>
            <td></td>
            <td>🗸</td>
            <td></td>
        </tr>
        <tr>
            <td>waitForDetached</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitForElement</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitForEnabled</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitForInvisible</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitForText</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitForValue</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitForVisible</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitInUrl</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitNumberOfVisibleElements</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitToHide</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitUntil</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
        <tr>
            <td>waitUrlEquals</td>
            <td>🗸</td>
            <td>🗸</td>
            <td></td>
            <td>🗸</td>
            <td>☑</td>
        </tr>
    </tbody>
</table>

**Comment by DavertMik** [comment]
still a good point to have one but looks like we need a script to generate this out of docs.

THIS TABLE WILL BE HUGE
