### ISSUE TITLE
Errors when running puppeteer with docker

### ISSUE THREAD

**Issue by wburningham** [codeceptjs/CodeceptJS#1022]
#### What are you trying to achieve?

I'm trying to run tests in Puppeteer in Docker. May just need to use more `docker run` flags or change something in the `codeceptjs.json`.

#### What do you get instead?

Here is [the repo with my setup for reproducing the error](https://github.com/wburningham/codecept-test).

From within that repo I run
```
docker run --net=host -v /Code/codecept-test:/tests codeception/codeceptjs
```
Which uses the `codeception/codeceptjs` docker image with ID `5bbce4c27fdb`

and I get the following error

```bash
CodeceptJS directory has been found.
CodeceptJS v1.1.7
Using test root "/tests"

My first test file @feature_set_1 --
 ✖ "before each" hook: codeceptjs.before for "test something @one @example" in 47ms
Error: Failed to launch chrome!
[0411/155101.763032:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
[0411/155101.763032:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-- FAILURES:

  1) My first test file @feature_set_1
       "before each" hook: codeceptjs.before for "test something @one @example":
     Failed to launch chrome!
[0411/155101.763032:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md


  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 0 passed, 1 failed   // 58ms
```

### Details

From within the docker image I pulled the following

* CodeceptJS version: `v1.1.7`
* NodeJS Version: `v8.9.1`
* Operating System: `uname -a` provides `Linux linuxkit-025000000001 4.9.75-linuxkit-aufs #1 SMP Tue Jan 9 10:58:17 UTC 2018 x86_64 GNU/Linux`
* Puppeteer version: whatever is install in the docker image
* Configuration file: [link](https://github.com/wburningham/codecept-test/blob/master/codecept.json)
* Suite config: [link](https://github.com/wburningham/codecept-test/blob/master/test1.js)

**Comment by wburningham** [comment]
I did a docker pull on the `codeception/codeceptjs` image and got id `f976668debef` The same error still occurs.

Any advice?

**Comment by M4zD4i** [comment]
I have the same issue with ImgID f976668debef. At this time used the same fix into config

**Comment by mralexho** [comment]
@wburningham perhaps this will help explain https://www.google.com/googlebooks/chrome/med_26.html

**Comment by iamdempa** [comment]
Using the `node:14` helped me to fix these problems.
