### ISSUE TITLE
Need multiple browsers' handles in single test case flow

### ISSUE THREAD

**Issue by vigneshwar-v** [codeceptjs/CodeceptJS#1041]
#### What are you trying to achieve?
Running / getting different browsers' handles in same test case
#### What do you get instead?
I dont know how to get it

### Details

I have a different need. I need two browsers inside same test case and need to switch between browsers in the same test case flow.

Like I want to choose, driver1 -> chrome,driver2->firefox and using both driver1 and driver2 in the same test case.

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

**Comment by DavertMik** [comment]
I'm currently working on that
