### ISSUE TITLE
No colorized console output after enabled AnsiColor Plugin in Jenkins

### ISSUE THREAD

**Issue by truesrc** [codeceptjs/CodeceptJS#1042]
#### What are you trying to achieve?
Colorized console output
#### What do you get instead?
No colorized console output
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 1.1.7
* NodeJS Version: 
* Operating System: win7
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by DavertMik** [comment]
Sorry you didn't provide any information and I don't have Jenkins to try.
But CodeceptJS outputs valid chars which should be handled by AnsiColor correctly.

**Comment by mirao** [comment]
It works for me in Jenkins 2.204.2 and CodeceptJS 2.4.3
I have enabled the option `Color ANSI Console Output` and set `ANSI color map = xterm` in job with a test.
Test is started over SSH and then over `docker-compose`. I suggest to pass `TERM=xterm` to `docker-compose` and start `codeceptjs run` with the option `--colors`.

This is how console output in Jenkins looks (timestamp plugin is used):
![image](https://user-images.githubusercontent.com/12584138/74051867-14910280-49d9-11ea-80fb-29704b72050c.png)

Note the colorized output doesn't work when running `codeceptjs run-multiple` in dockerized environment. However it's not related to Jenkins, it happens even in bash terminal. See #1876
