### ISSUE TITLE
run-multiple ignores WebDriverIO os & os_version capability

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/CodeceptJS#1047]
#### What are you trying to achieve?
Use `run-multiple` with `os` and `os_version` capabilities to run test on specific environment within BrowserStack.

#### What do you get instead?
`os` and `os_version` are not passed as `desiredCapabilities` when used within `multiple` config.

![image](https://user-images.githubusercontent.com/635526/39613762-2037da52-4f6a-11e8-9f16-e279e27e288a.png)

When I use the `run` command and configure the `desiredCapabilities` in WebDriverIO helper config prop, it works:

```js
    helpers: {
        WebDriverIO: {
            url: 'https://xxx',
            browser: 'Safari',

            // If present in ENV vars, CodeceptJS will use BrowserStack,
            // otherwise it falls back to local browser defined above
            user: process.env.BROWSERSTACK_USER,
            key: process.env.BROWSERSTACK_KEY,

            desiredCapabilities: {
                os: 'OSX',
                os_version: 'High Sierra',
            }
        }
    },
```

![image](https://user-images.githubusercontent.com/635526/39613789-8bc391da-4f6a-11e8-952b-e236d1095341.png)

### Details

* CodeceptJS version: 1.1.8
* NodeJS Version: 9.11.1
* Operating System: Mac OS X 10.13.4
* WebDriverIO
* Configuration file:

```js
    multiple: {

        'browserstack-desktop': {
            browsers: [
                {
                    browser: 'Safari',
                    desiredCapabilities: {
                        os: 'OSX',
                        os_version: 'High Sierra',
                    }
                },

            ]
        }
    }
```

**Comment by pablopaul** [comment]
I looked a little bit more into it and it turns out that when extend the WebDriverIO helper config with a an empty object as `desiredCapabilities` like this:

```js
    helpers: {
        WebDriverIO: {
            url: 'xxx',
            browser: 'chrome',
            desiredCapabilities: {},
        },
```

then the `desiredCapabilities` in the `multiple` config will get applied, since https://github.com/Codeception/CodeceptJS/blob/master/lib/command/run-multiple.js#L130 replaces the object keys, and if the key is not there in the "initial" WebDriverIO helper config, it can´t replace anything.

How could CodeceptJS check if there is a helper config used in `run-multiple` which is not in the initial WebDriverIO config and therefore would not be applied? Basically it could be a check that every object key of a run-multiple browser is also provided in helpers.WebDriverIO - or how would you approach that @DavertMik ?

**Comment by mirao** [comment]
I got the same issue when I tried to set headless mode in "multiple" section:
```js
multiple: {
        dev: {
            browsers: [
                {
                    browser: "chrome",
                    outputName: "chrome",
                    desiredCapabilities: {
                        chromeOptions: {
                            args: ["--headless", "--disable-gpu", "--no-sandbox"]
                        }

                    }
                },
                {
                    browser: "firefox",
                    outputName: "firefox",
                    desiredCapabilities: {
                        "moz:firefoxOptions": {
                            args: ["--headless"]
                        }
                    }
                }
            ]
        }
}
```
Headless mode in `run-multiple` doesn't work unless I set empty object for `desiredCapabilities` in helper setting:
```js
helpers: {
        WebDriver: {
            // ...
            desiredCapabilities: {},
        }
}
```
**Used SW:**
- CodeceptJS 2.3.6, WebDriverIO 5.16.15

**Comment by mirao** [comment]
> Headless mode in run-multiple doesn't work unless I set empty object for desiredCapabilities in helper setting

It's easier with Playwright. This `run-multiple` config:
```js
multiple: {
        dev: {
            browsers: [
                {
                    browser: "chromium",
                    outputName: "chromium"
                },
                {
                    browser: "firefox",
                    outputName: "firefox"
                }
            ]
        }
}
```
together with Playwright's helper option `show: false` does the trick and headless mode works for both Chromium/Firefox
