### ISSUE TITLE
[WebdriverIO] Starting browser occasionally hangs

### ISSUE THREAD

**Issue by DanDeMicco** [codeceptjs/CodeceptJS#1062]
#### What are you trying to achieve?
Testing via saucelabs and travis-ci

#### What do you get instead?
```_before``` occasionally hangs, causing the travis job to time out due to 10 minutes of inactivity. Seems to not be respecting the ```timeout``` property.

Looking at saucelabs, the recording shows the test starting, but browser not opening and timing out after about 90 seconds.

The browser connection should timeout after whatever is set as the ```timeout``` in the config, and it would respect the retries.

> Provide console output if related. Use `--verbose` mode for more details.

```
Controls --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook WebDriverIO._beforeSuite()
 Check document preview zoom @ci @chrome @firefox @edge @ie @safari @android @ios
   Emitted | test.before
   [1] Queued | hook WebDriverIO._before()
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

### Details

* CodeceptJS version: 1.1.6
* NodeJS Version: 8
* Operating System: linux? 
* Protractor || WebDriverIO || Nightmare version (if related)
WebDriverIO 4.12.0
* Configuration file: 
https://github.com/box/box-content-preview/blob/master/codecept.conf.js

**Comment by DanDeMicco** [comment]
This is most likely a webdriverio issue, but just posting here first to get some input

**Comment by pablopaul** [comment]
@DanDeMicco 
Can you upgrade to CodeceptJS 1.1.8?
Which node version you exactly use? 8.9+ is required for CodeceptJS 1.1.8.

**Comment by DanDeMicco** [comment]
Just upgraded to latest codeceptjs, will report back in a few days.

Node is 8.11.1

**Comment by DanDeMicco** [comment]
Hey @pablopaul have been running 1.1.8 for a few weeks now and still receiving failures, almost daily. Any suggestions?

**Comment by DanDeMicco** [comment]
Looking at saucelabs, I can see there is a POST to /session which returns back with a 200, but then no further commands get sent.
