### ISSUE TITLE
Error REST module, expects string instead of object

### ISSUE THREAD

**Issue by javigomez** [codeceptjs/CodeceptJS#1072]
#### What are you trying to achieve?
I.sendPostRequest('/api/users.json', { "email": "user@user.com" });

But actually to make it work you need to do this:
I.sendPostRequest('/api/users.json', **JSON.stringify(**{ "email": "user@user.com" }**)**);

#### Expected?
We should be able to pass the Object when sending a POST without having to be stringified as the documentation states: https://codecept.io/helpers/REST/#sendpostrequest

#### What do you get instead?

```bash
<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>SyntaxError: Unexpected token # in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (/usr/src/app/node_modules/body-parser/lib/types/json.js:157:10)<br> &nbsp; &nbsp;at parse (/usr/src/app/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /usr/src/app/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/usr/src/app/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/usr/src/app/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/usr/src/app/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at emitNone (events.js:106:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:208:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1064:12)</pre>\n</body>\n</html>\n
```

### Details

* CodeceptJS version: 1.2.0
* NodeJS Version: 8
* Operating System: MacOS
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "REST": {
      "config": {
        "endpoint": "localhost:1337"
      }
    }
  },
  "include": {},
  "bootstrap": false,
  "mocha": {},
  "name": "myproject"
}

```

**Comment by mirao** [comment]
Same issue for me. This works for me:
```javascript
I.haveRequestHeaders({
        'Content-Type': 'application/json',
});
I.sendPostRequest('/login', JSON.stringify({
        username: "user",
        password: "pass"
}));
```
But if I passed the 2nd argument as a JSON without `stringify()`, I would get an error "Invalid JSON" because the body is sent as `'username=user&password=pass'`

If I specify headers inside `I.sendPostRequest()`, I don't need to stringify JSON and it works well:
```javascript
I.sendPostRequest('/login', {
        username: "user",
        password: "pass"
}, { 'Content-Type': 'application/json' });
```
**Used SW:**
- CodeceptJS 1.4.4
- NodeJS 8.13
- Ubuntu 18.10
