### ISSUE TITLE
Add Nativescript helper

### ISSUE THREAD

**Issue by noumaans** [codeceptjs/CodeceptJS#1078]
Have a helper which can talk to {N} Nativescript Appium based driver.
This will support users on Nativescript platform to leverage CodeceptJS for e2e mobile app testing.

I already have a baseline helper written, would be interested to see if repo owners would accept a PR.

**Note** this would be a separate helper called NSAppium derived from Helper, since the NativeScript Appium driver element locator methods are different from WebDriverIO.

**Comment by DavertMik** [comment]
> I already have a baseline helper written, would be interested to see if repo owners would accept a PR.

Yes, sure! If you need anything from my side, I'd eager to help. Please send PR.

Btw, could you suggest something to read about Nativescript Appium? 😉

**Comment by DavertMik** [comment]
If you are using https://docs.nativescript.org/plugins/ui-tests it appears to be using selenium-webdriver package API. So you can probably take some code from Protractor helper which also based on top of selenium-webdriver API. However, I'm not sure how much of code could be shared. Anyway, take a look, maybe you will find it useful.

**Comment by noumaans** [comment]
Would you be willing to take a PR in TypeScript? Or, do you want me to convert it to JS?
Just want to ensure things would LGTM when I submit a PR... :)

**Comment by DavertMik** [comment]
If you want to do TypeScript - better to publish that as the standalone package. I will make a link to it on site. 

For CodeceptJS I'd ask to have it as ES7 to maintain consistent codebase.

**Comment by noumaans** [comment]
@DavertMik best resource is:
https://github.com/NativeScript/nativescript-dev-appium

There are links to Blogs, Demos and Videos in README on github page.

I'll modify the code to use ES7 and just provide type definitions as .d.ts so people who are using TypeScript can refer to them.

**Comment by DavertMik** [comment]
@noumaans any updates? 😉

**Comment by noumaans** [comment]
sorry still haven't gotten spare time to convert my TS code into JS... its probably only a few hours task, but busy with another open-source project for a few more days.
