### ISSUE TITLE
do we have any way to combine multiple test runs into one report.

### ISSUE THREAD

**Issue by govindn** [codeceptjs/CodeceptJS#1090]
#### What are you trying to achieve?
Suppose I am running three test case in parallel mode(i.e. codeceptjs run-multiple parallel) so three report gets generated each have details on one test case each,

But I want one report which has information of all three test run just like test run in normal mode(i.e without parallel mode). 

#### What do you get instead?

three separate reports generated with details of one test case in each report

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 1.2.1
* NodeJS Version: v9.10.1
* Operating System: mac
* Protractor || WebDriverIO || Nightmare version (if related) : protractor
* Configuration file: 

```js
# paste suite config here
```

**Comment by jsparks19** [comment]
I'm also interested in this. Running multiple tests in parallel is awesome, but from what I can tell the results are spit out in the console individually. Soon I'd like to hook this up to a build server but I'm not sure how to tell if the entire execution passed. Are there any ways to aggregate the results into a single pass/fail?

**Comment by elena-dev-thought** [comment]
I've created a script which is merging all the results from the reporters at the end in one. I will host it on my github and I'll let you know.

**Comment by Vaahin** [comment]
Any update on this ?

**Comment by markjackson02** [comment]
This works https://www.npmjs.com/package/junit-merge
