### ISSUE TITLE
[docs] Special keys supported by pressKey

### ISSUE THREAD

**Issue by thiagodp** [codeceptjs/CodeceptJS#1135]
The link in the documentation of [`pressKey`](https://codecept.io/helpers/WebDriverIO/#presskey) is pointing to an [outdated](https://github.com/seleniumhq/selenium-google-code-issue-archive#/session/:sessionId/element/:id/value) page. So I made a list of special keys supported by WebDriverIO, according to its [constants](https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/constants.js). I recommend to add them to the documentation, somewhere.

Special keys in alphabetical order (*case sensitive!*):
- `Add`
- `Alt`
- `ArrowDown` or `Down arrow`
- `ArrowLeft` or `Left arrow`
- `ArrowRight` or `Right arrow`
- `ArrowUp` or `Up arrow`
- `Backspace`
- `Command`
- `Control`
- `Del`
- `Divide`
- `End`
- `Enter`
- `Equals`
- `Escape`
- `F1` to `F12`
- `Home`
- `Insert`
- `Meta`
- `Multiply`
- `Numpad 0` to `Numpad 9`
- `Pagedown` or `PageDown`
- `Pageup` or `PageUp`
- `Pause`
- `Semicolon`
- `Shift`
- `Space`
- `Subtract`
- `Tab`

**Comment by thiagodp** [comment]
@xt1 @DavertMik I believe this Issue can be closed now that  version `1.3.1` included the list I prepared...

![image](https://user-images.githubusercontent.com/2997844/42355347-02f9d3b8-80a3-11e8-8b0f-c9e8f707bb89.png)

**Comment by auto-qa-git** [comment]
@thiagodp How about when we need to press Ctrl and P together?
