### ISSUE TITLE
Feature request - in settings enable continue after fail step inside scenario

### ISSUE THREAD

**Issue by rebajz** [codeceptjs/CodeceptJS#1158]
Sometimes it is good to let the scenario run, even if it contains a mistake (error may be more than one on same place).

Please enable set something as: continue after fail step in scenario. (protractor continue after fail step to next step and show both (or more) diff).

**Comment by SchnuckySchuster** [comment]
I have defined lots of Scenarios in many *_test.js files.
If one of the fails, test execution is abborted.
I need a way to tell codeceptjs to continue with the next scenario.
Is that already possible?
