### ISSUE TITLE
Share Before and After steps for different test file

### ISSUE THREAD

**Issue by vitoo** [codeceptjs/CodeceptJS#1159]
Hello,

How can i share Before and After steps for different test file

```js
Feature('Login');

Before((I) => { 
    I.amOnPage('/');
    I.click('.cookieOk');
});

After((I) => { 
    I.executeScript(function () {
        localStorage.clear();
    });
});

Scenario('I login successfully', (I) => {
    I.login('test','test');
    I.wait(5);
});

```

I want a baseTest.js with the before and after steps, than i can include in different test file (login, post ...)
To not repeat my code. How can i achieve this ?

Thanks for your help !

**Comment by jokumer** [comment]
Do you need for selected tests or all tests in one run?

**Comment by jokumer** [comment]
https://github.com/Codeception/CodeceptJS/blob/master/docs/hooks.md
