### ISSUE TITLE
how to write custom funtion other than steps_file???

### ISSUE THREAD

**Issue by zeeshan774r** [codeceptjs/CodeceptJS#1160]
If i want to write a function on certain page which i am testing.can i write it on that page likely contact_test.js other than steps_file.js.if yes plz suggest how to write them.

**Comment by vitoo** [comment]
Generate page object

`codeceptjs gpo
`
https://codecept.io/pageobjects/

**Comment by zeeshan774r** [comment]
That is fine i know that, i am asking how to make function on seperate file that i have made for different test cases.i can write custom function in steps_file.js i know that but there we can write login and such fuction which is used every where.but i want to write custom function in different page such as contact_test.js ,about_test.js,like i want to make a function for button click then why should i write it in steps_file.js,i rather choose to write in that particular file bcoz it used in that page only

**Comment by GSasu** [comment]
@zeeshan774r I don't understand why would you want to build a custom function in your test files?
You have multiple options to create custom functions.

PageObjects:
[Link](https://codecept.io/pageobjects/#pageobject)
StepObject:
[Link](https://codecept.io/pageobjects/#stepobjects) - though this is nothing more than a pageObject without locators

Actor:
[Link](https://codecept.io/pageobjects/#actor)

Something the documentation doesn't mention is the fact that you can have multiple actors such as:

AdminActor.js
```
"use strict";

module.exports = function() {
    return actor({
        login: function(
            url = config.admin.url,
            username = config.admin.username,
            password = config.admin.password
            ) {
                this.amOnPage(url);
                this.fillField(locator, username);
                this.fillField(locator, password);
                this.click(locator);
            },
            
            customFunctionOnlyAdminCanDo: function(param) {
                this.waitForVisible(locator, 20);
                this.fillField(locator, param);
            }
        });
    };
```

ClientActor.js
```
"use strict";

module.exports = function() {
    return actor({
        login: function(
            url = config.url,
            username = config.client.username,
            password = config.client.password
            ) {
                this.amOnPage(url);
                this.fillField(locator, username);
                this.fillField(locator, password);
                this.waitForVisible(locator, 5);
                this.click(locator);
            }
        });
    };
```

in your codecept.conf.js

```
include: {
        asClient: "./path/to/ClientActor.js",
        asAdmin: "./path/to/AdminActor.js",
```

you can use your new actors in your tests as such:
```
let I, asAdmin, asClient;

Feature("My test feature");

// notice that the actor you need to use in your test gets passed in next to I
Before((I, asAdmin) => {
    asAdmin.login(config.admin.url.rooms);
    // some setup or other code you are interested in
    });
    
    // Same as above, the actor needed in this section is passed in next to I as dependency.
    Scenario("My testy test that tests", (I, asClient) => {
        asClient.login();
        // some other functions/code/calls here
    });

```
