### ISSUE TITLE
Hello,How to save clipboard content to a variable in codeceptjs?

### ISSUE THREAD

**Issue by poonamagashe** [codeceptjs/CodeceptJS#1164]
In an app there is a copy-to-clipboard icon.After clicking it, I want the content which is in JSON format in a variable

I tried pasting the content in the textarea and then grabText.If we can directly save to local variable it would be better.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by GSasu** [comment]
hi @poonamagashe, I believe for this you would need to build a custom helper that gives you the clipboard text you need, hopefully this can give you an idea of what you need to accomplish that
https://stackoverflow.com/questions/6413036/get-current-clipboard-content/6413100#6413100

**Comment by syddel** [comment]
Did you find a solution to this? I'm trying out CodeceptJS at the moment, but cannot figure out how to read the contents of the clipboard in to a variable.
