### ISSUE TITLE
How to validate a select dropdown is pre-populated with a value?

### ISSUE THREAD

**Issue by austinmehmet** [codeceptjs/CodeceptJS#1169]
#### What are you trying to achieve?
As I navigate to one of my pages, a particular select dropdown should be pre-populated with data. None of the I.see* have worked for me and there is no I.seeValueSelected function

I have had to make the following helper: 
```
async seeValueSelected(selector, value) {
    const page = await this.helpers.Puppeteer.page
    const select = await page.$(selector)
    const selectValue = await select.getProperty('value')
    return assert.equal(await selectValue.jsonValue(), value)
  }
```

Is there a built in function to validate select dropdown values?

**Comment by ITJula** [comment]
If you want to check that some particular value is selected in the dropdown, you can use I.seeInField().
Note, that it checks the value (of the option) and not its text.

I.see() will check that some value is present in the dropdown (in the options) and not that it is selected.
