### ISSUE TITLE
Repeat code on same page after refresh

### ISSUE THREAD

**Issue by hallefsantos** [codeceptjs/CodeceptJS#1182]
Hi, my name is Hallef, I'm trying to do something.
I wanted to repeat an if on page until a class disappears, how could I do that?

I only managed to repeat it once and then to reload. I need him to just go to the next page when he disappears.

`const puppeteer = require('puppeteer');

(async() => {
    try {
        const width = 1300;
        const height = 1080;
        const browser = await puppeteer.launch({headless: false});
        const page = await browser.newPage();
        page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36');
        page.setViewport({ width: 1300, height: 1080 });
        await page.goto('file:///Users/hallefsantos/Documents/pup_testes/page01.html');
        
        // ========= Page 01 ==================
        await page.waitFor(2000);
        await page.click('a');
        // ==================================

        // ========= Page 02 ==================
        await page.waitFor(2000);
        await page.click('a.next');
        // ==================================

        // ========= Page 03 ==================
        if (await page.$('.next.disable') !== null) {
            console.log('encontrado');
            await page.waitFor(2000);
            await page.reload();
        }
        else {
            await page.click('a.next');
        }
        // await page.click('a');
        // ==================================        

    } catch (e) {
        console.log('our error' + e);
    }
})();
`

**Comment by GSasu** [comment]
@hallefsantos Hi, you can have a look [here](https://codecept.io/basics/#retries) and see if this would fit your needs, or let me know if not and what the limitations are.
