### ISSUE TITLE
Codeceptjs fails to find xpaths that use the second or greater instance of the element.

### ISSUE THREAD

**Issue by Jtech42** [codeceptjs/CodeceptJS#1183]
For example: 

(.//*[contains(@cname, 'Girls')]/ins)[3]

Always fails, codeceptjs returns that xpath is an "invalid locator" which is weird because every other tool (like Chrome inspector) seems to find locators fine like that.

**Comment by sergejkaravajnij** [comment]
I agree. It should work so but it don't :(

**Comment by LukoyanovE** [comment]
Is it true for `{xpath: "(.//*[contains(@cname, 'Girls')]/ins)[3]" }` locator too?

**Comment by sergejkaravajnij** [comment]
> Is it true for `{xpath: "(.//*[contains(@cname, 'Girls')]/ins)[3]" }` locator too?

Well, it would be fine if you test it yourself and write back here about results, isn't it? )

**Comment by Jtech42** [comment]
> Is it true for `{xpath: "(.//*[contains(@cname, 'Girls')]/ins)[3]" }` locator too?

I've seen it fail for this as well, in fact I think this would fail for me for a different reason entirely (if I didn't put the "xpath" in quotes when using codeceptjs).

**Comment by GSasu** [comment]
@Jtech42 locators with indexes pose issues for most frameworks. Try being a bit more precise in selecting the secondary element ie:
```
{xpath: "(.//*[contains(@cname, 'Girls')]/ins[contains(text(), 'some InnerHTML text you care about
')])" }
```
