### ISSUE TITLE
How to change for desired URL without reloading the page for WebDriverIO

### ISSUE THREAD

**Issue by egel** [codeceptjs/CodeceptJS#1191]
#### What are you trying to achieve?

Change for the desired URL without reloading the whole page.

Looking for something similar like `moveTo` method which is defined for CodeceptJS for Protractor but it's missing in WebDriverIO.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

NOTE: I replaced fragile data with XXX

```bash
→ yarn run test-e2e

yarn run v1.9.4
$ codeceptjs run --steps
CodeceptJS v1.3.3
Using test root "/XXX/cssp/client"

EVN --
  Sample test
   I am on page "/"
   I click "Zum Login"
   I fill field "#user_name", "XXX"
   I fill field "#user_password", "XXX"
   I click "Anmelden"
   I wait for text "XXX", 6000
   I see in current url "/start"
  ✖ FAILED in 2694ms


-- FAILURES:

  1) EVN
       Sample test:
     I.moveTo is not a function

  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 0 passed, 1 failed   // 8s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

> Provide test source code if related

```js
Scenario.only('Sample test', async (I) =>  {
  I.login();
  I.moveTo('/users/evn?startDate=2018-07-01&endDate=2018-07-31&vertragsId=2') // But this method only exist in CodeceptJS for Protractor
  I.waitForText('EVN', 10);
  I.seeInCurrentUrl('/users/evn?startDate=2018-07-01&endDate=2018-07-31&vertragsId=2');
});
```

### Details

* CodeceptJS version: 1.3.3
* NodeJS Version: 8.11.3
* Operating System: MacOSX 
* WebDriverIO
* Configuration file:

```js
{
  "tests": "./e2e-tests/*.e2e.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://localhost:8080",
      "browser": "chrome",
      "windowSize": "1366x768"
    }
  },
  "include": {
    "I": "./e2e-tests/steps_file.js"
  },
  "bootstrap": false,
  "mocha": {}
}
```

**Comment by LukoyanovE** [comment]
@egel ,
Protractor helper's moveTo uses Angular's setLocation, which, as I can see, is not implemented in WebDriverIO.

It's Protractor feature for Angular apps testing.


You can use some navigation button/link to necessary path.
Or maybe you can use somehow Angular's `$location.url()` on page. I don't know, just assume.

**Comment by GSasu** [comment]
@egel 
You can use I.amOnPage(). and pass in a relative url path since the base path come from config.
You can also build your own helper basing it on wdio actions such as [browser.url();](http://webdriver.io/api/protocol/url.html)
