### ISSUE TITLE
Setting WebDriverIO "services" doesn’t work

### ISSUE THREAD

**Issue by niksy** [codeceptjs/CodeceptJS#1196]
#### What are you trying to achieve?

Use [`wdio-chromedriver-service`](https://github.com/atti187/wdio-chromedriver-service) with WebDriverIO helper. Same configuration works OK with classic WebDriverIO runner, but not with CodeceptJS. Idea here is not to use Selenium, but to hook to native Chrome instance and run tests.

#### What do you get instead?

```bash
Homepage --
  ✖ "before each" hook: codeceptjs.before for "should hide privacy policy notice" in 19ms
Error: Can't connect to WebDriver.
Error: connect ECONNREFUSED 127.0.0.1:9515

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

-- FAILURES:

  1) Homepage
       "before each" hook: codeceptjs.before for "should hide privacy policy notice":
     Can't connect to WebDriver.
Error: connect ECONNREFUSED 127.0.0.1:9515

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
  
  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 0 passed, 1 failed   // 28ms
```

### Details

* CodeceptJS version: v1.3.3
* NodeJS Version: v8.11.2
* Operating System: macOS High Sierra 10.13.6
* WebDriverIO v4.13.2
* Configuration file:

```js
{
  "tests": "./test/codecept/*.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "/",
      "browser": "chrome",
      "path": "/",
      "port": "9515",
      "services": ["chromedriver"]
    }
  },
  "bootstrap": false,
  "mocha": {},
  "name": "browser-acceptance-tests-research"
}
```

**Comment by DavertMik** [comment]
Hi, sorry. wdio services are not supported yet (

**Comment by lokeshJR** [comment]
Hi @DavertMik , Are wdio services supported now?

**Comment by hungtruongquoc** [comment]
> Hi @DavertMik , Are wdio services supported now?

I don't think so. I followed the documentation still had to manually start the selenium standalone.

**Comment by gosua** [comment]
@hungtruongquoc https://codecept.io/plugins/#wdio
