### ISSUE TITLE
Throwing inside scenario or helpers won't fail test

### ISSUE THREAD

**Issue by Akxe** [codeceptjs/CodeceptJS#1210]
#### What are you trying to achieve?

``` js
class PuppetHelper extends Helper {

	/**
	 * @private
	 * @return {import("puppeteer").Page}
	 */
	get page() {
		return this.helpers.Puppeteer.page;
	}

	/**
	 * @param {string} property Property to look for on element
	 * @param {string} selector Element to look for
	 * @param {string | RegExp} [equalsTo] If specified, value will be tested against it
	 * @return {Promise<string | void>} undefined is returned if equalsTo is specified
	 */
	async seeStylePropertyOnElement(property, selector, equalsTo) {
		/** @type {number | string} */
		const propertyValue = await this.page.evaluate((property, selector) => {
			const CSSUnitValue = document.querySelector(selector).computedStyleMap().get(property);
			return CSSUnitValue.value || CSSUnitValue.toString();
		}, property, selector);

		if (equalsTo == void 0) {
			return propertyValue;
		} else {
			if (!`${propertyValue}`.match(equalsTo)) {
				throw new Error(`style['${property}'] "${propertyValue}" does not match ${equalsTo.toString()}`);
			}
		}
	}
}
```

#### What do you get instead?

> Emitted | step.before (I grab style property on element "transform", "video")
>    Emitted | step.after (I grab style property on element "transform", "video")
>    Emitted | step.start (I see style property on element "transform", "video", "non-translate")
>      I see style property on element "transform", "video", "non-translate"
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I see style property on element "transform", "video", "non-translate")
>    Step finished in 0.002 sec
>    Emitted | step.finish (I see style property on element "transform", "video", "non-translate")
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I click ".rotate-control")
>    Emitted | step.finish (I click ".rotate-control")
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I see style property on element "transform", "video", /rotateZ?\(270deg\)/)
>    Emitted | step.finish (I see style property on element "transform", "video", /rotateZ?\(270deg\)/)
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I click ".rotate-control")
>    Emitted | step.finish (I click ".rotate-control")
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I see style property on element "transform", "video", /rotateZ?\(180deg\)/)
>    Emitted | step.finish (I see style property on element "transform", "video", /rotateZ?\(180deg\)/)
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I click ".rotate-control")
>    Emitted | step.finish (I click ".rotate-control")
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I see style property on element "transform", "video", /rotateZ?\(90deg\)/)
>    Emitted | step.finish (I see style property on element "transform", "video", /rotateZ?\(90deg\)/)
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I click ".rotate-control")
>    Emitted | step.finish (I click ".rotate-control")
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>    Emitted | step.failed (I grab style property on element "transform", "video")
>    Emitted | step.finish (I grab style property on element "transform", "video")
>    Emitted | test.passed ([object Object])
>    Emitted | test.finish ([object Object])
>    [1] <within> Error | Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
> Error: style['transform'] "translate(-50%, -50%)" does not match non-translate
>   √ OK in 10498ms
> 
>    Emitted | test.after ([object Object])
>    Emitted | suite.after ([object Object])
> 
>   OK  | 1 passed   // 12s
>    Emitted | global.result ([object Object])
>    Emitted | global.after ([object Object])

```js
I.seeStylePropertyOnElement('transform', 'video', 'non-translate');
```

### Details

* CodeceptJS version: 1.3.3
* NodeJS Version: 9.11.1
* Operating System: Windows
* Puppeteer
* Configuration file:

```js
exports.config = {
	output: './output',
	helpers: {
		Puppeteer: {
			show: true,
			url: URL,
			chrome: { executablePath },
		},
		videoHelper: {
			require: './extensions/video.helper.js',
		},
		puppetHelper: {
			require: './extensions/puppet.helper.js',
		},
	},
	include: {
		I: './extensions/steps.js',
	},
	bootstrap: false,
	teardown: null,
	tests: './**/*.test.js',
	timeout: 10000,
	name: 'our-web',
}
```

**Comment by tusarnayak108** [comment]
so there is no way available for the developer to fail the test?

**Comment by lind-eduard** [comment]
Are there any updates on this? I need to fail test in event listener, but also not able to do it

**Comment by truetone** [comment]
👍

**Comment by mirao** [comment]
You can use:
```js
require("assert").fail("Test failed");
```
