### ISSUE TITLE
idea for new Helper

### ISSUE THREAD

**Issue by rebajz** [codeceptjs/CodeceptJS#1221]
In my work i must test CEF browser used in normal windows program.

Some time i must doing some steps outside browser. For this, i use autoit scripts. Yesterday i found this https://www.npmjs.com/package/autoit

It will be cool create new Heper (as protractor, appium etc.) for autoit and enable write test for windows desktop... (work with windows, mouse, keyboard, etc.)

**Comment by PeterNgTr** [comment]
I'm afraid you would create your own helper, cause if there is strong demand for this, it's worth to be in the core. :)
