### ISSUE TITLE
Is there a nice way to share data between BDD steps?

### ISSUE THREAD

**Issue by anabellaspinelli** [codeceptjs/CodeceptJS#1239]
#### What are you trying to achieve?
I'm trying to share data between BDD steps. I managed to do it with a global variable in the steps file (which is not a very nice solution I know) but then realised the value remains there from the previous test if I don't re-set it.

So far this hasn't caused much problems because I don't rely on the initial state for the 2nd test. But I think tests should be isolated and not affect each other.

So is there a nicer way to do this? Or maybe a way to run a cleanup between BDD scenarios?

For clarification, this is my code

```gherkin
  Scenario: List all apps with phantom card
    Given I have 3 apps in my account
    When I go into the apps panel
    Then I should see my apps

  Scenario: User creates an app and gets secret
    Given I am in the apps panel
    When I create a new app
    Then I see the new app in the list
```

```js
let appsCount = 0

Given(/I have (\d+) apps? in my account/, (count) => {
  appsCount = count
})

When(/I (go into|am in) the apps panel/, () => {
  I.amOnPage(`/#/section/apps?QA_initialCount=${appsCount}`)
})
```

### Details

* CodeceptJS version: 1.4.2
* NodeJS Version: 10.8.0
* Operating System: OSX HighSierra 10.13.6
* Configuration file:

```js
{
  "output": "./_output",
  "helpers": {
    "Puppeteer": {
      "url": "http://localhost:9000",
      "show": true,
      "waitForNavigation": "networkidle0",
      "windowSize": "1920x1080"
    }
  },
  "include": {},
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {
    "features": "./tests/features/*.feature",
    "steps": [
      "./tests/step_definitions/editAppSteps.js",
      "./tests/step_definitions/appsListSteps.js",
      "./tests/step_definitions/createAppSteps.js"
    ]
  },
  "plugins": {
    "screenshotOnFail": {
      "enabled": true
    }
  },
  "tests": "./tests/*_test.js",
  "timeout": 10000,
  "name": "paprikations"
}

```

**Comment by anabellaspinelli** [comment]
Hey @GSasu I think I made a mistake on the question above, now I have corrected it to look like your suggestion. What I'm trying to avoid is having global variables like these that can make one test affect the next since there's no easy/nice way of cleaning them up after running. I'll research about background though.

Thank you!

**Comment by GSasu** [comment]
You can always use ```delete global.variableName``` you can try using [sessions](https://codecept.io/acceptance/#multiple-sessions) though i don't know if they work or how well they work with cucumber in codeceptjs, if you have issues let me know and i can start investigating alternatives.
