### ISSUE TITLE
How can i debug JS code when wring with codeceptJS?

### ISSUE THREAD

**Issue by omeriko** [codeceptjs/CodeceptJS#1244]
Hi guys,

I'm working with IntelliJ , how do i set up debug configuration for CodeceptJS ?
I know how to use pause(), however the debugger lets me debug only the "I" api.

**Comment by xeonarno** [comment]
What do you want to do, I am not sure to understand what you want.

**Comment by GSasu** [comment]
@xeonarno I believe he is trying to achieve the same thing that codeceptjs offers for vsCode but in webstorm/intellij. He wants to be able to click the debug button, place some breakpoints and step in/out/over using intellijs debugger rather than vscode

**Comment by xeonarno** [comment]
@GSasu What codeceptjs do for VSCode ? I'm very interesting !

**Comment by GSasu** [comment]
@xeonarno the codeceptjs documentation shows multiple ways of debugging. One of the things it targets is setting up your preferred editor debugger to be able to just click Debug, start the tests and stop at a breakpoint to be able to continue to step in/out/over etc.

[CodeceptJS documentation](https://codecept.io/advanced/#debug)

**Comment by sandeepscet** [comment]
Getting  error of outFiles in vscode with below launch config

![image](https://user-images.githubusercontent.com/1390862/79943381-64368480-8486-11ea-9166-7f8592000522.png)


```
{
    "type": "node",
    "request": "launch",
    "name": "codeceptjs",
    "args": ["run"],
    "program": "${workspaceFolder}/node_modules/.bin/codeceptjs"
  }
```

This error suggest that debugger need main file from where it can start debugging.
For express , its mostly app.js

Any such file/config for codeceptjs?
