### ISSUE TITLE
waitForText

### ISSUE THREAD

**Issue by rebajz** [codeceptjs/CodeceptJS#1252]
In page i have uses text: Not Connected
When i use method waitForText('Connected') test go to next step immediately.

Now work as partial, better will be equal.

**Comment by xMutaGenx** [comment]
If using `WebDriverIO`, that's where you would use https://codecept.io/helpers/WebDriverIO/#seetextequals to assert for exact match. If you need to wait for the text beforehand, you can easily extend the functionality with a custom step, or use implicit waits.

**Comment by eduard-lind** [comment]
or you can also use I.waitForVisibility('//*[text()="<your text here>"]'); Using XPath you can even specify an element, where you want to see a text.
