### ISSUE TITLE
codeceptJS + nightmare + nightmare-download-manager not working

### ISSUE THREAD

**Issue by tastafur** [codeceptjs/CodeceptJS#1265]
#### What are you trying to achieve?
i am trying use this plugin nightmare-download-manager 

#### What do you done?
I have seen that Codecept instance Nightmare and I have tried in all the ways that have occurred to me to add the plugin that needs to be added before Nightmare is instanced and as I have not seen how I ended up making a fork of codecept, there is some other way to add actions to Nightmore before it is installed or has to be added as a new functionality for this type of Nightmore plugins. Below I leave information of what I have researched and done.

The problem comes from this issue here is implemented this plugin.
https://github.com/segmentio/nightmare/issues/151
Info:
https://electronjs.org/docs/api/download-item

And this line is the one that I had to add to my fork so that the plugin works because it needs to be added before Nightmare instants
https://github.com/tastafur/CodeceptJS

thanks

**Comment by DavertMik** [comment]
Let me look for it. Send a pull request from your fork and I will look if this is ok to get it into the main codebase.
