### ISSUE TITLE
How to call executeScript inside helper

### ISSUE THREAD

**Issue by vitaly87** [codeceptjs/CodeceptJS#1289]
#### What are you trying to achieve?
I am trying to get selector of visible element from screen,
When I am trying to call executeScript I am getting error 

     this.executeScript is not a function

my code:

```

 async clickOnVisibleElement (selector) {

   let visbleSelector= await this.executeScript(function(selector) {

      !function(e,t){var n=function(e){var n=[];for(;e&&e.tagName!==t;e=e.parentNode){if(e.className){var r=e.className.split(" ");for(var i in r){if(r.hasOwnProperty(i)&&r[i]){n.unshift(r[i]);n.unshift(".")}}}if(e.id&&!/\s/.test(e.id)){n.unshift(e.id);n.unshift("#")}n.unshift(e.tagName);n.unshift(" > ")}return n.slice(1).join("")};e.fn.getSelector=function(t){if(true===t){return n(this[0])}else{return e.map(this,function(e){return n(e)})}}}(window.jQuery)
      return $(selector + ":visible").getSelector()[0];
      }, selector); // passing jquery selector
    return visbleSelector;
  }

```

also what is the best way to put the first line to be common and be reuse?

**Comment by LukoyanovE** [comment]
https://codecept.io/helpers/

If you use WebDriveriIO `this.helpers['WebDriverIO'].executeScript( ...`
or `this.helpers.WebDriverIO.executeScript( ...`

Change name of helper, if You use other one.

**Comment by LukoyanovE** [comment]
If you want use browser realization (not Codecept) `this.helpers['WebDriverIO'].browser.executeScript( ...`
But be careful with arguments
