### ISSUE TITLE
Gherkin + Chunk combination

### ISSUE THREAD

**Issue by kulin24** [codeceptjs/CodeceptJS#1297]
#### What are you trying to achieve?
I am trying to execute the gherkin scenarios in parallel using chunk functionality.
#### What do you get instead?
The scenarios are not executed in parallel. The chunk configuration is not taking effect.
> Provide console output if related. Use `--verbose` mode for more details.

```bash
Admins-MacBook-Pro:Codeceptv1 admin$ npm run test

> codecept_poc@1.0.0 test /Users/admin/Desktop/My_Data/QuantumJS/Codeceptv1
> codeceptjs run-multiple wiki

Use JS config file
undefined
Nothing scheduled for execution
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codecept_poc@1.0.0 test: `codeceptjs run-multiple wiki`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codecept_poc@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2018-10-31T13_21_59_165Z-debug.log


```

> Provide test source code if related

```js
console.log('Use JS config file');

console.log(process.profile);
var deviceCaps = require('./test-config/devices/deviceCaps.json')

exports.config = {
    tests: './*_test.js',
    timeout: 10000,
    output: './output',
    helpers: {
        PerfectoWebDriverIO: {
            action: "PerfectoWebDriverIO Test",
            require: "./perfectowebdriverio.js",
            url: "https://google.com/",
            host: "<HOST>",
            path: "<PATH>",
            port: "<PORT>",
            jobName: "PerfectoWebDriverIO Test Job",
            buildNumber: 38,
            branch: "Not Branched Yet",
            projectName: "Perfecto-CodeceptJS Example Tests",
            projectVersion: "v0.1a",
            tags: ["codeceptjs", "webdriverio", "nodejs", "example tag"],
            restart: false,
            logLevel: "verbose",

            desiredCapabilities: {
                browserName: "Firefox",
                user: "<USER>",
                securityToken: "<TOKEN>",
                platformName: "Windows",
                platformVersion: "10",
                browserVersion: "62",
                resolution: "1280x1024",
                location: "US East"
            }
        }
    },
    mocha: {
        reporterOptions: {
            mochaFile: './output/result.xml',
        },
    },
    name: 'tests',
    bootstrap: './bootstrap.js',
    include: {
        I: "./custom_steps.js",
        Smth: "./pages/Smth.js",
        loginPage: "./pages/Login.js",
        signinFragment: "./fragments/Signin.js"
    },
    gherkin: {
        features: "./features/*.feature",
        steps: [
            "./step_definitions/steps.js",
            "./step_definitions/wiki_steps.js"
        ]
    },
    timeout: 10000,
    multiple: deviceCaps
};

```
DeviceCaps.json file:

{
  "wiki": {
    "chunks": 2,
    "browsers": [
      {
        "browser": "Firefox",
        "browserName": "Firefox",
        "user": "kulins@perfectomobile.com",
        "securityToken": "<TOKEN>",
        "platformName": "Windows",
        "platformVersion": "10",
        "browserVersion": "62",
        "resolution": "1280x1024",
        "location": "US East"
      },
      {
        "browser": "Chrome",
        "browserName": "Chrome",
        "user": "<USER>",
        "securityToken": "<TOKEN>",
        "platformName": "Windows",
        "platformVersion": "10",
        "browserVersion": "70",
        "resolution": "1280x1024",
        "location": "US East"
      }
    ],
    "grep": "@wiki"
  }
}

### Details

* CodeceptJS version: 1.4.4
* NodeJS Version: 5.7.1
* Operating System: Mac
* Protractor || WebDriverIO || Nightmare version (if related) WebdriverIO
* Configuration file: Shared above

**Comment by kulin24** [comment]
If I remove the chunks configuration then the scenarios are executing as expected in sequential manner on two browsers chrome and firefox in parallel.

So the question is, do we support chunks with gherkin approach?

**Comment by kdelalic** [comment]
Any updates here?

**Comment by kulin24** [comment]
No, there is no update on this issue. This bug still exists as far as I know.

**Comment by vitoo** [comment]
Parralel execution is not working with Gherkin scenario  :disappointed:

**Comment by PredragPavlovic** [comment]
@kulin24 did you find out what is problem? Does it work now?

**Comment by mayankchincholkar** [comment]
Any updates on this issue?

**Comment by kulin24** [comment]
I don’t have any updates on this issue.
Because of this bug and one more issue we ended up writing our own Wdio + cucumber fraemwork.

I don’t think the owners of this framework has given us any acknowledgment on this issue nor do we have any ETA on the resolution of this issue.

**Comment by evanjmg** [comment]
This is still an issue

**Comment by gkushang** [comment]
Parallel Executions with Gherkin is still an issue

**Comment by eugengaspar** [comment]
Yes, unfortunately, it still is :( 
Even with codecept 2.6.2

**Comment by gkushang** [comment]
I have faced issues in Before After hooks when Browser session closes or launches, and issue is still there specifically with WebDriver.

cc @koushikmohan1996

**Comment by javierfuentesm** [comment]
@kulin24  do you have some docs of how to use , or where you get the PerfectoWebDriverIO helper ?im trying to check if there is a way to connect with perfecto mobile.
Thanks in advance

**Comment by ttupper92618** [comment]
@javierfuentesm / @kulin24 I'm looking for an example of perfecto integration - can either of you assist?
