### ISSUE TITLE
Why don't we fully support Typescript?

### ISSUE THREAD

**Issue by trinhpham** [codeceptjs/CodeceptJS#1302]
As first, I don't want to make any war or comparison about pros/cons of TS vs JS.
I need TS as its our stakeholders requirement.

Playing around with CodeceptJS took me to some strange things:
- CodeceptJS isn't shipped with any TS definition
- To get the TS definition, I must use command `codeceptjs def .` which generates a steps.d.ts. However, that file is complained by `tsc`  command right at the first time I compile the TS project.
- The generated file doesn't have enough definition, some are: 
  - `function Data()` returns any type => the call to `Scenario` warns about the type of the given `I`
  - There's no definition for class `Datatable`

You know my problem, is there any plan to fully support TypeScript like other frameworks/libraries?

**Comment by LukoyanovE** [comment]
> CodeceptJS isn't shipped with any TS definition
Codecept was created for JS, and TS support was not main target. Now we are working on it.
Yep, I agree that we should create typings and ship it as separate package.

> The generated file doesn't have enough definition, some are:
Yep, not all definitions are correctly completed. Contributors correct the lack of definitions periodically. But there are not so many TS users.
Please, improve definitions by committing, when you see.

> You know my problem, is there any plan to fully support TypeScript like other frameworks/libraries?
It's not implemented yet.
I'm working on ts-node requiring for codecept.
I think, we should add Project to Codecept repository, so everybody could see progress.

Something like:
- add support for ts-node requiring
- create separate typings repository and move codecept definitons into it (maybe not)
- change `codeceptjs def` to create typings file for user defined functions
...

@trinhpham, please add more improvements goals

**Comment by trinhpham** [comment]
It's great to know that you are working on this.
At this moment, I think adding typings definition is the biggest thing to be done.
Get it done and our users would raise more improvement request.
I (and maybe many are there) always want to help, if you agree, public your progress and detail tasks + requirements then you should see the power of the community 😄

**Comment by dkozickis** [comment]
I'd vote for keeping TS defs inside this repo :)

**Comment by LukoyanovE** [comment]
TS support was added.
https://codecept.io/configuration/#require

Maybe, typings should be

**Comment by Naimadnap** [comment]
@LukoyanovE could you prepare some full example? I have updated codecept to 1.4.5 version but it breaks tests which I described earlier witch generated typings.

**Comment by prosenjit-manna** [comment]
Also If there is an option when the project is being generated like 
- Javascript 
- Typescript

That will be a lot easier.

**Comment by DavertMik** [comment]
If you wish to improve TS support in CodeceptJS - please send pull rquests.
At this moment our team do not have resources for that
