### ISSUE TITLE
Running codeceptjs with multiple browsers

### ISSUE THREAD

**Issue by omeriko** [codeceptjs/CodeceptJS#1311]
#### What are you trying to achieve?

I'm running this command:
codeceptjs run-multiple parallel --profile "oracle,Change123" --grep "@Hosted|@PrivateSqlServer" --invert 

#### What do you get instead?

I'm getting the following error message

> Provide console output if related. Use `--verbose` mode for more details.

error: unknown option `--invert' 

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:^1.4.3
* NodeJS Version: 8.12.0
* Operating System: windows 10 enterprise
* Protractor || WebDriverIO || Nightmare version (if related):  WebDriverIO
* Configuration file: codecept.conf.js

```js
# paste suite config here
```

exports.config = {
  multiple:{
    parallel: {
      chunks: 2
    }
  },
  output: "./output",
  helpers: {
    WebDriverIO: {
      url: "https://ids.ics.dev/identity-service/home",
      browser: "chrome",
      smartWait: 5000,
      windowSize: "maximize"

    },
    cihHelper: {
      require: "./helpers/cih_helper.js"
    },    
    RestHelper: {
      require: "./helpers/restHelper.js"
    }
  },
  multiple: {
    parallel: {
      // Splits tests into 2 chunks
      chunks: 2
    }
  },
  plugins: {
    stepByStepReport: {
      enabled: true,
      deleteSuccessful:true
    },
    allure: {
      enabled: true
    }
  },
  include: {
    I: "./logicalOperations.js"
  },
  mocha: {},
  bootstrap: false,
  teardown: null,
  hooks: [],
  gherkin: {},

  tests: "./tests/OnlineSubscription/*.js",

  timeout: 10000,
  name: "build-assets",
  auth: {}
};
// we use 1 parameter to update config
if (process.profile) {
  let params = process.profile.split(",")
  // update config for cloud service provider
  exports.config.auth.user = params[0];
  exports.config.auth.pass = params[1];
} else {

  exports.config.auth.user = 'hosted1@infa.com';
  exports.config.auth.pass = '******';
}

**Comment by EgorBodnar** [comment]
Fixed in #1322
