### ISSUE TITLE
[feature-request] using multiple frameworks while running features

### ISSUE THREAD

**Issue by Rob-Meijeren** [codeceptjs/CodeceptJS#1320]
I would like to request a thing that I am really missing here. 

That you define which frame work a feature should run on. 

e.g.

@framework('protractor')
Feature x

@framework('webdriverio')
Feature y

To what degree this is feasible I don't know but I think it would be cool. Also a good thing for if you want to migrate from 1 framework to another.

**Comment by xMutaGenx** [comment]
Hey Rob, you can achieve this with dynamic configuration: https://codecept.io/advanced#dynamic-configuration
