### ISSUE TITLE
CodeceptJS + allure: does not show meta streps 

### ISSUE THREAD

**Issue by gagandeepsingh26** [codeceptjs/CodeceptJS#1339]
While running the test suite with the following settings:
1. Allure plugin is enabled.
2. use --steps

CLI report and allure report does not show meta steps.

when I tried with --verbose it gave an error message

Error processing step.start event:
    TypeError: step.metaStep.actor.index is not a function
    at EventEmitter.event.dispatcher.on (codeceptjs/lib/plugin/allure.js:95:47)

https://github.com/Codeception/CodeceptJS/blob/d16220da48c1728aa4139fbffa5c3d91fb4c92ef/lib/plugin/allure.js#L95

If I disable allure then It works fine and displays all steps and meta steps.

Thanks

**Comment by PeterNgTr** [comment]
https://github.com/Codeception/CodeceptJS/pull/1326/files
still not a proper fix, I guess

**Comment by balajioct8** [comment]
Not able to log report for createTodo in the allure report, its logging report only Scenario, what if the steps fail in createTodo ?. Please see sample code below. Can you help as I have lot if reusable functions which I am not able to log in the allure now.


module.exports = function() {
  return actor({
    createTodo: function(title) {
      this.fillField({model: 'newTodo'}, title);
      this.pressKey('Enter');
    }
  });
}

Scenario('create todo item', (I) => {
  I.dontSeeElement('#todo-count');
  I.createTodo('Write a guide');
  I.see('Write a guide', {repeater: "todo in todos"});
  I.see('1 item left', '#todo-count');
});

**Comment by SchnuckySchuster** [comment]
I want to define und use custom steps and I need to see the steps together with the screenshots in the allure test report.

Problem:
I see the screenshots but no corresponding text.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/3406054/63008875-bea52d00-be83-11e9-8ad0-836384b2fcfc.png">

I think using custom steps is vital for biger tests suites as is having a propper report.

**Comment by DavertMik** [comment]
I hope this was fixed in revent releases
