### ISSUE TITLE
 bootstrapAll/teardownAll pathes not working with run-multiple parallel

### ISSUE THREAD

**Issue by vitaly87** [codeceptjs/CodeceptJS#1346]
#### What are you trying to achieve?
I am trying to run bootstrapAll/teardownAll with run-multiple parallel but getting error 
#### What do you get instead?

> throw new TypeError('Path must be a string. Received ' + inspect(path));
   ^

**Comment by LukoyanovE** [comment]
Looks like global variables, defined for `run` and several others commands happens in Codecept.init()
```
  init(dir) {
    this.initGlobals(dir);
    // initializing listeners
    Container.create(this.config, this.opts);
    this.runHooks();
  }
...
  initGlobals(dir) {
    global.codecept_dir = dir;
    global.output_dir = fsPath.resolve(dir, this.config.output);
...
```

`run-multiple` does not call `Codecept.init` , 
I think `codecept_dir` and `output_dir` definiton should be moved to separate method and called for each command before `Codecept` instance creation

**Comment by DavertMik** [comment]
Should be fixed with workers
