### ISSUE TITLE
CodeceptJS hangs on CircleCI

### ISSUE THREAD

**Issue by KalleVuorjoki** [codeceptjs/CodeceptJS#1349]
#### What are you trying to achieve?
I try to run basic test on Circle CI, on my local machine it works without issues. Tried with global and local Puppeteer / Codeceptjs / Nightmare. Unlike suspected in #1140, I don't believe the issue is missing Xfvb, because I'm able to run basic standalone Nightmare.js examples in CircleCI.

I don't expect to anyone here to fix CircleCI issues, but I would appreciate any information how to debug the missing dependency.

#### What do you get instead?

CodeceptJS hangs without any further information. 
```bash
codeceptjs run --verbose
creating output directory: /home/circleci/web/output
CodeceptJS v1.4.6
Using test root "/home/circleci/web"
Helpers: Puppeteer
Plugins:

Frontpage --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  test something
    Emitted | test.before ([object Object])
Too long with no output (exceeded 10m0s)
```

```js
Feature('My First Test');

Scenario('test something', (I) => {
  I.amOnPage('https://github.com');
  I.see('GitHub');
});
```

### Details

* CodeceptJS version: 1.4.6
* NodeJS Version: 8.12.0
* Operating System: CircleCI / Debian Stretch - Docker (circleci/php:7.2.9-apache-node-browsers)
* Nightmare version: 2.10.0
* Chrome version: Google Chrome 69.0.3497.92
* Configuration file:

package.json
```js
{
  "name": "js-tests",
  "version": "1.0.0",
  "description": "Nightmare.js tests for UI",
  "main": "index.js",
  "scripts": {
    "test": "node node_modules/.bin/codeceptjs run --verbose"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "chai": "^4.1.2",
    "chai-moment": "^0.1.0",
    "codeceptjs": "^1.4.6",
    "mocha": "^4.1.0",
    "moment": "^2.20.1",
    "nightmare": "^2.10.0",
    "nightmare-screenshot": "^1.0.0",
    "nightmare-upload": "^0.1.1",
    "nightmare-wait-for-url": "0.0.2",
    "puppeteer": "^1.10.0"
  },
  "engines": {
    "node": ">= 6.9.0",
    "npm": ">= 3.10.0"
  }
}
```

**Comment by neutraali** [comment]
Using Gitlab CI in our case, but we might be having a similar issue, as the error output is pretty much the same. We're using `selenium/standalone-chrome:latest` as a `service` in our case. Tests run fine locally but will fail / hang once they hit CI (will also fail via `gitlab-runner`). Eventually the runner reports the following error:
```
Can't connect to WebDriver.
Error: connect ETIMEDOUT 172.17.0.2:4444
Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible
```
Running with:
```
"@wdio/selenium-standalone-service": "5.13.2"
"codeceptjs": "2.3.2"
```
