### ISSUE TITLE
Runnning Protractor with docker CodeceptJS

### ISSUE THREAD

**Issue by bhargavjulaganti** [codeceptjs/CodeceptJS#1468]
Running Protractor using Docker .

#Error: Cannot able to load codecept.conf.js

My docker-compose.yml

`version: '2'

services:
    codeceptjs:
        image: codeception/codeceptjs
        volumes:
            - "${HOST_PATH_SRC_TEST_SUITE}:/CodeceptJS-Test-Suite"
        depends_on:
            - selenium-chrome
    selenium-chrome:
        image: selenium/standalone-chrome:3.5.3
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"`

My Codecept.conf.js file 

`exports.config = {
  tests: './tests/*_test.js',
  output: './output',
  helpers: {
    Protractor: {
      url: 'https://sbeta.com',
      key:'asndksandkland',
      driver: 'hosted',
      browser: 'chrome',
      angular: false,
      host: chrome
    },
    REST: {
      endpoint: ""
    }
  },
  include: {
    I: './steps_file.js',
    loginPageObjectPage: './pages/LoginPageObject.js',
    MidwareObject:'./support/MidwareFunctions.js'
  },
  bootstrap: null,
  mocha: {
    reporterOptions: {
       reportDir: "output",
       reportPageTitle: " E2E Test Reports",
       reportTitle: "E2E Test Reports"
    }
  },
  name: 'codeceptjs3'
}`

* CodeceptJS version:
* NodeJS Version:
* Operating System: MAC OS
* Protractor 
* Configuration file:

**Comment by PeterNgTr** [comment]
volumes:
- "${HOST_PATH_SRC_TEST_SUITE}:/CodeceptJS-Test-Suite"

I think the mapping volume is not proper. I see it is something like :test in the doc.

**Comment by bhargavjulaganti** [comment]
the volume should be the root path of test suite . If I am not wrong

**Comment by lepadellec** [comment]
Yes bhargavjulaganti is correct, the volume mapping should be 
volumes:
  -/hostlocationoftestsuite:/tests

So in your case:
volumes:
  - ${HOST_PATH_SRC_TEST_SUITE}:/tests

You might also want to add the environment variable CODECEPT_ARGS to indicate the config file to use to run the tests (assuming that codecept.json is located in $HOST_PATH_SRC_TEST_SUITE):

environment:
      - CODECEPT_ARGS=-c codecept.json --verbose --steps

**Comment by bhargavjulaganti** [comment]
@lepadellec  As suggested I changed my volume , but when I am running using the command "docker-compose up" it cannot find any test cases in my tests folder .

Here is my docker-compose file


version: '2'

services:
    codeceptjs:
        image: codeception/codeceptjs
        depends_on:
            - selenium-chrome
        environment:
            - CODECEPT_ARGS=-c codecept.conf.js run 
        volumes:
            - /Users/bjulaganti/dev/RMS-CodeceptJS-Test-Suite:/tests
        dns:
            - 10.2.122.100
            - 10.9.122.100
    selenium-chrome:
        image: selenium/standalone-chrome:3.5.3
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444"
            - '5900'

Here is the docker output screenshot 

![image](https://user-images.githubusercontent.com/11901773/54882894-3fac4b00-4e35-11e9-9649-68639d7f3812.png)

can you let me know what I am doing wrong here

**Comment by bhargavjulaganti** [comment]
@lepadellec As suggested I changed my volume , but when I am running using the command "docker-compose up" it cannot find any test cases in my tests folder .

Here is my docker-compose file

version: '2'

services:
codeceptjs:
image: codeception/codeceptjs
depends_on:
- selenium-chrome
environment:
- CODECEPT_ARGS=-c codecept.conf.js run
volumes:
- /Users/bjulaganti/dev/RMS-CodeceptJS-Test-Suite:/tests
dns:
- 10.2.122.100
- 10.9.122.100
selenium-chrome:
image: selenium/standalone-chrome:3.5.3
volumes:
- /dev/shm:/dev/shm
ports:
- "4444"
- '5900'

Here is the docker output screenshot

![image](https://user-images.githubusercontent.com/11901773/54883146-c0b91180-4e38-11e9-835a-7e79e3110d03.png)

can you let me know what I am doing here wrong
