### ISSUE TITLE
Use proxy via REST helper

### ISSUE THREAD

**Issue by nounnoune** [codeceptjs/CodeceptJS#1566]
I would like to add a proxy parameter on REST helper, like on webdriver Helper

I don't know how I have to do

I have error 

> 502 bad gateway

```
"helpers": {
    "REST": {
      "endpoint": "http://{{url}}/LoyaltyWS/v1/",
      "defaultHeaders": {
        "X-APIKey": "test",
        "Authorization": "Bearer 011e16a1-fa4f-45ec-a1f5-0ceec532727c",
        "Accept": "application/json"
      }
    }
  }
```

```
        "WebDriver": {
            "url": "http://{{url}}:86/oskar-ng/",
            "browser": "chrome",
            "restart": false,
            "windowSize": "300x800",
            "host": "localhost",
            "port": 4444,
            "desiredCapabilities": {
                "browserName": "chrome",
                "chromeOptions": {
                  "args": [ "--user-agent=Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36"]
                },
                **"proxy": {
                  "proxyType": "pac",
                  "proxyAutoconfigUrl": "http://pac.zscaler.net/kiabi.com/kiabiDSI.pac"
                }**
            }
        }
    }

```

I did this for webdriver but I can't do it for REST helper

**My question: Is there a way to do this ?**

**Comment by PeterNgTr** [comment]
REST helper wraps `axios` so let's try to add proxy via request -> https://github.com/axios/axios#request-config

**Comment by nounnoune** [comment]
How can I proceed ? have I to overwrite my request using axios ?

**Comment by PeterNgTr** [comment]
https://codecept.io/helpers/REST

Please try onRequest which can update the request config

**Comment by HesterdeTester** [comment]
Have you had some succes? 

I had the same problem and I wrote my own helper in the end using the HTTP-client Request (npm). I had to write an async function for it in the helper and used await to wait for the result. This setup has no problems with the proxy while I couldn't get it to work with the build in REST helper.

**Comment by AdamOakman** [comment]
Maybe this will help, in my case I needed to disable proxy at all:

```
        REST: {
            endpoint: getEnv('grafUrl'),
            onRequest: (request) => {
                request.proxy = false;
            }
        }
```

By analogy try to pass proxy object to onRequest

```
proxy: {
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'mikeymike',
      password: 'rapunz3l'
    }
  }
```

**Comment by commonquail** [comment]
I was able to confirm that

> By analogy try to pass proxy object to onRequest

"works" -- that is, as suggested, the `proxy` value is passed correctly to axios -- but I simply could not get axios to communicate with our proxy the way our proxy expects. This may have been an HTTPS-over-HTTP obstacle (and it would not surprise me that the limitation is in the proxy rather than in axios, but either way).

However, I was able to disable axios' own proxy configuration and override its HTTP(S) agent with [`https-proxy-agent`](https://www.npmjs.com/package/https-proxy-agent)@5.0.0 and get _that_ working:

```js
const HttpsProxyAgent = require("https-proxy-agent");

...

  REST: {
    endpoint: "https://reqres.in", // NB: no trailing slash
    onRequest: (request) => {
        if (process.env.https_proxy) {
            // Forcefully disable axios' own proxy config, because it just
            // doesn't work right in our situation.
            request.proxy = false;
            request.httpsAgent = new HttpsProxyAgent(process.env.https_proxy);
        }
        if (process.env.http_proxy) {
            request.proxy = false;
            request.httpAgent = new HttpsProxyAgent(process.env.http_proxy);
        }
    }
```

I got this solution from [an axios ticket](https://github.com/axios/axios/issues/2072#issuecomment-567473812).
