### ISSUE TITLE
I.fillField() value have preset type as string

### ISSUE THREAD

**Issue by rebajz** [codeceptjs/CodeceptJS#1568]
method  I.fillField() - value have preset type as string, this is bad.

If some app working with types, and I use this method, i have empty field in form (because this field working only with number).

**Comment by PeterNgTr** [comment]
Web app is still okay
```
Scenario('Type in number @1', (I) => {
    I.amOnPage("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number");
    I.switchTo('#iframeResult')
    I.fillField('*//input[@type="number"]', '123');
});
```
