### ISSUE TITLE
How to wait acceptPopup except using wait 

### ISSUE THREAD

**Issue by SpenserJulia** [codeceptjs/CodeceptJS#1593]
#### What are you trying to achieve?
have a system where popup becomes visible after a few seconds.

I use 
wait (1);
I.acceptPopup();

I want to get rid of the seconds. How i can wait a popup use time in seconds to wait.

* CodeceptJS version: 2.0.8
* NodeJS Version: 10.15.3
* Operating System: ubuntu
* WebDriverIO

**Comment by SpenserJulia** [comment]
Do you have an idea how to solve the problem or is it impossible?

**Comment by eduardofinotti** [comment]
Hi @SpenserJulia . 

To Appium I created a method that can check if an element is on screen.
So you can check before each command if your popup is on screen.

But it's on PR: https://github.com/Codeception/CodeceptJS/pull/1631

You can write the same method to WebDriverIO.
Or if my PR is accepted I can write to you.

Does this work for you?

:)

**Comment by SpenserJulia** [comment]
@eduardofinotti work with popup different then usual element, but very impotant to see all solve. I am interesting to see.
I have one solve of problem, but not optimal, new method grabPopupText every 0.1ms, before text !== ""

**Comment by eduardofinotti** [comment]
@SpenserJulia Ok, but if the text can't be got, it will happen an error in your test execution. No?

**Comment by SpenserJulia** [comment]
@eduardofinotti Yes of course
