### ISSUE TITLE
Maximize option for resolution should have same functionality as manually clicking maximise button on window

### ISSUE THREAD

**Issue by hotdog2201** [codeceptjs/CodeceptJS#1600]
#### What are you trying to achieve?

When I set the windowSize to 'maximize' the browser window should be fullscreened, eg on Mac OS this would bring the window over the taskbar, hence maximising the window the same as clicking maximise should do.
#### What do you get instead?

The window is simply brought to the maximum resolution of the screen, but the option is not acting as a proper maximise, such as clicking the green maximise button on a window in mac os.

> Provide test source code if related
 helpers: {
    WebDriver: {
      host: process.profile || 'localhost',
      url: process.env.CODECEPT_URL || 'http://localhost:3000',
      browser: 'chrome',
      coloredLogs: true,
      restart: false,
      waitForTimeout: 10000,
      windowSize: 'maximize',
    },
  },

### Details

* CodeceptJS version: 2.0.8
* NodeJS Version: 11.3.0
* Operating System: Red Hat LInux, but issue tested on Mac OS
* WebDriverIO: 5.7.9
* Configuration file:
```js
exports.config = {
  tests: './e2eTests/tests/**/*.test.js',
  output: './output',

  /**
   *  actors and page objects to be registered in DI container ,
   * and included in tests. Accepts objects and module require paths
   */
  include: {
    offenses: './e2eTests/tests/offenses/offensesPageObject.js',
  },

  helpers: {
    WebDriver: {
      host: process.profile || 'localhost',
      url: process.env.CODECEPT_URL || 'http://localhost:3000',
      browser: 'chrome',
      coloredLogs: true,
      restart: false,
      waitForTimeout: 10000,
      /**
       * replace below with 'maximize' if your browser window size or position
       * is causing tests to fail
       * */
      windowSize: '1920x1080',
    },
  },
  plugins: {
    retryFailedStep: {
      enabled: true,
      retries: 10,
    },
    screenshotOnFail: {
      enabled: true,
    },
  },
  multiple: {
    parallel: {
      browsers: ['chrome', 'firefox'],
    },
  },
  bootstrap: null,
  mocha: {},
  name: 'test-ui',
};
```

**Comment by realnikunj** [comment]
no update on this yet ?

**Comment by SavitaMaurya** [comment]
Hi Team,

Any update on the issue?

**Comment by DavertMik** [comment]
sorry, this is how WebDriver works. We can't do anything on our side
