### ISSUE TITLE
Custom helper unhandledPromiseRejection with retryFailedStep plugin

### ISSUE THREAD

**Issue by mattin4d** [codeceptjs/CodeceptJS#1634]
#### What are you trying to achieve?
A custom helper that checks for a bootstrap alert containing the given text and then dismisses it.

The following works as intended in both pass & fail scenarios when the retryFailedStep plugin is disabled.
```js
seeAndDismissAlert (text) {
        const helper = this.helpers['WebDriver'];
        return helper.see(text, '.alert').then(() => {
                return helper.click(
                        locate('button')
                        .withAttr({ 'aria-label': 'Close' })
                        .inside(
                                locate('.alert').withText(text)
                        )
                );
        });
}
```

#### What do you get instead?
When the retryFailedStep plugin is enabled and there is no alert found on the page there is a "chaining cycle detected" error and the codeceptjs process exits early with a successful code 0. That of course is not good in a CI environment when basing the next stage on the codeceptjs exit code.

```bash
    I see and dismiss alert "foo bar"
(node:6862) UnhandledPromiseRejectionWarning: TypeError: Chaining cycle detected for promise #<Promise>
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6862) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ✖ FAILED in 33784ms

    # irrelevant After hook step output here
  ✖ FAILED in 33784ms
```

### Details

* CodeceptJS version: 2.1.0
* NodeJS Version: 10.15.3
* Operating System: Gentoo / Linux 4.19.27-r1

**Comment by DavertMik** [comment]
From what I see everythig is fine here...

**Comment by PeterNgTr** [comment]
isn't it `let client = this.helpers['WebDriver'].browser;` when you want to access the helper's methods?

**Comment by mattin4d** [comment]
@PeterNgTr That is what the [documentation](https://codecept.io/helpers#webdriver-example) says and did trip me up at first till I noticed all the I methods were actually available directly off `this.helpers['WebDriver']`. I am using Selenium if that makes a difference?

My helper does work 100% in pass cases, it's just certain failure cases (cant find .alert on page) that it hits these promise errors which makes the codecept process exit early with code 0 rather than exiting with >=1 after it is completely done outputting everything. Notice how I don't get the final failure summary output. Eg. `FAIL | 1 passed, 1 failed // 9s`

**Comment by PeterNgTr** [comment]
Well @mattin4d could you try to wait a bit before it? Possibly the .alert is not loaded yet due to delays

**Comment by mattin4d** [comment]
@PeterNgTr, sorry I don't think I'm being clear enough. In the output provided I am expecting the test to fail, there is no .alert containing "foo bar" on the page. I'm trying to convey that when my helper fails codecept does not finish doing it's thing and exits early with code 0. I would expect it to finish outputting reports and the failure summary and then exit with code 1 in the event of a failure.

I made a discovery this morning and realized the after hook output I omitted is actually very relevant. The helper failure was actually somehow causing the after hook to fail as well and it turned out to be the after hook failing that was making codecept exit early.

steps_file.js
```js
// ensure that indexeddb is finished writing data before moving on
waitForIdb: function () {
        return this.executeAsyncScript(async (done) => { try { await window.idbSettingData; } catch (e) { console.error(e) } finally { done(); } });
},
```
I had been doing this in our suites
```js
After(async (I) => {
        await I.waitForIdb();
});
```
I tried try/catching and that made no difference
```js
After(async (I) => {
        try {
                await I.waitForIdb();
        } catch (e) {
                console.error(e);
        }
});
```
It also made no difference re-throwing or throwing a new error in the catch.

That then lead me to trying without async/await and it appears that returning the promise directly in the hook behaves as intended.
```js
After((I) => I.waitForIdb());
```

That resolves the issue for me at least.

**Comment by mattin4d** [comment]
Did some more experimenting and I can confirm that the UnhandledPromiseRejectionWarnings are happening with ANY failed I method not just my custom helper, and only with the retryFailedStep plugin enabled. They on their own don't seem to be breaking anything so I think that issue is pretty minor.
