### ISSUE TITLE
 _switchToContext is not defined

### ISSUE THREAD

**Issue by PHUITesting** [codeceptjs/CodeceptJS#1641]
This function mentioned in the docs is not defined. I._switchToContext is not defined. The documentation for it is mostly undefined and there are no examples.

https://codecept.io/helpers/Appium

**Comment by GSasu** [comment]
@PHUITesting All functions starting with an _ are meant to be used inside a helper so try implementing a helper using that method.

**Comment by PHUITesting** [comment]
Any examples?
'''"use strict";
const Helper = codecept_helper;
const I = actor();
let browser;

class AppiumHelper extends Helper {
  /**
   * Function to switch the context of the app
   * Conext name to switch to
   */
  switchToContext(context) {
    browser = this.helpers["Appium"].browser;
    return browser._switchToContext(context);
  }


  async getPageSource() {
    browser = this.helpers["Appium"].browser;
    console.log(await browser.getPageSource());
    return browser.getPageSource();
  }
}

module.exports = AppiumHelper;
'''

Throws: browser._switchToContext is not a function

'''
  switchToContext(context) {
    browser = this.helpers["Appium"].browser;
    return _switchToContext(context);
  }
'''
     _switchToContext is not defined

**Comment by PeterNgTr** [comment]
```javascript
const Helper = codecept_helper;
let browser;

class AppiumHelper extends Helper {
  /**
   * Function to switch the context of the app
   * Context name to switch to
   */
  switchToContext(context) {
    browser = this.helpers["Appium"].browser;
    return browser.switchToContext(context);
  }

}

module.exports = AppiumHelper;
```
does it work for you @PHUITesting?
