### ISSUE TITLE
Using appium - I fill field ".android.widget.EditText" doesn't use CSS, searches by text instead and fails.

### ISSUE THREAD

**Issue by PHUITesting** [codeceptjs/CodeceptJS#1645]
I fill field ".android.widget.EditText", "Jason.legako@yum.com"

Fails when it adds details:

Field "android=new UiSelector().text(".android.widget.EditText")" was not found by text|CSS|XPath

**Comment by LukoyanovE** [comment]
@PHUITesting , is it works with `I.fillField({ android:  ".android.widget.EditText" }, "Jason.legako@yum.com");`

**Comment by PHUITesting** [comment]
Thanks for the response, I tried it with your line and this was the result:

"Field "android=new UiSelector().text(".android.widget.EditText")" was not found by text|CSS|XPath"

.android.widget.EditText is a class name in the app per the inspectors and it's also an element name. But there is no text related to these elements in this implementation unfortunately.

**Comment by raschmitt** [comment]
I'm experiencing the same behavior. is there any way to workaround this?

**Comment by idxn** [comment]
I have looked into the parseLocator() code and it's definitely a bug. The current implementation does not support native locator.

**Comment by raschmitt** [comment]
I've tried to use appendField() instead, and it seems that it suffers from the same bug.

**Comment by raschmitt** [comment]
@DavertMik any idea on how we can solve this?

**Comment by raschmitt** [comment]
I've solved this issue by placing an `#` in front of my id locator
