### ISSUE TITLE
Protractor helper - Cannot switch to and from different browsers running headless Chrome

### ISSUE THREAD

**Issue by lepadellec** [codeceptjs/CodeceptJS#1656]
#### What are you trying to achieve?
I have 2 different Electron apps that I want to test, the apps need to communicate with eachother. App1 starts up, several fields are manipulated, then app2 starts and some fields in app2 need to be manipulated before returning to app1.

So far, I am able to run app1 and to launch app2. I am able to enter data into app2 and
then switch back to app1 to manipulate the app1 BUT whenever I try to switch back to app2
(the forked browser) nothing happens.

The following code spawns the new browser:
async openNewApplication(location){
    // save current driver in global mainDriver
    mainDriver = this.helpers['Protractor'].browser.driver;
    let config = await this.helpers['Protractor'].browser.getProcessedConfig();
    config.capabilities.chromeOptions.binary = location;
    // save new ProtractorBrowser object in global forked
    forked = await this.helpers['Protractor'].browser.forkNewDriverInstance().ready;
    this.helpers['Protractor'].browser.driver = forked.driver;  
    let handles = await forked.getAllWindowHandles();
    let max = handles.length - 1;
    let authWindow = handles[max];
    await forked.driver.switchTo().window(authWindow);
  }

The following code switches back from the forked app to a new app:
async switchToMainApp()
  {
    this.helpers['Protractor'].browser.driver = mainDriver;
    let handles = await this.helpers['Protractor'].browser.driver.getAllWindowHandles();
    let max = handles.length - 1;
    let authWindow = handles[max];
    
    await this.helpers['Protractor'].browser.switchTo().window(authWindow);
  }
The following code attempts to switch back from the main app to the forked app, this generates no errors but clearly when I try to locate elements on the forked app they cannot be located so I don't think the switch to the forked browser has worked correctly:

async switchToForkedApp(){
    this.helpers['Protractor'].browser.driver = thisForked.driver; 
    let handles = await thisForked.getAllWindowHandles();
    let max = handles.length - 1;
    await this.helpers['Protractor'].browser.driver.switchTo().window(handles[max]);
  }

Details
CodeceptJS version: 2.1.1
NodeJS Version: 8.9.4
Operating System: Windows 10
Protractor
Configuration file:
{
"output": "./output",
"helpers": {
"Protractor": {
"driver": "hosted",
"browser": "chrome",
"rootElement": "body",
"directConnect": true,
"capabilities": {
"chromeOptions": {
"args": ["--no-sandbox", "--headless", "--disable-dev-shm-usage"],
"binary": "C:/calcium/calcium.exe"
}}
},
"ElementHelper": {
"require": "./helpers/element_helper.js",
"type": "electron"
},
"IwProvisioning": {
"require": "./helpers/iw_provisioning_helper.js",
"server": "dev"
},
"Iw_authentication": {
"require": "./helpers/iw_authentication_helper.js",
"server": "dev"
}
},

"include": {
"changePinPage": "./pages/change_pin.js",
"consentPage": "./pages/consent.js",
"errorOverlayPage": "./pages/error-overlay.js",
"activatePage": "./pages/activate.js",
"menuPage": "./pages/menu.js",
"aboutPage": "./pages/about.js",
"devicePage": "./pages/devices.js",
"footerPage": "./pages/footer.js",
"headerPage": "./pages/header.js",
"homePage": "./pages/home.js",
"otpPage": "./pages/otp.js",
"pushPage": "./pages/push.js",
"settings": "./pages/settings.js",
"toast": "./pages/toast.js",
"apiSteps": "./plugins/api_steps.js",
"authSteps": "./plugins/authenticator_steps.js",
"calciumSteps": "./plugins/calcium_steps.js"
},
"mocha": {},
"bootstrap": false,
"teardown": false,
"hooks": [],
"gherkin": {},
"plugins": {
"screenshotOnFail": {
"enabled": true
},
"ePlugin": {
"require": "./plugins/electron.js",
"enabled": true,
"path": "C:/Users/laura/AppData/Roaming/calcium/Local Storage/leveldb"
}
},
"tests": "./calcium/tests/0*.js",
"timeout": 100000,
"name": "codeceptio",
"params" : {
"target": "electron",
"server": "dev",
"configIdx": 0,
"appVersion": "6.5.0-0",
"build": "[0-9]+",
"libVersion": "2.0.6",
"serialNo": "[0-9a-zA-Z]+",
"menuAlwaysPresent": false,
"authenticator": "C:/authenticator6/Authenticator 6.exe"
}
}

**Comment by PHUITesting** [comment]
Would it be possible to load them in different tabs rather than different windows entirely? I don't have any tests using the window switching, but the tabbing features worked well for me recently.

**Comment by lepadellec** [comment]
THi PHUITesting, thanks for your suggestion but unfortunately I cannot simply use different tabs. The reason being is that I have two Electron applications to test (headless Chromes) that interact with eachother. The first application is launched when the testsuite starts up, this is the principal application, I then launch the second application perform an operation, return to the principal application, perform an operation and then need to return to the spawned application again, it is this stage that I can't seem to get to work the "return control to the spawned application". I can spawn the second application, manipulate it, then return to the principal application but it is this second stage "return to the spawned" application that doesn't work, frustrating as I've kept a reference to the browser object. See code for switchToForkedApp() above. Any ideas would be welcome :-D

**Comment by amireldor** [comment]
Is there any news on this? I would like to test two browsers as well (not elecron-based apps). I think I can get around with tabs but two browser instance would be nice.
