### ISSUE TITLE
[Feature request] Commands for <select multiple> element

### ISSUE THREAD

**Issue by evgeniy-mh** [codeceptjs/CodeceptJS#1667]
#### What are you trying to achieve?

Commands that will help to test `<select multiple>` html elements.
E.g:
```html
<select multiple>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="opel">Opel</option>
  <option value="audi">Audi</option>
</select>
```

It would be great if CodeceptJS will have these commands:

- Command that will add selection to selection of options.
- Command that will remove selection from selection of options.

**Comment by DavertMik** [comment]
please send PR if you have ideas how to implement it
