### ISSUE TITLE
Unable to use swipe and tap Action on codeceptjs

### ISSUE THREAD

**Issue by susantharakan25** [codeceptjs/CodeceptJS#1672]
#### What are you trying to achieve?

To perform swipe and tap on an app page to see the elements below

#### What do you get instead?

Error- swipe method can be used only with apps
makeTouchAction method can be used only with apps

> Provide console output if related. Use `--verbose` mode for more details.

### Details

* CodeceptJS version: V2.1.0
* NodeJS Version: v12.3.0
* Operating System: Mac Os
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

exports.config = {
  "tests": "features/*/*Tests.js",
  "output": "./output",
  "helpers": {
   "Appium": {
      app: "bs://xxxxxxxxxxxxxxxxxxx",
      platformName: "iOS",
      browserstack_user : "xxxxxxxx",
      host: "hub-cloud.browserstack.com",
      waitForTimeout : 3000,
      port: 4444,
      user: "xxxxxxxxxxx",
      key: "xxxxxxxxxxxx",
      device:"iPhone 8 Plus",
      browserstack_debug : "true",
  },
    "AppiumHelper": {
      require: "./helpers/appium_helper.js",
    },

  },
  "include": {
    "commonActions": "./pageactions/CommonActions.js",
    "commonObjects": "./pageobjects/CommonObjects.js"
  },
  "bootstrap": null,
  "mocha": {},
  "name": "appium",
 };

**Action.js**

I.swipe(loginPage.dobfield, 0, 0, 1000);
I.tap(loginPage.newAccount);

**Page Object**
 dobfield: {
   iOS: '~Date Input'
  },

newAccount: {
   ios: '~Create an Account',
   },

**Comment by PHUITesting** [comment]
Seeing this on my environment now, error is "makeTouchAction method can be used only with apps" when trying to run I.tap. 

Desired caps clearly specify an app though...

    "Appium": {
      app: "bs://a213118b10fa5b2bbb99f93390eabba86c60377f",
      platformName: "android",
      browserstack_user : "jasonlegako1",
      host: "hub-cloud.browserstack.com",
      waitForTimeout : 30000,
      port: 4444,
      user: "jasonlegako1",
      key: "r9p5VRUTeopjJ7ihQZgF",
      device:"Google Pixel",
      browserstack_debug : "true",
      desiredCapabilities: {
        newCommandTimeout: 0,
        deviceName: "Google Pixel",
        platform: "Android",
        automationName: "uiautomator2",
      },
    },


Am I missing a desired cap to get this to run?

**Comment by PHUITesting** [comment]
Seeing this on my environment now, error is "makeTouchAction method can be used only with apps" when trying to run I.tap. 

Desired caps clearly specify an app though...

    "Appium": {
      app: "bs://a213118b10fa5b2bbb99f93390eabba86c60377f",
      platformName: "android",
      browserstack_user : "xxx",
      host: "hub-cloud.browserstack.com",
      waitForTimeout : 30000,
      port: 4444,
      user: "xxx",
      key: "xxx",
      device:"Google Pixel",
      browserstack_debug : "true",
      desiredCapabilities: {
        newCommandTimeout: 0,
        deviceName: "Google Pixel",
        platform: "Android",
        automationName: "uiautomator2",
      },
    },


Am I missing a desired cap to get this to run?

**Comment by PHUITesting** [comment]
I commented out the line from appium that throw this error, and it still threw the error. Strangely those appium files were inside of codeceptjs folder, but it seems like the error is coming from browserstacks appium server. maybe it's a shared check between codeceptjs and other appium servers?

**Comment by PHUITesting** [comment]
Add 

platform: "android", 

inside the Appium config bracket but outside the desired capabilities bracket. Now tap and swipe are working for me.
