### ISSUE TITLE
Safari could not select file

### ISSUE THREAD

**Issue by stychu** [codeceptjs/CodeceptJS#1681]
#### What are you trying to achieve?
I want to upload a file
#### What do you get instead?
`     One or more files could not be selected.` This is happening only on Safari. On chrome and firefox, it works. I've noticed that when on pause() debugging when I manually use attach file it would upload that file 4 times rather than one and throw that error
> Provide console output if related. Use `--verbose` mode for more details.

```bash
-- FAILURES:

  1) .... @raiseDeal
       I can create a new deal:
     One or more files could not be selected.
  
  Scenario Steps:
  
  - I.attachFile("#upload-button", "sample.pdf") at Object.fillDealData (src/pages/raiseDeal.js:62:7)

```

### Details

* CodeceptJS version: 2.1.3
* NodeJS Version: 10.15.3
* Operating System: 4.6.1
* Protractor || WebDriverIO || Nightmare version (if related)     "webdriverio": "5.8.4"

**Comment by MaryanaVelyka** [comment]
@stychu have you managed to upload file in safari?
