### ISSUE TITLE
helpers not appended by default

### ISSUE THREAD

**Issue by DanielRuf** [codeceptjs/CodeceptJS#1702]
#### What are you trying to achieve?
Automatically append new helper to config file.

#### What do you get instead?

Not appended. Just the info that I should update the config myself.

Docs say that it is automatically appended:
https://codecept.io/helpers/

> This command generates a basic helper and appends it to helpers section of config file:
### Details

* CodeceptJS version: 2.1.3 (is there a `--version` flag?)
* NodeJS Version: v10.11.0
* Operating System: macOS
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

**Comment by ufko** [comment]
Looks like that behavior changed with #1433
