### ISSUE TITLE
Cannot POST JSON object with content-type application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by lepadellec** [codeceptjs/CodeceptJS#1714]
#### What are you trying to achieve?
The REST module provided by codecepjs uses axios. Due to the following issue :
https://github.com/axios/axios/issues/97
it is not possible to post JSON objects in the body of the request when content-type is
application/x-www-form-urlencoded
The following code should be added to the REST modules POST/PUT/DELETE implementations:
axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';
axios.defaults.transformRequest = [function (data, headers) {
    var str = [];
    for(var p in data)
      if (data.hasOwnProperty(p) && data[p]) {
        str.push(encodeURIComponent(p) + "=" + encodeURIComponent(data[p]));
      }
    return str.join("&");
  }];

Codeceptjs version: 2.1.2

**Comment by PeterNgTr** [comment]
you are more than welcome to make a PR :)
