### ISSUE TITLE
Wdio plugin does not properly support 'run-multiple'

### ISSUE THREAD

**Issue by cchiaverini** [codeceptjs/CodeceptJS#1739]
#### What are you trying to achieve?

To automatically start/stop selenium before test execution using the wdio plugin as documented here: https://codecept.io/plugins#wdio

#### What do you get instead?

When using this plugin and the 'run-multiple' target, the selenium instance may terminate before all threads are finished.  As a result, any remaining tests will fail.

From what I can tell, starting and stopping the wdio plugin is tied to events for a single thread:

```js
  function registerLauncher(launcher) {
    const name = launcher.constructor.name;
    if (launcher.onPrepare) {
      event.dispatcher.on(event.all.before, () => {
        recorder.add(`launcher ${name} start`, async () => {
          await launcher.onPrepare(config);
          output.debug(`Started ${name}`);
        });
      });
    }

    if (launcher.onComplete) {
      event.dispatcher.on(event.all.after, () => {
        recorder.add(`launcher ${name} start`, async () => {
          await launcher.onComplete(process.exitCode, config);
          output.debug(`Stopped ${name}`);
        });
      });
    }
  }
```

This will work properly for the 'run' target since selenium will be started/stopped before and after all of the tests execute.  In the case of the 'run-multiple' target it is a bit of a crapshoot.  

In the 'run-multiple' case, the first thread that starts will start selenium, and it will remain running until that thread ends.  If that thread ends last, then all of the tests will complete successfully.  If that thread does not end last, then selenium will be killed.  

> Provide test source code if related

### Details

* CodeceptJS version: 2.1.4
* NodeJS Version: any
* Operating System: any
* Protractor || WebDriverIO || Nightmare version (if related): N/A

* Configuration file:

#### Other comments

I see this being further complicated by the fact that run-multiple creates child threads for each process.  So those processes would need to know not to start selenium (ie they're 'run-multiple 'children), but instances invoked by 'run' would need to know they are not 'run-multiple' children (and start selenium).

In general, it seems that only starting a single selenium instance would likely be preferred.

With some guidance regarding the preferred way to handle this, and if similar situations have arisen before, I may be able to implement a fix.

**Comment by vitaly87** [comment]
+1

**Comment by PeterNgTr** [comment]
@cchiaverini would love to see the PR for it :)

**Comment by vantruongt2** [comment]
+1

**Comment by PeterNgTr** [comment]
I thought `run-multiple` will be soon deprecated in v3.0. So better to go with `run-workers`
