### ISSUE TITLE
"The development server has disconnected. Refresh the page if necessary."

### ISSUE THREAD

**Issue by remjx** [codeceptjs/CodeceptJS#1779]
#### What are you trying to achieve?
Test runs completed locally without having to manually refresh the browser intermittently

#### What do you get instead?
`JSHandle:The development server has disconnected. Refresh the page if necessary.`
Sometimes, page refresh allows the test to continue. Other times, the same error is generated and even upon refresh the same message is generated repeatedly causing test to get stuck. 

```bash
› [Browser:Info] The development server has disconnected.
Refresh the page if necessary.JSHandle:The development server has disconnected.
Refresh the page if necessary.
```

This only happens when running with Puppeteer `show: true`.

### Details

* CodeceptJS version: 2.1.4
* NodeJS Version: 10.14.2
* Operating System: macOS Mojave 10.14.3 
* Puppeteer: 1.15.0

**Comment by hubidu** [comment]
Have you already tried with puppeteer 1.19?
