### ISSUE TITLE
Geolocation Appium with CodeceptJs.

### ISSUE THREAD

**Issue by herbert-soares-ifood** [codeceptjs/CodeceptJS#1789]
Hello.
I utilize geolocation in Appium with the code: 
driver.setGeoLocation({latitude: "121.21", longitude: "11.56", altitude: "94.23"});

Link for Geolocation:
http://appium.io/docs/en/commands/session/geolocation/set-geolocation/

How i utilize the same code with CodeceptJs ?

Tks.

**Comment by yassineskiba** [comment]
Hello you have the same method on Appium Helper : https://codecept.io/helpers/Appium.html#setgeolocation

Have fun ;)
