### ISSUE TITLE
Puppeteer/Codeception multiple iFrames

### ISSUE THREAD

**Issue by maassenbas** [codeceptjs/CodeceptJS#1811]
#### What are you trying to achieve?
Insert value in an iFrame, then switch to another iFrame and insert another value there. 

#### What do you get instead?
The value into the first iFrame will be inserted, but the value in the second iFrame not. 

> Provide console output if related. Use `--verbose` mode for more details.

```bash
 Element "xyz"was not found by text|CSS|XPath
```

> Provide test source code if related

```js
    I.switchTo('#id iframe');
    I.fillField('#abc', "abc");
    I.wait(5);
    I.switchTo();

    I.switchTo('#id2 iframe');
    I.fillField('#xyz', "xyz");
    I.wait(5);
    I.switchTo();
```

### Details

* CodeceptJS version:
* NodeJS Version: v8.11.2
* Operating System: MAC
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js

exports.config = {
  tests: './tests/*_test.js',
  output: './output',
  helpers: {
      Puppeteer: {
        url: 'www.mywebsite.com',
        chrome: {
          executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
        },
        windowSize: '1440x700',
        show: true,
        waitForNavigation: ['networkidle0', 'domcontentloaded'],
          waitForAction: 750,
          waitForTimeout: 5000
     }
  },
  include: {
    I: './customsteps.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'workspace'
}

```

**Comment by xMutaGenx** [comment]
This seems like the perfect use case for https://codecept.io/basics#within
```
within({frame: "#id"}, () => {
  I.fillField('#abc', "abc");
});

within({frame: "#id2"}, () => {
  I.fillField('#xyz', "xyz");
});
```
