### ISSUE TITLE
Hey, I need to check Checkbox only if it is not checked already. How do I implement this in CodeceptJS with webDriverIO? Appreciate any help!

### ISSUE THREAD

**Issue by vaijiNeel** [codeceptjs/CodeceptJS#1859]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by rebajz** [comment]
writed in protractor helper, but must working for webDriverIO...

Scenario.only('Check checkbox only if is not checked', async (I) => {
    I.amOnPage('https://material.angular.io/components/checkbox/examples');
    let actualStatus = await I.grabAttributeFrom({id: 'mat-checkbox-1-input'}, 'aria-checked');
    if (actualStatus === false) {
        I.checkOption({id: 'mat-checkbox-1'});
    }
});
