### ISSUE TITLE
Gherkin with Typescript example?

### ISSUE THREAD

**Issue by evanjmg** [codeceptjs/CodeceptJS#1871]
#### What are you trying to achieve?
I'm trying to get gherkin and typescript setup. Globbing typescript with gherkin steps doesn't seem to work. The types do not include the gherkin Given, When, Then. The gherkin plugin doesn't support typescript. The only way to get typescript working is to generate JS files. 

#### What do you get instead?
I need to supply my own typings and use barrel syntax to require a js file - but it still doesn't require the steps. It doesn't error though and console.logs work

### Details

* CodeceptJS version: 2.3.0
* NodeJS Version: 10.16.0 (ts node 5.0.1)
* Operating System: MAC Mojave
* Puppeeter
* Configuration file: 
```
 {
  gherkin: {
    features: './e2e/features/*.feature',
    steps: ['./e2e/step_definitions/index.js'] // use barrel here - otherwise it errors
  },
  require: ['ts-node/register']
}
```

**Comment by luchsamapparat** [comment]
https://github.com/ngxp/demo/tree/feature/codecept-js/e2e

Have a look at this project.

**Comment by evanjmg** [comment]
thanks @luchsamapparat
