### ISSUE TITLE
REST helper defaultHeaders are ignored

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/CodeceptJS#1873]
Currently the `defaultHeaders` config in the REST helper is ignored, it is used [here](https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/REST.js#L53) but it does not have any effect on the actual request.

**Comment by pablopaul** [comment]
Would be fixed with #1626 , specifically this line: https://github.com/Codeception/CodeceptJS/pull/1626/files#diff-f89aa2e0ea9f0ae22d9a724b9c80fbabR84

`request.headers = Object.assign(request.headers, this.headers);`

**Comment by IanHong66** [comment]
I upgraded to CodeceptJS v3.0.0. It seems this problem is still not resolved?

**Comment by PeterNgTr** [comment]
Yeah, that PR is not merged yet.
