### ISSUE TITLE
Trying to write BDD test cases .

### ISSUE THREAD

**Issue by sumiagar** [codeceptjs/CodeceptJS#1878]
#### What are you trying to achieve?
Trying to use BDD functionality in my project 
I have init the Gherkin and able to write feature and step file. But not able to access custom functions whihc I have defined  into actor .

#### What do you get instead?
I used const I = actor();
it shows I.see(0
but I.navigateTo(); not able to access 
> Provide console output if related. Use `--verbose` mode for more details.

```bash
1) Business rules
       Verify the settings sub menu:
     I.navigateTo is not a function
```

> Provide test source code if related

```js
const I = actor();

// Add in your custom step files


Given('I am on portal', () => {
  within({frame: "#PORTAL"},() => {
    I.see("watch tv");
  }); 
});

When('launch settings menu', () =>{
    I.navigateTo('settings');
});

Then('verify all the settings submenus',(settings) => {
  settings.verify_the_Settings_options();
});
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
 include: {
    I: './lib/utility/utility.js',   // this is my customStep file which has return the actor and has navigateTO()
    settings: './modules/settings/main.js',
    portal: './modules/portal/main.js'
  },
  mocha: {},
  bootstrap: null,
  teardown: null,
  hooks: [],
  gherkin: {
    features: './features/*.feature',
    steps: ['./step_definitions/steps.js']
  },
```

**Comment by DavertMik** [comment]
Use 

```js
// instead of const I = actor();
const { I } = inject();
```

We introduced `inject` for such purposes

**Comment by sumiagar** [comment]
> Use
> 
> ```js
> // instead of const I = actor();
> const { I } = inject();
> ```
> 
> We introduced `inject` for such purposes

Thanks for reply ..
When I am using inject it shows 

PS C:\ws\N_TEST\NET_Codecept_Automation\NET_UI_Codecept_Automation> ..\node_modules\.bin\codeceptjs run --features

Could not include object Step Definition from ./step_definitions/steps.js from module 'C:\ws\N_TEST\NET_Codecept_Automation\NET_UI_Codecept_Automation\step_definitions\steps.js'
inject is not defined

**Comment by sumiagar** [comment]
> > Use
> > ```js
> > // instead of const I = actor();
> > const { I } = inject();
> > ```
> > 
> > 
> > We introduced `inject` for such purposes
> 
> Thanks for reply ..
> When I am using inject it shows
> 
> PS C:\ws\N_TEST\NET_Codecept_Automation\NET_UI_Codecept_Automation> ..\node_modules.bin\codeceptjs run --features
> 
> Could not include object Step Definition from ./step_definitions/steps.js from module 'C:\ws\N_TEST\NET_Codecept_Automation\NET_UI_Codecept_Automation\step_definitions\steps.js'
> inject is not defined

Please help me out . Inject shows undeclare. 
Do I need to add or update anything else

**Comment by javierfuentesm** [comment]
Did you update the version of codeceptJS ??
