### ISSUE TITLE
Right Click does not open the context menu with Firefox

### ISSUE THREAD

**Issue by eisenreich** [codeceptjs/CodeceptJS#1883]
#### What are you trying to achieve?
Open a context menu with a right click.

#### What do you get instead?
The following error.

```
 1) Feature 1
       Scenario 1.1
     unknown variant `pointerDown`, expected one of `none`, `key`, `pointer` at line 1 column 45

  Scenario Steps:

  - I.rightClick({xpath: .//p[contains(., 'Text with a context menu')]}) at Test.Scenario (tests\context_menu_test.js:26:9)
```

The tests code:

```js
      I.rightClick(locate("p").withText("Text with a context menu"));
      I.seeElement("Context item 1")
```

### Details

* CodeceptJS version: 2.3.0
* NodeJS Version: 10.16.2
* Operating System: Windows 10
* WebDriverIO: 5.12.4
* Firefox: 68.0.2

### Update
I changed the driver to puppeteer and now the `rightClick` is working.

**Comment by DavertMik** [comment]
try `forceRightClick`
