### ISSUE TITLE
[question] How to run CodeceptJS in parallel using the custom runner

### ISSUE THREAD

**Issue by simonsen78** [codeceptjs/CodeceptJS#1913]
Hi

Is there any way to run codeceptjs programatically like you can with Nightwatch?

- https://nightwatchjs.org/guide/running-tests/#programmatic-api

I tried searching but found no current info.
Thanks.

**Comment by PeterNgTr** [comment]
hi @simonsen78 
out of curiosity, what would be the benefits when you use it with codeceptjs? 🤔

**Comment by simonsen78** [comment]
I am exposing a service (via a webpage) for running tests internally in our company.

Currently using Jest in this way for API and lower level stuff, and would love to be able to (easily) use codeceptjs to let people run our web tests.

**Comment by simonsen78** [comment]
Ok.

So I found out how to run it in code using the custom runner (), but there is no mention of running parallel profiles like "multiple" in codecept.conf.js file.

Any ideas on how to do this?

So far I can only run tests sequentially, which is pretty slow.

**Comment by PeterNgTr** [comment]
maybe this could help https://www.npmjs.com/package/mocha-parallel-tests

**Comment by DavertMik** [comment]
Currently we have it here https://codecept.io/parallel/#custom-parallel-execution
