### ISSUE TITLE
[Question] Is it possible to use the reporter argument when using run-workers command?

### ISSUE THREAD

**Issue by ipapagia** [codeceptjs/CodeceptJS#1938]
#### What are you trying to achieve?
It would be handy if it was possible to generate a report (xml) when running tests in parallel with the `run-workers` command:
e.g: 
`npx codeceptjs run-workers --reporter=mocha-multi 5 --config=codecept.conf.js`
#### What do you get instead?

```bash
$npx codeceptjs run-workers --reporter=mocha-multi 5 --config=concurrent.conf.js
error: unknown option `--reporter'
```
Tests are executed normally when the reporter option is omitted

### Details

* CodeceptJS version: 2.3.2
* NodeJS Version: v12.11.0

**Comment by orihomie** [comment]
I am also have interest in this.

**Comment by PeterNgTr** [comment]
AFAIK, we can enable allure plugin when using run-workers command, and in the end Allure has built-in aggregation functionality, just put two or more allure results bundles in one folder and use it as a source for your report. You will get report with two suites in it.

**Comment by ipapagia** [comment]
Indeed, allure plugin works fine with the workers command,
But given that a ci/cd system might already be configured to report using the mocha-junit-report or other reporters, it would be a great addition to provide such an option for the run-workers command.

**Comment by andyheyns93** [comment]
It would be handy if the command 'run-workers' can be configured with 'mocha-junit-report'. In my case even when each independent worker would create a xml file under an output folder. I can always aggregate these results.
