### ISSUE TITLE
How can I avoid within() block? 

### ISSUE THREAD

**Issue by sumiagar** [codeceptjs/CodeceptJS#1943]
want to verify the multiple items within same frame

Getting error :-   Can't start within block inside another within block

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

for(const id in table.rows)
  { 
    
    within({frame: "#SETTINGS"},() => {
        console.log("before checking:: Channel name and number "+table.rows[0].cells[0].value);
        I.seeTextEquals(table.rows[id].cells[0].value,'//*[@id="secondSubMenuList"]/div[id+2]/p[1]');
    });
  }

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by PeterNgTr** [comment]
why not just switching to frame before entering the loop?

**Comment by sumiagar** [comment]
> why not just switching to frame before entering the loop?

Thanks for reply but switchTo() also not working .

code::

  I.switchTo('#SETTINGS');
   for(const id in table.rows)
    { 
      console.log("before checking:: Channel name and number "+table.rows[0].cells[0].value);
      I.seeTextEquals(table.rows[id].cells[0].value,'//*[@id="secondSubMenuList"]/div[id+2]/p[1]');
    }

output:- 

-- FAILURES:

  1) I want to be able to interact with a settings menu
       Add multiple servcies into Fav list:
     Element "context element" was not found by text|CSS|XPath
