### ISSUE TITLE
Categories.json file applying for allure reporting

### ISSUE THREAD

**Issue by dsharapkou** [codeceptjs/CodeceptJS#1945]
Hi to all,

We are using stack `codeceptjs + webdriver + appium` on our project with `allure-js-commons` as a reporting library and I am trying to add custom categories for allure report.
[In this documentation](https://docs.qameta.io/allure/#_categories_2) said, that you should put `categories.json` to report folder before report generation.

The issue is that when I test it locally and put `categories.json` to `allure-results` directory and than generate report for this folder - it says that report already exists and you should apply `--clean` to this generation so it removes everything from folder including `categories.json` file.

When I'm trying to keep this file in `./output` directory for allure report, and than run generation of report it does not apply categories to report as well

Maybe you can advise how to handle this and where exactly we need to keep this `categories.json` file?

![66199544-8366f380-e6a7-11e9-926d-a680ab7e8f89](https://user-images.githubusercontent.com/35460045/66663001-8b4c0800-ec52-11e9-94fa-6a8ae4f5c0e9.png)
![66199549-8530b700-e6a7-11e9-82f4-83b2d5d3dd22](https://user-images.githubusercontent.com/35460045/66663002-8b4c0800-ec52-11e9-8c62-47713c2cec73.png)
![66199550-8661e400-e6a7-11e9-8853-c75b33cf6348](https://user-images.githubusercontent.com/35460045/66663004-8b4c0800-ec52-11e9-838c-1b7536b6ecd5.png)
![66199595-a2658580-e6a7-11e9-9d94-b337d33bc3fb](https://user-images.githubusercontent.com/35460045/66663005-8b4c0800-ec52-11e9-882c-7c5c7d95409f.png)

**Comment by PeterNgTr** [comment]
@dsharapkou this is not related to codeceptjs, I think!
