### ISSUE TITLE
 run-workers 2 --steps: error: unknown option `--steps'

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/CodeceptJS#1966]
#### What are you trying to achieve?

`npx codeceptjs run-workers 2 --steps`

#### What do you get instead?

```bash
error: unknown option `--steps'
```

See https://gitlab.com/codeceptjs/codeceptjs-bug-report-template/-/jobs/322854842

### Details

* CodeceptJS version: 2.3.3
* NodeJS Version: 12

**Comment by PeterNgTr** [comment]
that option is not supported, afaik.

**Comment by DavertMik** [comment]
It won't be, it will create a mess in the output
