### ISSUE TITLE
run-workers 2 --invert: error: unknown option `--invert'

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/CodeceptJS#1967]
#### What are you trying to achieve?

`npx codeceptjs run-workers 2 --grep @tag --invert`

#### What do you get instead?

```bash
error: unknown option `--invert'
```

See https://gitlab.com/codeceptjs/codeceptjs-bug-report-template/-/jobs/322861341

### Details

* CodeceptJS version: 2.3.3
* NodeJS Version: 12

**Comment by PeterNgTr** [comment]
no option https://github.com/Codeception/CodeceptJS/blob/master/bin/codecept.js#L123
