### ISSUE TITLE
WDIO@5.15.1 cause waitForVisible broken

### ISSUE THREAD

**Issue by sky172839465** [codeceptjs/CodeceptJS#1975]
#### What are you trying to achieve?

When I use waitForVisible will throw `Cannot convert undefined or null to object` error.

#### What do you get instead?

```bash
-- FAILURES:

  1) Search page
       page search not exist user:
     Cannot convert undefined or null to object
  
  Scenario Steps:
  
  - I.waitForVisible("input[name="userName"]") at Test.Scenario (src/__e2e__/src/Page/Search.js:38:5)
  - I.amOnPage("/test-app") at Test.Scenario (src/__e2e__/src/Page/Search.js:37:5)
  
  TypeError: Cannot convert undefined or null to object
      at /xxx/node_modules/@wdio/sync/build/runFnInFiberContext.js:14:19
      at Timer._fn (node_modules/webdriverio/build/utils/Timer.js:21:59)
      at Timer.tick (node_modules/webdriverio/build/utils/Timer.js:79:25)
      at Timer.start (node_modules/webdriverio/build/utils/Timer.js:41:12)
      at new Timer (node_modules/webdriverio/build/utils/Timer.js:28:10)
      at Browser._default (node_modules/webdriverio/build/commands/browser/waitUntil.js:26:15)
      at WebDriver.waitForVisible (node_modules/codeceptjs/lib/helper/WebDriver.js:1839:25)
      at Step.run (node_modules/codeceptjs/lib/step.js:45:47)
      at recorder.add (node_modules/codeceptjs/lib/actor.js:75:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### What I figured out is

It seems webdriverio this line cause waitForVisible broken, after delete the code, every thing work find, I have been downgrade wdio version to fix this issue.

```js
delete global.browser._NOT_FIBER;
```

### Details

* CodeceptJS version: 2.3.3
* NodeJS Version: 10.14.1
* Operating System: MacOS
* WebDriverIO
* Configuration file:

```js
exports.config = {
  name: 'test-app',
  tests: '../src/__e2e__/src/**/**.js',
  output: '../report',
  helpers: {
    WebDriver: {
      url: 'http://localhost:3000',
      browser: 'chrome',
      waitForTimeout: 300000
    }
  },
  include: {
    I: './actor/steps_file.js'
  },
  bootstrap: false,
  coloredLogs: true
}
```
* Repo(wdio version has been downgrade): https://github.com/sky172839465/test-app

**Comment by PeterNgTr** [comment]
I see you use the improper locator?
`I.waitForVisible("input[name="userName"]")` -> `I.waitForVisible('input[name="userName"]')` or `I.waitForVisible("input[name='userName']")`

**Comment by sky172839465** [comment]
Hi @PeterNgTr the locator you saw isn’t real, here has the code just like you say 😃
https://github.com/sky172839465/test-app/blob/master/src/__e2e__/pageObject.js#L3

**Comment by PeterNgTr** [comment]
@sky172839465 please recheck your issue with latest version.
