### ISSUE TITLE
Handle webdriverio version requirement dynamically

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/CodeceptJS#1980]
CodeceptJS depends on webdriverio which gets constantly updated, but https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/WebDriver.js#L453 says CodeceptJS requires i.e. webdriverio@5.2.2 which is not up to date anymore.

Would it be ok to just remove the exact webdriverio version here @DavertMik ?

**Comment by PeterNgTr** [comment]
@pablopaul I think the hard-coded value like this can be removed. I guess same thing happened with puppeteer.
