### ISSUE TITLE
Using Dynamic Configs Cuts WaitForTimeout by 1000 Each Time

### ISSUE THREAD

**Issue by vkoves** [codeceptjs/CodeceptJS#1995]
#### What are you trying to achieve?

We are looking to use dynamic configs to be able to test a second site within our larger suite, which has a different base URL but shares a lot of common UI elements.

#### What do you get instead?

Every time we use `.config` on a `Feature`, it causes the config to get revalidated and the `waitForTimeout` property's value appears to get divided by 1000 every time, making it so that each feature gets a smaller and smaller timeout, going from 10 sec to 0.01 sec, to 0.00001 sec, and so on.

Here's some sample output from one of our tests:

```bash
-- FAILURES:

1) Admin - FEATURE 1 NAME
  SCENARIO NAME
  element (.reveal-modal-bg) still visible after 0.01 sec

2) Admin - FEATURE 1 NAME
  SCENARIO NAME
  element (.reveal-modal-bg) still visible after 0.01 sec

3) Admin - FEATURE 2 NAME
  SCENARIO NAME
  element ({css: .fixed-width-message}) still not visible after 0.00001 sec

...

6) Admin - FEATURE 3 NAME
  SCENARIO NAME
  element ({css: .cdk-global-overlay-wrapper form}) still not visible after 1e-8 sec

...

9) Admin - FEATURE 4 NAME
  SCENARIO NAME
  element ({css: communities-list table > tbody > tr:nth-child(1)}) still not visible after 1.0000000000000001e-11 sec
```

Here is some sample source code of how we use `.config`. We confirmed that removing this fixed the issue:

```js
Feature('Admin - XXXXX').config({
    // Required for all admin tests
    url: process.env.CI ? CONSTANTS.frontendUrls.admin.internal : CONSTANTS.frontendUrls.admin.external
});
```

### Details

* CodeceptJS version: **Codecept v2.3.5**
* NodeJS Version: **Node v12.10.0**
* Operating System: **Ubuntu 18.04.03 LTS**
* Protractor || WebDriverIO || Nightmare version: **Webdriver 5.13.2**
* Configuration file: The only important bit is that under our helpers we specify:

```js
waitForTimeout: 10000
```

**Comment by mirao** [comment]
Just wanted to create the same issue and you saved my time.

Today I hit this problem when changing `desiredCapabilities.app` for [Appium](https://codecept.io/helpers/Appium#helper-configuration) helper (it extends WebDriver) in a `Scenario` dynamically.

As a workaround I'm getting the "Appium" part of original config, changing properties I need and returning the changed config:
```js
Scenario(...)
.config(() => { // Replace new APK by old one in this scenario
    const configOrig = require("codeceptjs").config.get().helpers.Appium;
    // Make a deep copy to avoid mutation of original config because this method is executed when test starts
    // Otherwise other tests are affected by changed config and old APK would be installed in all tests
    const configCustom = JSON.parse(JSON.stringify(configOrig));
    const desiredCapabilities = configCustom.desiredCapabilities;
    desiredCapabilities.app = desiredCapabilities.app.replace("new", "old");
    return configCustom;
});
```
Interesting thing is that e.g. `smartWait` (which is another WebDriver property) isn't cut by dynamic config and its original value is used in scenario correctly.

Used SW:
- CodeceptJS 2.3.3
- WebDriverIO 5.7.2
- Ubuntu 19.04

**Comment by mirao** [comment]
It's related to https://github.com/codeceptjs/CodeceptJS/blob/41936638272091400d4d239769300bd730e5b108/lib/helper/WebDriver.js#L465
The same issue is with Appium: https://github.com/codeceptjs/CodeceptJS/blob/41936638272091400d4d239769300bd730e5b108/lib/helper/Appium.js#L190

I guess that computing msec => sec should occur only when test suite starts. But now it's happening from some reason also when particular scenario with dynamic config starts.

**Comment by mirao** [comment]
```js
oldConfig.waitForTimeout *= 1000;
````
after https://github.com/codeceptjs/CodeceptJS/blob/41936638272091400d4d239769300bd730e5b108/lib/listener/config.js#L18
seems to be a solution.

I'll create PR.

**Comment by mirao** [comment]
It seems to be fixed in https://github.com/codeceptjs/CodeceptJS/pull/3478
