### ISSUE TITLE
Popup gets always accepted and move to next page

### ISSUE THREAD

**Issue by bhautikbpatel** [codeceptjs/CodeceptJS#1996]
I click "Home", This code will generate popup on a webpage and I need to grab text from the popup and accept popup so i write code as below.
I.click("Home");
let x = await I.grabPopupText();
console.log("x: " + x) //Display null text as it already move to home page.
await I.acceptPopup();

Here, it moves to the home page and ignores popup so I am not able to perform any action on popup.

Log: Popup already exists and was not closed. Popups must always be closed by calling either I.acceptPopup() or I.cancelPopup()

**Comment by PeterNgTr** [comment]
@bhautikbpatel please provide more info like what helper, browser, etc.

**Comment by bhautikbpatel** [comment]
"dependencies": {
    "allure-commandline": "^2.13.0",
    "chai": "^4.2.0",
    "codeceptjs": "^2.3.3",
    "codeceptjs-assert": "0.0.4",
    "config": "^3.2.2",
    "mocha": "^6.2.1",
    "mocha-allure-reporter": "^1.4.0",
    "mocha-junit-reporter": "^1.23.1",
    "mochawesome": "^4.1.0",
    "npm": "^6.12.0",
    "pdf-parse": "^1.1.1",
    "puppeteer": "^2.0.0",
    "rimraf": "^3.0.0"
  }

 Puppeteer: {
      show: true,
      restart: false,
      keepBrowserState: true,
      uniqueScreenshotNames: true,
      getPageTimeout: 60000,
      waitForNavigation: ['domcontentloaded', 'networkidle0'],
      waitForTimeout: 20000,
      windowSize: '1280x960',
      waitForAction: 500,
      chrome: {
        args: ['--start-maximized' ]
      }
    },
