### ISSUE TITLE
Process doesnt end when running in parallel

### ISSUE THREAD

**Issue by willhowlett** [codeceptjs/CodeceptJS#1997]
#### What are you trying to achieve?

Running multiple browsers with testcafe using `codeceptjs run-multiple --all`

#### What do you get instead?

The process seems to hang and `teardownAll` never fires

![Screen Shot 2019-10-31 at 13 37 06](https://user-images.githubusercontent.com/2945977/67951881-4594b680-fbe4-11e9-80c5-230b707f8c49.png)

### Details

* CodeceptJS version: 2.3.5
* NodeJS Version: 10.13.0
* Operating System: Macos Sierra
* Protractor || WebDriverIO || Nightmare version (if related): - testcafe 1.6.0
* Configuration file:

```js
exports.config = {
  output: './e2e_tests/output',
  helpers: {
    TestCafe: {
      url: 'https://dev-server.com',
      browser: 'browserstack:chrome@78.0:OS X Mojave',
      show: true,
    },
    ResembleHelper: {
      require: 'codeceptjs-resemblehelper',
      screenshotFolder: './e2e_tests/tests/output/',
      baseFolder: './e2e_tests/tests/screenshots/base/',
      diffFolder: './e2e_tests/tests/screenshots/diff/',
    },
  },
  include: {
    I: './e2e_tests/steps_file.js',
  },
  mocha: { bail: true },
  bootstrap: null,
  teardown: null,
  hooks: [
    // './e2e_tests/hooks/event.all.after.js',
  ],
  gherkin: {
    features: './e2e_tests/features/*.feature',
    steps: ['./e2e_tests/step_definitions/steps.js'],
  },
  plugins: {
    screenshotOnFail: {
      enabled: true,
    },
  },
  tests: './e2e_tests/tests/**/*.test.js',
  name: 'polaris-siteapp',
  multiple: {
    basic: {
      grep: '(?=.*)^(?!.*@visual-test)',
      // List available browserstack browsers
      // node ./node_modules/testcafe/bin/testcafe.js -b browserstack
      browsers: [
        'chrome',
        'safari',
        // 'browserstack:chrome@78.0:OS X Mojave',
        // 'browserstack:edge@18.0:Windows 10',
        // 'browserstack:ie@11.0:Windows 10',
      ],
    },
  },
  teardownAll: (done) => { console.log('DUN'); done(); },
};

```

**Comment by Vla8islav** [comment]
I second that one. It's also can be reproduced when you're trying to use chunks to run tests in parallel.
This can be useful when you want to use the custom reporter which is not supported by run-workers.

Steps to reproduce: 

`
git clone git@github.com:Vla8islav/codeceptjs-multireporter-test.git
cd codeceptjs-multireporter-test
docker build  -t codecept-chrome:latest . &&  docker run codecept-chrome:latest
`
main process
`CMD npx codeceptjs run-multiple parallel`
just hangs after executing tests.
It also can be reproduced without a docker.
`  "dependencies": {
    "codeceptjs": "^2.3.5",
    "testcafe": "^1.6.1"
  }`
I suggest removing the relevan example
`	multiple: {
	  parallel: {
	    // Splits tests into 2 chunks
	    chunks: 4
	  }
	},
`
from the documentation untill an issue is fixed.

**Comment by gkushang** [comment]
I am also seeing issues when `feature` file has more than one scenario defined, it does not run the Second Scenario and process hangs or throws below error,

```
  2) Search Github @search
       "after each" hook: codeceptjs.after for "Fred should see the highlighted results for the searched repository @search_results":
     connect ECONNREFUSED 127.0.0.1:4444
  rror: connect ECONNREFUSED 127.0.0.1:4444
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
```

**Comment by yaoxiao1993** [comment]
I have this problem too, any update?

**Comment by armands226** [comment]
Hi,
Is there any updates?
I have similar issue. I have visual tests. I am using Resemble.
Command to execute:
```
npx codeceptjs run-multiple parallel --reporter  mocha-multi
```
All tests are executed , but proces hangs after that and teardownAll is not executed, I have to kill it myself manually and then execute teardownAll task manually.

My config
```
exports.config = {
  tests: './tests/*_test.js',
  output: './report',
  bootstrapAll: './bootstrapAll.js',
  teardownAll:'./teardownAll.js',
  multiple: {
    parallel: {
      chunks: 4
    }
  },
  mocha: {
    "reporterOptions": {
        "codeceptjs-cli-reporter": {
            "stdout": "-",
            "options": {
                "verbose": false,
                "steps": true
            }
        },
        "mocha-junit-reporter": {
            "stdout": "./report/jconsole.log",
            "options": {
                "mochaFile": "./report/result.xml"
            }
        },
        "mochawesome": {
          "stdout": "./report/mconsole.log",
          "options": {
            "reportDir": "./report",
            "reportFilename": "report"
         },
         "attachments": true 
        }
    }
  },
  helpers: {
     Puppeteer: {
       url: 'http://xxxxxxxx:7777',
       show: false,
       windowSize: "1920x1080",
       waitForNavigation: [ "domcontentloaded", "networkidle0" ],
       waitForAction:1000,
       waitForTimeout:30000
     },
    HooksHelper: {
      require: './helpers/hooksHelper.js'
    },
	ResembleHelper : {
       require: "codeceptjs-resemblehelper",
       screenshotFolder : "./report/",
       baseFolder: "./tests/screenshots/base/",
       diffFolder: "./report/diff/"
     },
     Mochawesome: {
      uniqueScreenshotNames: true
  }
},
}
```

**Comment by PeterNgTr** [comment]
Have you tried with latest version 2.6.0?

**Comment by armands226** [comment]
Hi thanks, I will try and let you know. Currently I am using 2.5.0.

**Comment by armands226** [comment]
Hi, updated to 2.6.0. Still the same process doesn't end.

**Comment by Anikethana** [comment]
any luck with this issue ?

**Comment by armands226** [comment]
> any luck with this issue ?

Hi, partly.
with these settings for puppeteer is more stable. Especialy restart : false
     Puppeteer: {
       url: 'xxx.xxx',
       show: false,
       windowSize: "1920x1080",
       waitForNavigation: [ "domcontentloaded", "networkidle0" ],
       waitForAction:1000,
       waitForTimeout:30000,
       restart:false,
       chrome: { args: ['--enable-font-antialiasing', '--no-sandbox', '--disable-setuid-sandbox', '--font-render-hinting=none'], ignoreDefaultArgs: ["--hide-scrollbars"]}
     },

**Comment by DavertMik** [comment]
please switch to workers

**Comment by jayudey-wf** [comment]
I'm seeing this as well with `run-workers`
