### ISSUE TITLE
Problem with page object injection: inject is not defined

### ISSUE THREAD

**Issue by sinelshchikovigor** [codeceptjs/CodeceptJS#2012]
#### What are you trying to achieve?
I'm trying to inject page object into script with inject() function.

#### What do you get instead?

```bash
inject is not defined

ReferenceError: 
    at Object.<anonymous> (/Users/igorsinelsikov/Documents/dpm-platform/packages/portal/src/e2e/ui-examples.e2e.spec.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)

```

> Provide test source code if related

```js
// page object
module.exports = function() {
  return actor({
    login: function(email, password) {
      this.waitForElement('#username', 10);
      this.fillField('#username', email);
      this.fillField('#password', password);
      this.click('Login');
    },
  });
};

// spec
const {loginPage} = inject();

Feature('Test');

Scenario('Test UI examples', (I) => {
  I.amOnPage('/');

  loginPage.login('si', 'si');
});

```

### Details

* CodeceptJS version: 2.3.5
* NodeJS Version: 10.13.0
* Operating System: macOS Mojave 10.14.6
* Puppeteer: 2.0.0
* Configuration file:

```js
exports.config = {
  tests: './packages/portal/**/*.e2e.spec.js',
  output: './temp/e2e',
  helpers: {
    Puppeteer: {
      url: 'https://localhost',
      show: true,
      chrome: {
        args: ['--no-sandbox', '--window-size=1680,960'],
        ignoreHTTPSErrors: true,
      },
      windowSize: '1680x820',
    },
  },
  include: {
    loginPage: './e2e/pages/login-page.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'portal',
};

```

Could you please help me with the issue? Am I doing something wrong?

UPDATE:

If I inject it like this, everything is working fine:

```js
Feature('Test');

Scenario('Test UI examples', (I, loginPage) => {
  I.amOnPage('/');

  loginPage.login('si', 'si');
});
```

**Comment by samaysimantbarik** [comment]
My code with inject worked with Node 12 but when I am trying to execute from another machine having node 10, it gives the same error "Could not include object loginPage from module 'C:\Projects\****\****\e2e\pages\Login.js'
inject is not defined" . Is it an issue with Node version.

Alternate approach is to pass the page object names to each function as a parameter. But that's what I would not prefer to do.

Kindly suggest

**Comment by sinelshchikovigor** [comment]
@samaysimantbarik, thanks a lot for your help!

Maybe this also helps: I'm using Node v10 with Puppeteer and it's not working. I tried to switch to WebDriver and it started to work with Node v10.
