### ISSUE TITLE
Drop run-multiple in favor of run-workers

### ISSUE THREAD

**Issue by DavertMik** [codeceptjs/CodeceptJS#2015]

**Comment by PeterNgTr** [comment]
Maybe we should think of:
- migrate from `run-multiple` to `run-workers`
- remove related `run-multiple` docs

**Comment by GSasu** [comment]
Please don't remove run-multiple yet. Run-workers still has issues with data-driven tests running in parallel. Or if you want to remove it from the normal command chain, fine but at least expose the methods for a custom runner. It wouldn't hurt to expose both run-multiple and run-workers to be available for custom runners.

**Comment by gkushang** [comment]
@DavertMik 

I will agree with @GSasu !  Please do not remove the `run-multiple` yet. `run-workers` does not run the BDD Gherkin Feature files / Scenarios. It has lot of issues.

I also agree on keeping both features if new `run-workers` is available in V3 through https://github.com/Codeception/CodeceptJS/pull/2115

Thanks!
Kushang

**Comment by pablopaul** [comment]
I would deprecate `run-multiple` in v3 and drop it in v4.
