### ISSUE TITLE
Test incorrectly logs the total test time (Codecept + Testcafe)

### ISSUE THREAD

**Issue by Nofit** [codeceptjs/CodeceptJS#2032]
#### What are you trying to achieve?
Having the correct total test time logged. 

#### What do you get instead?
An obviously incorrect test time. I executed a really short starter test and it logged 14 seconds, while it undoubtedly took only around 2 seconds. 
![image](https://user-images.githubusercontent.com/33626766/68968922-feade000-07e3-11ea-992b-62ee2c4292eb.png)

You can see the incorrect total time back in Allure. 
The weird thing is that the step times are correct. This is a really important feature for me, I need the correct total test time, otherwise I can't make any legit test reports.

> Provide console output if related. Use `--verbose` mode for more details.

TodoMVC --
 Running tests in:
 - Chrome 78.0.3904 / Windows 10.0.0
  √ create todo item in 2509ms

  OK  | 1 passed   // 14s

> Provide test source code if related

Feature('TodoMVC');

Scenario('create todo item', (I) => {
  I.amOnPage('http://todomvc.com/examples/angularjs/#/');
  I.fillField('.new-todo', 'spelen')
  I.pressKey('Enter');
  I.seeNumberOfVisibleElements('.todo-list li', 1);
  I.see('1 item left', '.todo-count');
});

### Details

* CodeceptJS version:  2.3.5
* NodeJS Version: 10.16.3
* Operating System: Windows 10
* Testcafe 1.6.0
* Configuration file:

exports.config = {
  output: './output',
  helpers: {
    TestCafe: {
      url: 'http://todomvc.com/examples/angularjs/#/',
      browser: 'chrome',
      show: true
    }
  },
  include: {
    I: './steps_file.js'
  },
  mocha: {},
  bootstrap: null,
  teardown: null,
  hooks: [],
  gherkin: {
    features: './test/features/*.feature',
    steps: ['./test/step_definitions/steps.js']
  },
  plugins: {
    screenshotOnFail: {
      enabled: true
    },
    allure: {
    }
  },
  tests: './*_test.js',
  name: 'TestCoSuite'
}

**Comment by PeterNgTr** [comment]
seems like not on TestCafe helper

<img width="615" alt="Screenshot 2019-11-18 at 10 37 46" src="https://user-images.githubusercontent.com/7845001/69041311-959ab800-09ef-11ea-89cf-186b9e6d23cd.png">
