### ISSUE TITLE
Login with certificate with puppeteer

### ISSUE THREAD

**Issue by CB0rghi** [codeceptjs/CodeceptJS#2097]
#### What are you trying to achieve?
Choose a certificate from certificate popup that pops on chromium
#### What do you get instead?
I.pressKey('Enter') or Tab doesnt work

* CodeceptJS version: 2.3.6
* Operating System: Windows
* puppeteer version: 2.0.0
* Configuration file: 
exports.config = {
  tests: "./tests/*.js",
  output: "./outputs",
  helpers: {
    Puppeteer: {
      browser:"firefox",
      restart: false,
      show: true,
      url: "http://localhost"
    }
  },
  include: {
    I: "./steps_file.js"
  },
  bootstrap: null,
  mocha: {},
  name: "Crawler"
};

**Comment by CAIOHOBORGHI** [comment]
Tried with chomium instead firefox too but that also didn't work

**Comment by DavertMik** [comment]
i don't think that certificate should work like that
maybe you need to Puppeteer API for that
