### ISSUE TITLE
Access tests results summary

### ISSUE THREAD

**Issue by raquelgs** [codeceptjs/CodeceptJS#2105]
#### What are you trying to achieve?
Access test results summary. 
I'm using `mochawesome` to generate the test report but I only want to save the report if there are failing tests. So I'm creating a hook for that.
Is there any event I can suscribe to for checking the results of the execution?  I've was thinkin `event.all.result` could have that information, but I was not able to find it.

### Details

* CodeceptJS version: 2.3.0
* NodeJS Version: 10
* Operating System: linux
* webdriverio

**Comment by PeterNgTr** [comment]
https://codecept.io/hooks/#api

Have you tried to collect all the failed tests with `event.test.failed(test, error)` then `event.all.after` to write the test report?

**Comment by raquelgs** [comment]
Hello @PeterNgTr, yes that's what I'm using but I was wondering if there was a simpler way

**Comment by DavertMik** [comment]
you can listen to all tests failed events, collect tests and then iterate over them
also all artifacts are available under `test.artifacts` option
