### ISSUE TITLE
Public API for run-workers

### ISSUE THREAD

**Issue by DavertMik** [codeceptjs/CodeceptJS#2107]
Currently, run-workers is available only via command file: https://github.com/Codeception/CodeceptJS/blob/master/lib/command/run-workers.js

There must be a way to use them via a programmable interface:

Something like this:

```js
const workers = require('lib/workers')'
await workers.spawn(2).run();
```

This API should be more flexible than command line API so workers could be instantiated with custom configs each so we could apply a custom config to each worker:

```js
const workers = require('lib/workers');

// split all tests by 2 groups
const groupOfTests = workers.createGroupsOfTests(2);

// thre should be a way to spawn groups by suites
const groupOfTests = workers.createGroupsOfSuites(2);

// execute each group with different config

// simple run
workers.spawn(2).run();

// execute bootstrapAll hook
workers.bootstrapAll();

// complex
const configs = [
  { helpers: { WebDriver: { browser: 'firefox' } } },
  { helpers: { WebDriver: { browser: 'chrome' } } },
]

for (group of groupOfTests) {
  for (config of configs) {
    let worker = workers.spawn();
    worker.addTests(group);
    worker.setConfig(config);
  }
}

workers.on(event.test.failed, () => {
  // add custom event listener, as it is done here
  // https://github.com/Codeception/CodeceptJS/blob/master/lib/command/run-workers.js#L84

});


workers.on(event.test.passed, () => {
  // add custom event listener, as it is done here
  // https://github.com/Codeception/CodeceptJS/blob/master/lib/command/run-workers.js#L84

});

workers.run();
```

This is an initial draft for API so this can be improved and changed on refactoring. Any ideas appreciated.

### Shared memory

There also should be API for shared memory via workers.

* API to pass data from main process into worker `worker.shareData({})`;
* API to interconnect between workers so each worker could share data with other workers
* API to pass data from a worker into a main thread. Currently, this is done via events.

**Comment by koushikmohan1996** [comment]
@DavertMik I have some ideas.

For simple operation we can have something like this: 
```js
const Workers = require('lib/workers')';

//This will create 2 groups of tests. If the second param is passed as true, groups will be split as suites 

const workers = new Workers(2, false);
workers.run();


// Override config for all the workers
workers.overrideConfig({
  helpers: {
    Puppeteer: {
      url: 'http://localhost',
      show: true
    }
  }
});
```
Rest can be added as above.

Also instead of using EventEmitter can we use promise? Something like this : 
```js
workers.run().then((stats) => {
console.log(stats.passes);
}).catch((errObj) => {
console.log('Stats :', errObj.stats.passes);
console.log('Failed :', errObj.stats.failures);

 for (const failedTest of errObj.failedTests) {
    console.log('Title : ', failedTest.title);
    console.log('Message : ', failedTest.err.message)
 }
});
```

**Comment by koushikmohan1996** [comment]
@DavertMik I have some doubts in shared memory.

In Node we can share data using `postMessage` API. We should decide on the data type according to our needs.
If data is going to be a simple JSON and not going to modified after transferring, we can directly send it using `postMessage`. If we want a have shared memory we can use SharedBuffer. 

My doubt here is how this data is going to be used inside the worker?  
[Refer here](https://nodejs.org/api/worker_threads.html#worker_threads_port_postmessage_value_transferlist) to know about shared buffer
