### ISSUE TITLE
Cannot turn off auto-retry plugin via config file

### ISSUE THREAD

**Issue by grzegorzprzybylo** [codeceptjs/CodeceptJS#2175]
#### What are you trying to achieve?
disable auto-retry plugin: https://codecept.io/basics/#auto-retry

I see it is set globally since 2.4, I am using: `2.4.3`

And this is part of my config:

```
 plugins: {
    ...,
    retryFailedStep: {
      enabled: false
    },
  }
```

#### What do you get instead?

verbose log:
```
    [1] Retrying... Attempt #2
    [1] Retrying... Attempt #3
    [1] Retrying... Attempt #4
    [1] Retrying... Attempt #5
    [1] Retrying... Attempt #6
    [1] Error | Error: Text "testtesttest" was not found on page after 1 sec
waiting for function failed: timeout 1000ms exceeded

```

what I have in test:
```
await I.waitForText('testtesttest', 1);
```

@DavertMik is there a possibility to turn off auto-retry plugin globally for a project?

**Comment by grzegorzprzybylo** [comment]
looks like that option: https://codecept.io/plugins/#retryfailedstep is not working either.

**Comment by grzegorzprzybylo** [comment]
@DavertMik @Vorobeyko 
looks like this one: https://github.com/Codeception/CodeceptJS/issues/1891 is still valid for me using `2.4.3` and I see issue above because of this I believe

**Comment by grzegorzprzybylo** [comment]
I see that when I modify `retries` in some step in my tests to e.g. `1` - then it tries only `1` time execute failed next step

**Comment by Vorobeyko** [comment]
@grzegorzprzybylo Hi! Thank you for issue!
I check this moment today)

**Comment by DavertMik** [comment]
This looks like a major issue but I could not reproduce it.

Here is my output log:

```
      I fill field "user[password]", "user@user.com"
      › [Browser:Error] Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
    Emitted | step.passed (I fill field "user[password]", "user@user.com")
    Emitted | step.finish (I fill field "user[password]", "user@user.com")
    Emitted | step.start (I fill field "q", "aaa")
      I fill field "q", "aaa"
    [4] <within> Error | Error: Field "q" was not found by text|CSS|XPath
    Emitted | step.failed (I fill field "q", "aaa")
    Emitted | step.finish (I fill field "q", "aaa")
    [4] <within> Error | Error: Field "q" was not found by text|CSS|XPath
    Emitted | step.failed (I click "button")
    Emitted | step.finish (I click "button")
    [4] <within> Error | Error: Field "q" was not found by text|CSS|XPath
    [4] <within> Error | Error: Field "q" was not found by text|CSS|XPath
    Emitted | step.failed (I see "There were problems creating your account.")
    Emitted | step.finish (I see "There were problems creating your account.")
    [4] <within> Error | Error: Field "q" was not found by text|CSS|XPath
    Emitted | step.failed (I click "Explore")
    Emitted | step.finish (I click "Explore")
    [4] <within> Error | Error: Field "q" was not found by text|CSS|XPath
    Emitted | step.failed (I see in current url "/explore")
    Emitted | step.finish (I see in current url "/explore")
    [4] <within> Error | Error: Field "q" was not found by text|CSS|XPath
    [4] <within> Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [4] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, saving screenshot
 › Screenshot is saving to /home/davert/projects/codeceptjs/examples/output/register.failed.png
  ✖ FAILED in 1644ms


```

Here is my config:

```
    retryFailedStep: {
      enabled: false,
    },
```

Please provide an example which we could reproduce.
Or share more information on your setup, maybe the issue is in your config...

**Comment by grzegorzprzybylo** [comment]
I can check it with some fresh install, once I have more info I will paste it here, thanks!

**Comment by grzegorzprzybylo** [comment]
@DavertMik @Vorobeyko 

looks like when I am using custom helper method it occurs, please see repo with example https://github.com/grzegorzprzybylo/ccjs-test

**Comment by armandsz22** [comment]
Hi, I am using resemble helper. Same issue.
![image](https://user-images.githubusercontent.com/93975599/144766201-bdfa6844-dc20-4751-ba12-dcb1ebc413bf.png)
![image](https://user-images.githubusercontent.com/93975599/144766224-c9372668-6b76-4c19-8ddb-acc8bb1c00fe.png)
