### ISSUE TITLE
codeceptjs cannot find ANY of the elements on a page, waitForNavigation() never finishes 

### ISSUE THREAD

**Issue by amustafa15** [codeceptjs/CodeceptJS#2190]
Steps to reproduce

So I cannot load or find a single element on a page. I use I.amOnPage() to navigate to the correct page. but when the code gets to I.waitForNavigation it never resolves. it just pauses there forever. I tried everything suggested here but nothing changes that. so I tried I.waitForElement('.body') and nothing. according to puppeteer/codeceptjs there is no body element on this page. it can find the iframe alright but it cannot find the body or any other element by text, css or xpath. it seems the only stuff it can find is the navigation menu.

Tell us about your environment:

Puppeteer version: whatever the latest version is
Platform / OS version: Mac OS whatever the most recent is
URLs (if applicable):
Node.js version: most recent
What steps will reproduce the problem?

Please include code that reproduces the issue.

I.amOnPage('https://artemis-test2.atlassian.net/wiki/plugins/servlet/ac/com.nurago.confluence.plugins.treecopy/copy-page-tree-confluence?page.id=25821196&space.key=TEST1');

I.waitForNavigation();
I.wait(4);
I.waitForElement('.ap-iframe');
I.waitForElement('.body');
What is the expected result?
the expected result is that after I.waitForNavigation() the code then interacts within the body element. as it stands now it says there is no body element on the entire page. it is impossible to interact with any of the elements on the page.

**Comment by elukoyanov** [comment]
WaitForNavigation wait, until you load something.
But you already loaded page on `amOnPage` action.

You either do not need to explicitly wait `waitForNavigation` and use network navigation timeout configuration, or run with `amOnPage` in same Promise.all:
```js
await Promise.all([
  I.waitForNavigation(),
  I.amOnPage('....')
])
```

**Comment by amustafa15** [comment]
thank you for the response but that does not solve the main issue which is that codeceptjs cannot find the majority of the html elements on a page after it loads. your answer helped solve the other issue but the main issue persists. how do I get codeceptjs to see **ALL** the elements on a page after it loads? cause as it stands now the only elements that can be interacted with are in the navigation panel. have others had this issue before? even if I update my code to include what you wrote the same thing happens.

**Comment by DavertMik** [comment]
There can be 100500 reasons why it doesn't see elements.
I think the most obvious can be that those elements may be rendered inside iframe or shadow dom
Please check this
