### ISSUE TITLE
pressKey doesn't work with Shift inside text field

### ISSUE THREAD

**Issue by ghost** [codeceptjs/CodeceptJS#2201]
#### What are you trying to achieve?
Trying to enter "Shift + a" inside text field to make it "A",
#### What do you get instead?
 but it shows only "a". 
> Provide console output if related. Use `--verbose` mode for more details.

```bash
[ 'Shift', 'a' ]
[ '' ]
```

> Provide test source code if related

```js
Feature('search.feature');

Scenario('test something', (I) => {
    I.amOnPage('/');
    I.pressKey(['Shift', 'a']);
    pause();
});
```

### Details

* CodeceptJS version: 2.4.3
* NodeJS Version: 11.5.0
* Operating System: Windows
* puppeteer || webdriverio || protractor || testcafe version (if related) webdriverio
* Configuration file:

```js
exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    WebDriver: {
      url: 'http://www.google.com',
      browser: 'chrome'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'Webdriver',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    },
    wdio: {
      enabled: true,
      services: ['selenium-standalone']
    }
  }
}
```

**Comment by vatsan34** [comment]
Going through the code, in lib/helper/Webdriver.js, pressKey(key) calls getNormalizedKey.call(this, key) twice in case of using an Array, once in that method and again in pressKeyDown/Up method. Are we trying to get normalized key of Shift twice here? Is that causing this issue?

**Comment by DavertMik** [comment]
Thanks for investigating this
If you know how to fix that please send PR!

**Comment by vatsan34** [comment]
Also, Ctrl+W (in windows) does not close a window, that does not have focus on text field.

**Comment by fauwazahmad** [comment]
I am facing same issue with 
**I.pressKey(['Shift', 'F10']);**
