### ISSUE TITLE
Support &nbsp symbol in I.see method

### ISSUE THREAD

**Issue by MissiaL** [codeceptjs/CodeceptJS#2206]
#### What are you trying to achieve?
When I check the text, I don’t want to figure out what characters it contains. I see the text and I want to check it. Now the method `see` does not support text verification if it contains a `&nbsp` character.
```
<div class="dJHe_" style="color: rgb(255, 255, 255);">My&nbsp;Text!</div>
```
Now `I.see("My Text!")` will not work!

#### What do you get instead?
I propose to maintain strict compliance with the text and not strict. Here is an example of how I see it:
```
I.see("My text", strict=false)
```
Or I propose to make this behavior by default for all checks

**Comment by MathieuNo** [comment]
Hi, I don't see answers for this bug but it's still relevant. Symbols in semantic locators can't be detected.
&nbsp; is important and still use in websites.
