### ISSUE TITLE
Video recording plugin.

### ISSUE THREAD

**Issue by Vorobeyko** [codeceptjs/CodeceptJS#2212]
To record video in Puppeteer or WebDriver using  Selenoid

**Comment by pablopaul** [comment]
@DavertMik are we planning to bring Playwright support as well? See https://github.com/qawolf/playwright-video

**Comment by akapitoha** [comment]
+1 to Playwright video recording support

**Comment by aesyondu** [comment]
Anyone found a workaround at the moment?

Playwright docs says:

> When browser context is created with the videosPath option, each page has a video object associated with it.

I'm trying to figure out how I can inject the `videosPath` to the browser context.

**Comment by kaustubhshete** [comment]
looking at so many open and answered issues I am seriously rethinking of switching away from codecept
