### ISSUE TITLE
Test suite fails with "Object of type passedObject is not defined in container" when use After(pause)

### ISSUE THREAD

**Issue by karunandrii** [codeceptjs/CodeceptJS#2235]
#### What are you trying to achieve?
Start an interactive console after the last step.
#### What do you get instead?
Test fails with an error: Object of type passedObject is not defined in container.
It works with @2.3.6 version, though. Support object, in that case, is "I". So, a workaround to work it out is to use.
```
After(I => { pause()});
```
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# CodeceptJS v2.5.0
Helpers: REST, Puppeteer
Plugins: screenshotOnFail

@Test --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  test
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.comment (Scenario)
   Scenario
    Emitted | test.passed ([object Object])
    Emitted | test.finish ([object Object])
  √ OK in 15ms

    Emitted | hook.start ([object Object])
    [1] Error | Error: Object of type passedObject is not defined in container
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.after ([object Object])
    [1] <teardown> Stopping recording promises
    Emitted | hook.failed ([object Object])
  × FAILED in 622ms

    [2] Starting recording promises
    Emitted | suite.after ([object Object])
-- FAILURES:

  1) @Test
       "after each" hook: After for "test":
     Object of type passedObject is not defined in container
  rror: Object of type passedObject is not defined in container
      at getInjectedArguments (node_modules\codeceptjs\lib\scenario.js:198:13)
      at Context.<anonymous> (node_modules\codeceptjs\lib\scenario.js:140:22)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)


  FAIL  | 1 passed, 1 failed   // 1s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

> Provide test source code if related

```js
Feature('@Test');

After(pause);

Scenario('test', I => {
    I.say('Scenario');
});
```

### Details

* CodeceptJS version: 2.5.0
* NodeJS Version: 12.14.1
* Operating System: Win 10
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# Default for puppeteer.
```

**Comment by herrouhajar** [comment]
@karunandrii  did you found any solution to this issue, cuz im facing the same :
Im using playwright and when i run **vue-cli-service test:e2e**
i got this error :  Error: Object of type {I is not defined in container
      at getInjectedArguments (node_modules\vue-cli-plugin-codeceptjs-puppeteer\node_modules\codeceptjs\lib\scenario.js:198:13)
      at Context.test.fn (node_modules\vue-cli-plugin-codeceptjs-puppeteer\node_modules\codeceptjs\lib\scenario.js:56:26)

  Run with --verbose flag to see NodeJS stacktrace
