### ISSUE TITLE
[PlayWright] Two chromium browser instances getting launched Instead of One

### ISSUE THREAD

**Issue by MaxTester1** [codeceptjs/CodeceptJS#2239]
#### What are you trying to achieve?
Trying to Automate Web using Playwright helper on Chromium, expected to get one browser launched and test executed

#### What do you get instead?
Two Browser instances are getting launched 1 as Incognito mode and other in Normal Mode

> Provide console output if related. Use `--verbose` mode for more details.
CodeceptJS v2.5.0
Using test root "C:\Automation\Demo_Playwright"
Helpers: Playwright
Plugins: screenshotOnFail, retryFailedStep, allure

Test Google Page --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
 » [Session] Starting singleton browser session
  Search Page @Google
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I am on page "https://www.google.com/")
    Emitted | step.after (I am on page "https://www.google.com/")
    Emitted | step.before (I wait 10)
    Emitted | step.after (I wait 10)
```bash
# paste output here
```

> Provide test source code if related
Feature('Test Google Page');

Scenario('Search Page @Google', (I)=>{
    I.amOnPage('https://www.google.com/')
    I.wait (10)
    I.fillField('q','Google')
    I.click('Google Search')
    I.say('Done!')
});
```js
// paste test
```

### Details

* CodeceptJS version:2.5.0
* NodeJS Version:12.16.0
* Operating System: Windows 10
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# const { setHeadlessWhen,setWindowSize } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable

// HEADLESS=true npx codecept run

setHeadlessWhen(process.env.HEADLESS);

exports.config = {

  tests: './tests/*_test.js',

  timeout: 10000,

  output: './output',

  helpers: {

    Playwright: {

      url: '',

      show: true,

      browser: 'chromium',

      windowSize: '1900x1200',

      waitForNavigation: [ "domcontentloaded", "networkidle0" ]

    }

  },

  include: {

    I: './steps_file.js'

  },

  bootstrap: null,

  mocha: {},    

  name: 'Demo_Playwright',

  plugins: {

    retryFailedStep: {

      enabled: true

    },

    screenshotOnFail: {

      enabled: true

    },

    allure: {

      enabled: true

    }

  }

}
```

**Comment by DavertMik** [comment]
I faced similar issue duting development. 
For me it was the problem with some Playwright versions. I hope this will be fixed on their end.

**Comment by MaxTester1** [comment]
Thanks for confirming the issue, will look forward for upcoming releases to get this resolved either by Playwright or by our community.

**Comment by Elverslane** [comment]
@MaxTester1 just wait for update
https://github.com/microsoft/playwright/issues/981

**Comment by PeterNgTr** [comment]
so seemed like it's playwright's part
.

**Comment by DavertMik** [comment]
Yeah, let's wait for them to fix this

**Comment by MaxTester1** [comment]
> @MaxTester1 just wait for update
> [microsoft/playwright#981](https://github.com/microsoft/playwright/issues/981)

Thanks @Elverslane for the followup and update
