### ISSUE TITLE
I.grabTextFrom() behaves differently in Chromium and Webkit with Playwright

### ISSUE THREAD

**Issue by abramenal** [codeceptjs/CodeceptJS#2243]
### I.grabTextFrom() behaves differently in Chromium and Webkit with Playwright

Having this markup:
```html
<div class="ant-breadcrumb">
  <span>
    <span class="ant-breadcrumb-link">
      <a href="/activations">
        <span>Activations</span>
      </a>
    </span>
    <span class="ant-breadcrumb-separator">/</span>
  </span>

  <span>
    <span class="ant-breadcrumb-link">
      <span>
        <span>New Activation</span>
      </span>
    </span>

    <span class="ant-breadcrumb-separator">/</span>
  </span>
</div>
```
#### Actual result

Executing `I.grabTextFrom($0)` on the root element returns:

- `"Activations / New Activation"` in Chromium
- `"Activations / New Activation\n"` in Webkit

#### Expected result

Executing `I.grabTextFrom($0)` on the root element should return same string without special characters despite of the platform used.

### Details

I observed that it behaves similar to native method: `$0.innerText` which gives same output, but keeping in mind CodeceptJS cross-platform support I suppose this case should be baked in `grabTextFrom` method.

* CodeceptJS version: `^2.5.0`
* Playwright version: `^0.11.1`

**Comment by PeterNgTr** [comment]
@abramenal have you tried `I.grabTextFrom('div')`? Did it give the same thing that you are encountering ?

**Comment by abramenal** [comment]
@PeterNgTr for sure it is the same, the problem is not in $0 aliasing
