### ISSUE TITLE
init: traling commas in config

### ISSUE THREAD

**Issue by tomByrer** [codeceptjs/CodeceptJS#2254]
#### What are you trying to achieve?

Less `git diff` noise, more lazy copy & paste :)

`codeceptjs init` is a great project generator.  Unfortunately additional configuration requires editing 2 lines, one of which could be avoided.
Currently:
```js
...
  helpers: {
    Playwright: {
      url: 'https://www.facebook.com',
      show: true,
      browser: 'chromium'
    }
  },
```
Then I want to add a navigation rule:
```js
...
  helpers: {
    Playwright: {
      url: 'https://www.facebook.com',
      show: true,
      browser: 'chromium',
      waitForNavigation: "networkidle0",
    }
  },
```
I have to add an extra comma after `'chromium'`, adding git noise.  I'd prefer the thralling comma to be there already.  [Part of spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) for a while ;)

Though I confess, nit-pick (very minor) issue for a great generator.

**Comment by tomByrer** [comment]
Here is a perfect example of the extra 'git noise' that could be prevented by the generator adding the comma after `true`.
![playwright-trailing-comma](https://user-images.githubusercontent.com/1308419/76144971-de33bb00-604a-11ea-8c2d-de598eb3ab43.jpg)

**Comment by DavertMik** [comment]
Good point
