### ISSUE TITLE
request feature

### ISSUE THREAD

**Issue by spham** [codeceptjs/CodeceptJS#2259]
hi
in current version, when user see logs, all not implemented features, is display in red color.
if possible display in orange, only if not implemented, and red on error

**Comment by PeterNgTr** [comment]
@spham could you pass the example logs?

**Comment by spham** [comment]
![image](https://user-images.githubusercontent.com/1083631/76510160-7538b280-6451-11ea-9062-de382b2c1a0a.png)

**Comment by spham** [comment]
it should have difference between Failed and not Yet Implemented
