### ISSUE TITLE
Return type of "grabAttributeFrom" in Puppeteer helper

### ISSUE THREAD

**Issue by cerven** [codeceptjs/CodeceptJS#2272]
In documentation is written method `grabAttributeFrom` returns `Promise<string>` or `array` if multiple elements are matched.
1. in some cases it returns also `Promise<number>`, when attribute is numeric
2. in my opinion it should return always just one type for any context, or there should be next parameter in the method where i can choose return type

Let's say parameter "onlyFirstOccurence". If "onlyFirstOccurence is true" method should return `Promise<string>`, if "onlyFirstOccurence is false" method should return `Promise<array<string>>`

**Comment by DavertMik** [comment]
changed in 3.0
