### ISSUE TITLE
"Retries" option doesn't work (puppeteer)

### ISSUE THREAD

**Issue by aelzhanova** [codeceptjs/CodeceptJS#2278]
Hi,

I want my test to be rerun upon failure, according to the "retries" option.

What do you get instead?
For instance, I expect the following test to print "run" 3 times:

Feature('Retries')

Scenario('simple test', {retries: 2}, (I) => {
    console.log('run');
    throw new Error('boum');
});
But it prints "run" only once.
### Details

* CodeceptJS version: 2.5.0
* NodeJS Version: v13.8.0
* Operating System: MacOs Mojave
* puppeteer

**Comment by MaxTester1** [comment]
Hi

it working fine, may be launching browser and try once again

Scenario('Really complex', { retries: 2 }, (I) => {
  I.amOnPage('https://www.google.com/')
  I.see("Google")
  throw new Error('boum');
}).tag('@ret');

**Results:**
  Really complex @ret
    I am on page "https://www.google.com/"
    I see "Google"
    I am on page "https://www.google.com/"
    I see "Google"
    I am on page "https://www.google.com/"
    I see "Google"
  × Really complex @ret in 1780ms

**Comment by aelzhanova** [comment]
Hi! I forgot to attach my codecept.conf.js
`const data = require('./src/dictionaries/data');

const config = {
  helpers: {
    Puppeteer: {
      url: process.env.CODECEPT_URL || 'http://localhost:8080',
      show: false,
      browser: 'chrome',
      windowSize: '1920x1080',
      waitForAction: 0,
      waitForNavigation: 'load',
      waitForTimeout: 500,
      restart: false,
      keepBrowserState: true,
      typeInterval: '-1',
      chrome: {
        args: ['--no-sandbox', '--headless', '--window-size=1920,1080', '--disable-web-security'],
        ignoreHTTPSErrors: true,
      },
      capabilities: {
        chromeOptions: {
          w3c: false,
        },
      },
    },
    ResembleHelper: {
      require: 'codeceptjs-resemblehelper',
      baseFolder: 'base',
      diffFolder: 'diff',
    },
    MockRequest: {
      mode: 'passthrough',
      logging: false,
      recordIfMissing: false,
      recordFailedRequests: false,
      expiryStrategy: 'error',
    },
    allureHelper: {
      require: './src/helpers/allureHelper.js',
    }
  },

  include: {
    I: './steps_file.js',

    // pages:
    loginPage: './src/pages/loginPage.js',
    mainPage: './src/pages/mainPage.js',
  },
  multiple: {
    parallel: {
      // Splits tests into 2 chunks
      chunks: 4,
    },
  },
  mocha: {
    reporterOptions: {
      reportDir: './report',
      autoOpen: true,
    },
  },
  plugins: {
    allure: {
      enabled: true,
      outputDir: './allure-results',
      enableScreenshotDiffPlugin: true,
    },
    stepByStepReport: {},
    customLocator: {
      enabled: true,
      attribute: 'data-test-id',
    },
    autoLogin: {
      enabled: true,
      saveToFile: true,
      inject: 'loginAs',
      users: {
        admin: {
          login: async (I) => {
            await I.login(data.PROFFI_ADMIN);
          },
          check: (I) => {
            I.see(data.PROFFI_ADMIN.companyName);
            I.dontSeeElement("//input[@name='userName']");
          },
          fetch: () => true, // not neccessary due to "keepCookies" option
          restore: () => {}, // not neccessary due to "keepCookies" option
        },
      },
    },
  },
  tests: './tests/**/*.js',
  name: 'e2e',
};

exports.config = config;

`

**Comment by aelzhanova** [comment]
so for me retry option doesn't work

**Comment by PeterNgTr** [comment]
@aelzhanova could you run `--verbose` to see more details?

**Comment by aelzhanova** [comment]
@PeterNgTr 
CodeceptJS v2.5.0
Using test root "/Users/aelzhanova/Documents/Projects/myProject/__tests__/codeceptjsTests"
Helpers: Puppeteer, ResembleHelper, MockRequest, allureHelper
Plugins: screenshotOnFail, allure, customLocator, autoLogin

Retries --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
 › [Session] Starting singleton browser session
  simple test
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
run
    [1] Error | Error: boum
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, saving screenshot
 › Screenshot is saving to /Users/aelzhanova/Documents/Projects/seller-ui/__tests__/codeceptjsTests/_output/simple_test.failed.png
    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

  OK  | 0 passed   // 667ms
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])

**Comment by timkulich** [comment]
@aelzhanova Did you find a solution to this?
I am having the same issue. I am now on v3.0.2.

**Comment by hatufacci** [comment]
The same issue with "codeceptjs": "^3.0.4", (Playwright)

**Comment by timkulich** [comment]
You are right, this works for me too. Puppeteer. Thanks!

**Comment by stracker-phil** [comment]
With CodeceptJS 3.1.1 the following code prints `run` three times:

```js
Feature('Retries')

Scenario('simple test', {retries: 2}, ({I}) => {
	console.log('run');
	throw new Error('boum');
});
```

Output:
```
Retries --
run
run
run
  ✖ simple test in 93ms

-- FAILURES:

  1) Retries
       simple test:
     boum
```
