### ISSUE TITLE
fillField fails to type the whole value

### ISSUE THREAD

**Issue by akapitoha** [codeceptjs/CodeceptJS#2299]
#### What are you trying to achieve?
I try to fill a login form (password field in particular).

#### What do you get instead?
I get random behavior: sometimes value is typed correctly, sometimes only 4-5 symbols out of 9 are typed.

#### I use the following code (in `steps_file.js`):
```
this.amOnPage("/login")
this.seeElement(login.emailField)
this.fillField(login.emailField, email)
this.click("Next")
// here url changes
this.waitForVisible(login.pwdField)
this.click(login.pwdField)
this.fillField(login.pwdField, password)
```

Note: also strange that typing password value doesn't work for me at all without clicking the field itself before filling. though it works fine for login field.

### Details
* CodeceptJS version: 2.5.0
* NodeJS Version: 12.16.1
* Operating System: Mac os 10.14.6
* Playwright: 0.11.1

**Comment by DavertMik** [comment]
I hope this issue was fixed by Playwright team
