### ISSUE TITLE
I.mockRequest in Docker Container doesn't work

### ISSUE THREAD

**Issue by CutmastaD** [codeceptjs/CodeceptJS#2304]
#### What are you trying to achieve?

I try to mock a api request with the I.mockRequest() method by codeceptjs.
I render the result of the request in a list and right after that I check if I can see the result with I.see().
On my local windows and pop_os machines, where I installed yarn and node manually, it works like a charm. I don't even have to install chromium, simple `yarn install` does the trick.
But if I try to spawn a docker container with the node:13.12.0-buster-slim image, there's simply no response. Nothing gets rendered and therefore I don't see any results with I.see().

I needed to install all the packages from [https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix) for chromium to even spawn right.

I already tried to install chromium in the container and setting the `executablePath` in the config file, ignoring the version installed by `yarn install`. 
No other tests fail, only the ones with the mocked requests.

Edit:
When I change the api url to `localhost` and change the mockRequest url to '/something', instead of a hardcoded url, the request gets mocked right.

### Details

* CodeceptJS version: 2.5.0
* NodeJS Version: 13.12.0
* Yarn Version: 1.22.4
* Operating System: debian buster
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

**Comment by CutmastaD** [comment]
I inspected the request by running codeceptjs in --verbose mode and I got this error:
```
[Browser:Error] Access to XMLHttpRequest at 'https://blub.de/users' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Again, no mention of this on my local windows or ubuntu machine, just in the docker node container.
Is there a way to prevent this?

**Comment by PeterNgTr** [comment]
@CutmastaD could you check with latest version of codeceptjs? I thought there are some changes for `Mockrequest`.

**Comment by CutmastaD** [comment]
I tried with codeceptjs version 2.6.0 but it still doesn't work.
I had to configure chrome to disable web security, but I dont't get it, why cors-policy gets ignored on my local machines but is such an issue in an docker container.

```javascript
exports.config = {
    helpers: {
        Puppeteer: {
            chrome: {
                args: [
                    "--disable-web-security",
                    "--no-sandbox"
                ],
            }
        },
        MockRequest: {}
    },
    bootstrap: null,
};
```

**Comment by DavertMik** [comment]
better to use Playwright's mockRequest
