### ISSUE TITLE
[Playwright] I.amOnPage implementation prevents navigating to about:blank

### ISSUE THREAD

**Issue by guillaume86** [codeceptjs/CodeceptJS#2311]
This regex test prevents navigating to about:blank

https://github.com/Codeception/CodeceptJS/blob/fb2ca3002978d4b803230709cd356b0265ed930b/lib/helper/Playwright.js#L612-L614

This behavior do not match the documentation (https://codecept.io/helpers/Playwright/#amonpage) that states that only URLs starting with / will use the config base URL.

**Comment by zaxovaiko** [comment]
@DavertMik I would like to fix it, could you assign it to me, please?
