### ISSUE TITLE
Blank Allure Report 

### ISSUE THREAD

**Issue by sanjay1411** [codeceptjs/CodeceptJS#2350]
![image](https://user-images.githubusercontent.com/46441474/79847996-1e25e600-83de-11ea-8157-ecf5c85bd830.png)

--- codecept.config.js --- 
 plugins: {
        wdio: {
            enabled: true,
            services: ['selenium-standalone']
        },
        allure: {
            enabled: true,
            outputDir: "./output"
          },
        screenshotOnFail: {
            enabled: true
        },
        stepByStepReport: {
            enabled: true,
            output: "./output"
        },
     },
reporters: [['allure', {
            outputDir: 'allure-results',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: true,
        }]],
------ package.json ----
    "test:acceptance:report": "./node_modules/.bin/allure serve test/acceptance/report",
  "devDependencies": {
    "allure-commandline": "^2.13.0",
}

I tried ...
1- reinstalling npm
2- installing allure-commandline (npm install -g allure-commandline --save-dev)
3- Run via allure generate and allure generate --clean

C:\workspace\MyWorkspace\SFRABaseCodeceptJS>allure generate --clean
allure-results does not exists
Report successfully generated to allure-report

C:\workspace\MyWorkspace\SFRABaseCodeceptJS>npm install -g allure-commandline --save-dev
C:\Users\XXXXX\AppData\Roaming\npm\allure -> C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\allure-commandline\bin\allure
+ allure-commandline@2.13.0
added 1 package in 2.304s

**Comment by sanjay1411** [comment]
Can someone help ?

**Comment by sanjay1411** [comment]
Can someone help ?

**Comment by sanjay1411** [comment]
no one have any solution

**Comment by PeterNgTr** [comment]
@sanjay1411 I thought you missed something. Have you tried this?

```
allure serve output
```

**Comment by sanjay1411** [comment]
Yes i did try .. but its not working as well

**Comment by PeterNgTr** [comment]
On your local machine?

**Comment by sanjay1411** [comment]
yes

**Comment by PeterNgTr** [comment]
All right, did you see any xml files in output folder after the execution?

**Comment by sanjay1411** [comment]
Yes .. its in allure results folder

**Comment by PeterNgTr** [comment]
Hmm, why do you config allure together with allure plugin?

**Comment by sanjay1411** [comment]
I tried multiple things earlier but nothing was working. I came across one of the solution somewhere, it was related to Selenium but i thought it will work for me as well.

**Comment by xyngfei** [comment]
> I tried multiple things earlier but nothing was working. I came across one of the solution somewhere, it was related to Selenium but i thought it will work for me as well.
> By this i got succeeded once and i could see the report as well .. but now again i am in same situation.

Can you try with allure open <folder you use to store the allure output>?
