### ISSUE TITLE
Type Script Definitions not working

### ISSUE THREAD

**Issue by GVKrish2328** [codeceptjs/CodeceptJS#2375]
Ran command "npx codeceptjs def" to get type script definitions

Instead of complete list of definitions found small bit of code mentioned below in steps.d.ts file. (Nothing in steps_file.js as well)
------>
**type steps_file = typeof import('./steps_file.js');

declare namespace CodeceptJS {
  interface SupportObject { I: CodeceptJS.I }
  interface CallbackOrder { [0]: CodeceptJS.I }
  interface Methods extends CodeceptJS.WebDriver {}
  interface I extends ReturnType<steps_file> {}
  namespace Translation {
    interface Actions {}
  }
}**
<------------------

Console output --- "TypeScript Definitions provide autocompletion in Visual Studio Code and other IDEs
Definitions were generated in steps.d.ts"

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: Latest
* NodeJS Version: Latest
* Operating System: Windows
webdriverio

Below is Config file: 
exports.config = {
  tests: './*_test.js',
  output: './output',

  timeout: 1000,
  helpers: {
    WebDriver: {
      url: 'https://xha-qa.hexagonxalt.net/',
      browser: 'chrome'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'XALT_XHA_Codecept',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}

**Comment by Jimmy9222** [comment]
Alrighty I have the same issue.

Workaround, set your codeceptjs version to 2.3.5. Everything `>2.3.5` is broken.

**Comment by SDETDeven** [comment]
Hello all,

Does this issue still exist ? 

I have codeceptjs version 3.2.0. For me initially this was working but I made some changes in the config files and suddenly it stopped working. 

Could anyone please help me with the same ?

**Comment by elukoyanov** [comment]
@SDETDeven , what changes did you do?
which error are you getting?

**Comment by mcareyma** [comment]
The answer to this is to have this stanza your .tsconfig file

"ts-node":{
     "files":true
  },

--files is a flag to ts-node to make it pick up these types.
