### ISSUE TITLE
[Missing Implementation]Playwright chromium launching in Incognito Mode, no option to change it

### ISSUE THREAD

**Issue by MaxTester1** [codeceptjs/CodeceptJS#2376]
#### What are you trying to achieve?
launching application in chromium and Test

#### What do you get instead?
Chromium getting started in Incognito mode, should have option to launch in Normal mode
> Provide console output if related. Use `--verbose` mode for more details.

```bash
#      userDataDir option is not supported in `browserType.launch`. Use `browserType.launchPersistentContext` instead
  rror: userDataDir option is not supported in `browserType.launch`. Use `browserType.launchPersistentContext` instead
      at Object.assert (node_modules\playwright-core\lib\helper.js:288:15)
      at Chromium.launch (node_modules\playwright-core\lib\server\chromium.js:43:18)
      at Playwright._startBrowser (node_modules\codeceptjs\lib\helper\Playwright.js:531:61)
      at Playwright._beforeSuite (node_modules\codeceptjs\lib\helper\Playwright.js:299:19)
      at C:\Automation\Demo_Playwright\node_modules\codeceptjs\lib\listener\helpers.js:27:69
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

> Provide test source code if related

```js
// Please implement 
const browser = await playwright[browserType].launchPersistentContext(userDataDir,{headless:false})
along with
const browser = await playwright[browserType].launch({headless:false})
```

### Details

* CodeceptJS version:2.6.2
* NodeJS Version:
* Operating System:Win 10
* pPlaywright
* Configuration file:

```js
# exports.config = {
  tests: './tests/*_test.js',
  timeout: 10000,
  output: './output',
  manualStart:true,
  helpers: {
    Playwright: {
      url: '',
      show: true,
      browser: 'chromium',
      chromium: {
          browserContext: false,
          userDataDir: " C:/Users/test/AppData/Local/Chromium/User Data"
          args: [
            '--disable-features=ImprovedCookieControls',            
        ],
      },
      windowSize: '1900x1200'

```

**Comment by DavertMik** [comment]
> // Please implement 
const browser = await playwright[browserType].launchPersistentContext(userDataDir,{headless:false})
along with
const browser = await playwright[browserType].launch({headless:false})

I think you are half-done to get it implemented by yourself. 
It is easy to start contributing to CodeceptJS, send a pull request to Playwright helper with your changes and we will try to get it into a release!

**Comment by MaxTester1** [comment]
> > // Please implement
> > const browser = await playwright[browserType].launchPersistentContext(userDataDir,{headless:false})
> > along with
> > const browser = await playwright[browserType].launch({headless:false})
> 
> I think you are half-done to get it implemented by yourself.
> It is easy to start contributing to CodeceptJS, send a pull request to Playwright helper with your changes and we will try to get it into a release!

Thanks @DavertMik , i still find issues with Playwright launchPersistentContext method, will send pull request once i have proper fix.

**Comment by podmanvn** [comment]
Hello @MaxTester1 can we add a lauchType option same as jest-playwright did ?

launchType <LAUNCH | PERSISTENT | SERVER>. Method to launch browser instance. jest-playwright attaches Playwright to an existing browser instance by default.
