### ISSUE TITLE
How to use the codeceptjs APIs in docker

### ISSUE THREAD

**Issue by lepadellec** [codeceptjs/CodeceptJS#2377]
#### What are you trying to achieve?
I am trying to deploy my codeceptjs tests on docker

#### What do you get instead?

I cannot run the tests as one of my plugins cannot be loaded as it tries to use the codeceptjs APIs and it cannot include them when running within docker.

> Provide test source code if related

At the beginning of my plugin I indicate:

```js
const Container = require('codeceptjs').container;
```
When I run the tests with the docker container I get the following error:
```
Could not load plugin foreachAsync from module '/tests/src/plugins/bzlUtils':
```

I can fix this by replacing the line with:
const Container = require('/codecept/container');

But this means that it will break the tests when I run them locally!
I would like a solution that works both locally and with docker.

### Details

* CodeceptJS version: 2.6.2
* NodeJS Version: 10.19.0
* Operating System: Ubuntu 18.04
* puppeteer || webdriverio || protractor || testcafe version (if related) None
* Configuration file:

```js
exports.config = {
  tests: '../tests/api/*_test.js',
  output: '../output',
  helpers: {
  },
  include: {
    I: '../src/steps_file.js',
  },
  bootstrap: null,
  "mocha": {
    "reporterOptions": {
        "mochaFile": "output/result.xml"
    }
  },
  name: 'test',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    },
    foreachAsync: {
      enabled: true,
      require: '../src/plugins/bzlUtils'
    }
  }
}
```

**Comment by PeterNgTr** [comment]
@lepadellec how is your dockerfile looking like?

**Comment by lepadellec** [comment]
Here it is:
FROM codeception/codeceptjs

ENV NODE_PATH=/codecept/node_modules
RUN runuser -l pptruser -c 'npm install --loglevel=warn --prefix /codecept jstoxml'
RUN runuser -l pptruser -c 'npm install --loglevel=warn --prefix /codecept mocha-jenkins-reporter'
RUN runuser -l pptruser -c 'npm install --loglevel=warn --prefix /codecept promise-fs'
RUN runuser -l pptruser -c 'npm install --loglevel=warn --prefix /codecept request-promise'

CMD ["bash", "/codecept/docker/run.sh"]

**Comment by cviejo** [comment]
I think the docker image is probably meant for very isolated, basic tests.  

In your case i would just overwrite the default `CMD` instruction. Since i don't see any `COPY` in your dockerfile, i'm guessing you're mounting your project and your `node_modules` folder will be there as well.  You might not need all those extra `npm installs` either, then.

```dockerfile
FROM codeception/codeceptjs

CMD ["npx", "codeceptjs", "run"]
```
