### ISSUE TITLE
I.click and pressKey didn't work to Webdriver

### ISSUE THREAD

**Issue by x86chi** [codeceptjs/CodeceptJS#2384]
#### What are you trying to achieve?

I am writing below test step with webdriver helper for Web Extension Test on CI environment:

_Submit username and password data with `I.click('button[type="submit"]')` or `I.pressKey('Enter')`_

#### What do you get instead?

However, both methods is not real act with webdriver helper.

```bash
Login --
  ✖ Submit Correct Account in 2232ms

-- FAILURES:

  1) Login
       Submit Correct Account:
     expected url to include /frame/main.do, but found /frame/index.do
```

Test only passed when I manual click submit button or press Enter key.

```bash
Login --
  ✔ Submit Correct Account in 2333ms

  OK  | 1 passed   // 8s
```

## Provide test source code if related

```js
Feature('Login')

Before(I => {
  I.amOnPage('/frame/index.do')
  I.waitForInvisible('div#page')
})

Scenario('Submit Correct Account', async I => {
  I.fillField('input[name="student_no"]', realUsername)
  I.fillField('input[name="student_pw"]', realPassword)
  // or I.pressKey('Enter')
  I.click('button[type="submit"]')
  I.waitInUrl('/frame/main.do', 10)
})
```

### Details

* CodeceptJS version: 2.6.3
* NodeJS Version: 12.16.3
* Operating System: MacOS catalina
* webdriverio: 6.1.9
* selenium-standalone: 6.17.0
* Configuration file:

```js
const args = [`--load-extension=${path.resolve('./dist')}`]

if (HEADLESS) {
  args.push('--disable-gpu')
  args.push('--no-sandbox')
}
// ... below configs is same from webdriver helper document. 
```

**Comment by DavertMik** [comment]
sorry, not enough information, can't help
