### ISSUE TITLE
I screenshot the element

### ISSUE THREAD

**Issue by roughsoft** [codeceptjs/CodeceptJS#2401]
#### What are you trying to achieve?
screenshot the element in the current page.
#### What do you get instead?
now i must write helper.
i suggestion these command:
I.screenshotElement(".recha","debug.png");

**Comment by PeterNgTr** [comment]
Could you make a PR?

**Comment by suniljaiswal01** [comment]
@PeterNgTr  Should i try this?

**Comment by PeterNgTr** [comment]
Hell yeah, why not? 🙌🏻
