### ISSUE TITLE
run-workers not working with docker container

### ISSUE THREAD

**Issue by KarthikP1306** [codeceptjs/CodeceptJS#2417]
Context:

Codecept version : 2.6.5
Playwright Version: [what Playwright version do you use?] : 1.0.2
Node version: [e.g. 10.12, 10.14] : 14.3.0
Browser: [e.g. All, Chromium, Firefox, WebKit] : Chromium

-------------------------------------------------------------------------------------------------------------

Describe the bug

Positive Scenario
In local (i.e without docker) we are able to run the workers without any issue

npx codeceptjs run-workers 3 --grep "@tag1"

Negative Scenario
a) In docker container, when we are running with multiple(i.e 3 in this case) workers, parallel execution by workers is not working.

docker run --net=host -it -v $PWD:/tests --name container-name image-name --entrypoint npx codeceptjs run-workers 3 --grep "@tag1"

b) In docker container, when we are running with single worker, parallel execution by workers is woking fine.

docker run --net=host -it -v $PWD:/tests --name container-name image-name --entrypoint npx codeceptjs run-workers 1 --grep "@tag1"

Could you please help us in resolving this issue?

**Comment by golfzaptw** [comment]
I found this problem too.

<img width="1125" alt="Screen Shot 2563-06-02 at 11 09 42" src="https://user-images.githubusercontent.com/21608972/83479028-a27d8580-a4c1-11ea-9676-36537821ec37.png">

**Comment by idxn** [comment]
@golfzaptw can you try with codeceptjs 3?

**Comment by PeterNgTr** [comment]
@KarthikP1306 did you follow here to use `run-workers` for docker container?

**Comment by jancorvus** [comment]
@PeterNgTr did you mean a link for 'here'?

**Comment by PeterNgTr** [comment]
> @PeterNgTr did you mean a link for 'here'?

Hey sorry for missing the link. https://codecept.io/docker.html#codeceptjs-docker
