### ISSUE TITLE
Mockawesome reporter not working with run-workers

### ISSUE THREAD

**Issue by RatnakarShetty** [codeceptjs/CodeceptJS#2421]
mochawesome reporter works fine with run commond but not working with run-workers plz find the below commands:

**Working fine:**
`npx codeceptjs --reporter mochawesome run --grep "@smokeTest"`

**Not working :**
```
npx codeceptjs --reporter mochawesome run-workers 2 --grep "@smokeTest"
Getting error as : error: unknown option `--reporter'
```

**Comment by storenth** [comment]
Same issue here, but with
```bash
npx codeceptjs run-workers --suites 2 --plugins allure --reporter mocha-junit-reporter -c chrome_selenoid_codecept.conf.js --grep @async
error: unknown option `--reporter'
```

**Comment by DavertMik** [comment]
we don't support mochawesome out of box
but I think `--reporter` option is availble now
