### ISSUE TITLE
Some Test Case are getting skipped

### ISSUE THREAD

**Issue by kuldeepsingh99** [codeceptjs/CodeceptJS#2425]
Some scenarios are getting skipped, if we are running the Test case.

We have almost 20 feature file and each file contains around 40 Test Cases.

I am only getting "Skipped due to failure in 'before' hook" 

In one of the Cases whole file gets skipped and one Test case got failed due to session time,  is session timeout causing the other test case skipped

**Comment by DavertMik** [comment]
not enough info to reproduce
