### ISSUE TITLE
Click on element with text

### ISSUE THREAD

**Issue by potapovDim** [codeceptjs/CodeceptJS#2430]
It can be a feature request, if I have a selector with the required text, why I do not have the possibility to click that tag?

#### What are you trying to achieve?
I want to click in 'td' tag where value is "808482.18"
#### What do you get instead?
I got 

```bash
Evaluation failed: DOMException: Failed to execute 'querySelectorAll' on 'Element': '808482.18' is not a valid selector.
    at __puppeteer_evaluation_script__:1:33

```
> Provide test source code if related

```js
clickOnMachineWithRequiredPrice(price = '808482.18') {
    I.click(price, 'td')
  }
```

### Details

* CodeceptJS version: 2.6.5
* NodeJS Version: v13.11.0
* Operating System: mac os

**Comment by DavertMik** [comment]
can be implemented as custom helper but not in CodeceptJS API
