### ISSUE TITLE
rightClick in WebDriver is not working

### ISSUE THREAD

**Issue by ramkumarizaap** [codeceptjs/CodeceptJS#2433]
i am trying to do rightClick functionality but it doesn't work and its continuing to execute with other test cases automatically.

**Comment by shanplourde** [comment]
The same issue happens for me too with WebDriver. Appreciate any breadcrumbs or pointers to help resolve this.

**Comment by suniljaiswal01** [comment]
@PeterNgTr  anyone looking into this issue? I have made a fix using executeScript which is working on firefox and chrome. Should i create a PR for the same?

**Comment by PeterNgTr** [comment]
That would be awesome 😎
