### ISSUE TITLE
Store API Request and Response during Test Execution in CodeceptJS

### ISSUE THREAD

**Issue by sreekanthjkprojects** [codeceptjs/CodeceptJS#2468]
#### What are you trying to achieve?
I am trying to achieve TestCafe's RequestLogger concept in CodeceptJS. By adding code in the custom helper and use it.

#### What do you get instead? Below is my code from custom helper: 
```js
const { Helper } = codeceptjs;

class ReadingapiResponse extends Helper {

//Method to read api response with RequestLogger class
    async apiResponse(){
      const { t } = this.helpers.TestCafe;
      //const { RequestLogger } = this.helpers.TestCafe;
      //const Requestlogger1 = await this.helpers['TestCafe'].RequestLogger('/IARider/',{logResponseBody: true,stringifyResponseBody: true});
      const Requestlogger1 = await this.helpers['TestCafe'].RequestLogger;
      console.log("I am in apiResponse method");
      const logger = RequestLogger('/getSignOnInformation/',{logResponseBody: true,stringifyResponseBody: true});
      console.log("Status code is " + logger.requests[0].response.statusCode)

    }

```
> Provide console output if related. Use `--verbose` mode for more details. Below error is what I get:
[Wrapped Error] {"code":"E24","isTestCafeError":true,"callsite":{"filename":"C:\\Users\\175146\\Desktop\\CodeceptJs_Project\\readingapiResponse_testcafe.js","lineNum":10,"callsiteFrameIdx":6,"stackFrames":[{},{},{},{},{},{},{},{},{}],"isV8Frames":true},"apiFnChain":["Selector('#loginbtn')"],"apiFnIndex":0}
```bash
# paste output here
```
[Wrapped Error] {"code":"E24","isTestCafeError":true,"callsite":{"filename":"C:\\Users\\175146\\Desktop\\CodeceptJs_Project\\readingapiResponse_testcafe.js","lineNum":10,"callsiteFrameIdx":6,"stackFrames":[{},{},{},{},{},{},{},{},{}],"isV8Frames":true},"apiFnChain":["Selector('#loginbtn')"],"apiFnIndex":0}
> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 
* NodeJS Version: v12.16.1
* Operating System:
* puppeteer || webdriverio || protractor || **testcafe** version (if related)
* Configuration file:

```js
# paste config here
//helper section of config file
helpers: {
    TestCafe: {
      url: 'https://accountviewer.qa.advisorcompass.com/',
      browser: 'chrome',
      show: true,
      RequestLogger: 'RequestLogger("/IARider/",{logResponseBody: true,stringifyResponseBody: true})'
    },
```

**Comment by sreekanthjkprojects** [comment]
hi, is there anyone who can help. Thank you!

**Comment by Vorobeyko** [comment]
hi!
You can use just `Helper` without declaration, because Helper is global variable

**Comment by sreekanthjkprojects** [comment]
ok thanks Vorobeyko. Is there a way we can Intercept Http Request in CodecepJS with any of the custom helpers?

**Comment by Vorobeyko** [comment]
You can intercept request with Puppeteer^ but you need to write custom helper and use this Puppeteers methods https://pptr.dev/#?product=Puppeteer&version=v4.0.1&show=api-event-request

**Comment by sreekanthjkprojects** [comment]
const { Helper } = codeceptjs;
class Puppeteer_api extends Helper {
  Puppeteer_Reading_httpRequests(){
    //Creating page object 
    const { page } = this.helpers.Puppeteer;

    page.setRequestInterception(true);

}

//I dont know how to use the setRequestinterception method. But found some code as mentioned below. Please tell me how to read service response from here after. I will just give the name of the service without using uri and headers, I should be able to read response. Please suggest


    const polly = new Polly('puppeteer', {
      adapters: ['puppeteer'],
      adapterOptions: { puppeteer: { page } },
      persister: 'fs',
      persisterOptions: {
      fs: {
        recordingsDir: path.join(__dirname, 'recordings')
      }
      }
    });

    const { server } = polly;

      server.host('http://localhost:3000', () => {
      server.get('/favicon.ico').passthrough();
      server.get('/sockjs-node/*').intercept((_, res) => res.sendStatus(200));
    });
  }


}

module.exports = Puppeteer_api;


O/P: Getting error stating that polly is not defined
