### ISSUE TITLE
Why cant we use RequestLogger class of TestCafe in CodeceptJS. What could be stopping us?

### ISSUE THREAD

**Issue by sreekanthjkprojects** [codeceptjs/CodeceptJS#2479]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by DavertMik** [comment]
Please send PR
