### ISSUE TITLE
Having shell report colorized in Gitlab-ci

### ISSUE THREAD

**Issue by medtoure18** [codeceptjs/CodeceptJS#2500]
#### What are you trying to achieve?
Read my test result in gitlabci job result. 

#### What do you get instead?
Colored texts on condeceptjs on my local machine i not shown on gitlabci

* CodeceptJS version:2.5
* Operating System: Linux
* GitlabCi: 12.9

![Capture du 2020-07-25 01-50-00](https://user-images.githubusercontent.com/46603792/88443742-ca31ff80-ce19-11ea-964a-bd6b9bb20644.png)

**Comment by PeterNgTr** [comment]
Hey @medtoure18 trying adding this --colors

**Comment by Vorobeyko** [comment]
you can use 
```yaml
variables:
  FORCE_COLOR: '1'
```

**Comment by medtoure18** [comment]
awesome :-)
thank you @Vorobeyko 
![Capture du 2020-07-25 10-37-52](https://user-images.githubusercontent.com/46603792/88452945-210ff700-ce63-11ea-83ff-60c9c302a92e.png)
