### ISSUE TITLE
Timeout configuration is ignored due to a mocha bug

### ISSUE THREAD

**Issue by ian-speers** [codeceptjs/CodeceptJS#2509]
#### What are you trying to achieve?

I'm trying to configure timeouts but they are being ignored.

#### What do you get instead?

I would like configured timeouts to be respected.

### Details
There are a few places in the code where `[Runnable].timeout(0)` is being called ([here](https://github.com/codeceptjs/CodeceptJS/blob/master/lib/ui.js#L38), [here](https://github.com/codeceptjs/CodeceptJS/blob/master/lib/ui.js#L102), [here](https://github.com/codeceptjs/CodeceptJS/blob/master/lib/scenario.js#L31), etc.). There was a [bug in `Runnable.timeout`](https://github.com/mochajs/mocha/issues/4254) prior to [mocha v8.0.1](https://github.com/mochajs/mocha/releases/tag/v8.0.1) which caused timeouts to remain permanently disabled after being set to zero. Would it be possible to upgrade mocha, or to change all occurrences of `[Runnable].timeout(0)` to `[Runnable].timeout(Number.MAX_SAFE_INTEGER)`? I'd be glad to handle the latter, but upgrading mocha caused a bunch of tests to fail and I don't have time to resolve those at the moment. Let me know—thanks!

**Comment by Vorobeyko** [comment]
Hi @ian-speers. We are works on this bug on https://github.com/codeceptjs/CodeceptJS/pull/2464

**Comment by ian-speers** [comment]
Thanks @Vorobeyko! I see that's tagged for the 3.0 release. In the meantime, would you be open to a PR that fixes this as described above? If not—do you have an ETA for that release?

**Comment by ian-speers** [comment]
For anyone else facing this issue, I added a postinstall hook to my project to patch the broken behavior.
```json
"postinstall": "grep -rlF '.timeout(0)' node_modules/codeceptjs/lib | xargs sed -i.bak 's/.timeout(0)/.timeout(Number.MAX_SAFE_INTEGER)/g'"
```
Looking forward to the 3.0 release so I can remove this 😁
