### ISSUE TITLE
Error in execution - "I.saveElementScreenshot is not a function "

### ISSUE THREAD

**Issue by sanjay1411** [codeceptjs/CodeceptJS#2531]
Saving Screenshot for a specific element

"I.saveElementScreenshot is not a function "

**Comment by PeterNgTr** [comment]
Which helper are you using? Are you also using the latest codeceptjs version?

**Comment by sanjay1411** [comment]
Webdriver

**Comment by suniljaiswal01** [comment]
@sanjay1411  can you please provide the logs of the error and code to reproduce the issue

**Comment by sanjay1411** [comment]
I used Verbose and below is the error from consol.
 Emitted | step.passed (I wait for visible ".report-performance.clear")
    Emitted | step.finish (I wait for visible ".report-performance.clear")
    [1] Error | TypeError: I.saveElementScreenshot is not a function
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
 » <screenshotOnFail> Test failed, saving screenshot
 » Screenshot has been saved to C:\workspace\sfra-automation\test\acceptance\report\Admin_is_able_to_check_site_performance_check_via_GTMatrix_and_pull_full_report_@perfromance.failed.png
  × FAILED in 70590ms
    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])



Code : 
  I.saveElementScreenshot('.report-tabs.r-tabs','GT.png');

**Comment by suniljaiswal01** [comment]
I have tried the same. It is working fine. Please find the below repository for example

https://github.com/suniljaiswal01/Codeceptjs-Javascript-Example
