### ISSUE TITLE
CodeceptJS 3:  Error: "I.say is not a function"

### ISSUE THREAD

**Issue by ngraf** [codeceptjs/CodeceptJS#2538]
#### What are you trying to achieve?
Execute `I.say` or `I.retry` in CodeceptJS 3 Beta.4

#### What do you get instead?
Errors `I.say is not a function` or `I.retry is not a function`

> Provide console output if related. Use `--verbose` mode for more details.

```bash
$ npx codeceptjs run
DEPRECATION NOTICE:
You are using webdriverio v5. It is recommended to update to webdriverio@6.
Support of webdriverio v5 is deprecated and will be removed in CodeceptJS 3.0

CodeceptJS v3.0.0-beta.4
Using test root "/Users/grafn/projects/Isay"

Isay --
Error: old CodeceptJS v2 format detected. Upgrade your project to the new format -> https://bit.ly/codecept3Up
  ✖ test something in 313ms

-- FAILURES:

  1) Isay
       test something:
     I.say is not a function
      at Test.<anonymous> (Isay_test.js:4:4)
      at Context.test.fn (node_modules/codeceptjs/lib/scenario.js:79:14)


  Artifacts:
  - screenshot: /Users/grafn/projects/Isay/output/test_something.failed.png


  FAIL  | 0 passed, 1 failed   // 1s
```

> Provide test source code if related

```js

Feature('Isay');

Scenario('test something', (I) => {
        I.say('hello world');
        I.retry(2).amOnPage('https://www.google');
});
```

### Details

* CodeceptJS version: 3.0 beta.4
* NodeJS Version: 12.16
* Operating System: MacOS Catalina
* webdriverio
* Configuration file:

```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './*_test.js',
  output: './output',
  helpers: {
    WebDriver: {
      url: 'http://localhost',
      browser: 'chrome'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'Isay',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

Steps file:

```
// in this file you can append custom step methods to 'I' object

module.exports = function() {
  return actor({

    // Define custom steps here, use 'this' to access default methods of I.
    // It is recommended to place a general 'login' function here.

  });
}
```

**Comment by PeterNgTr** [comment]
Hey, with codeceptjs v3.0 you should inject like {I} not I like older version.

**Comment by ngraf** [comment]
> Hey, with codeceptjs v3.0 you should inject like {I} not I like older version.

That does not fix it. Still the same error.

------

Instead I have file a 2nd bug then :/ 

🐞 CodeceptJS 3: "npx codeceptjs init" creates a test scenario with "I" not correctly injected

**Comment by ngraf** [comment]
The interesting thing is that the missing methods match exactly the methods defined in basic class "Actor":
https://github.com/codeceptjs/CodeceptJS/blob/codeceptjs-v3.0/lib/actor.js#L22

**Comment by PeterNgTr** [comment]
> > Hey, with codeceptjs v3.0 you should inject like {I} not I like older version.
> 
> That does not fix it. Still the same error.
> 
> Instead I have to file a 2nd bug then, because the test above with old injection was created by CodeceptJS 3 itself :/
> 
> 🐞 CodeceptJS 3: "npx codeceptjs init" creates a test scenario with "I" not correctly injected

maybe it's missing here, the `{ I }` https://github.com/codeceptjs/CodeceptJS/blob/codeceptjs-v3.0/lib/command/generate.js#L15

**Comment by PeterNgTr** [comment]
> The interesting thing is that the missing methods "say" and "retry" match exactly the methods defined in basic class "Actor":
> https://github.com/codeceptjs/CodeceptJS/blob/codeceptjs-v3.0/lib/actor.js#L22

@ngraf that worked fine for me.
<img width="858" alt="Screen Shot 2020-08-18 at 5 31 54 PM" src="https://user-images.githubusercontent.com/7845001/90533441-cecba880-e178-11ea-847a-70b3d4e5c6ad.png">

**Comment by ngraf** [comment]
@PeterNgTr , do you also make use of a `steps_file.js` file like me?

I think this important here to mention. Because if I do not use `steps_file.js` the error is not present.
My `steps_file.js` has been created also by `npx codeceptjs init`. So it should be reproducable easily.

**Comment by PeterNgTr** [comment]
Hey @ngraf I don't have step_file.js in my demo repo.

**Comment by ngraf** [comment]
"step_files.js" is always part of standard "npx codeceptjs init" process.

Exact steps to reproduce the error:

1) Create empty directory and enter it
2) Run `npm install codeceptjs@3.0.0-beta.4``
3) Run `npx codeceptjs init` and always press "ENTER" for any question asked
4) Edit created file `_test.js` and add test step `I.say('hello world')`
5) Run `npx codeceptjs run` will give you 🔴
```
      test something:
     I.say is not a function
```

**Comment by PeterNgTr** [comment]
I guess this issue is fixed by https://github.com/codeceptjs/CodeceptJS/pull/2582

**Comment by ngraf** [comment]
I can confirm my reported bug is fixed now in official final public version of "3.0.0" 👍🏻
