### ISSUE TITLE
codeceptjs run --grep with full scenario name does not work anymore

### ISSUE THREAD

**Issue by ITJula** [codeceptjs/CodeceptJS#2542]
Feature('My feature');

Scenario('test something @test', I => {
  I.say('Start')
  I.amOnPage('https://github.com/codeceptjs/CodeceptJS/issues/new')
});

PROBLEM:
If I try to run codeceptjs run --grep "test something", it does not find the test to run.
It works perfectly with --grep "@test" | --grep "test" | --grep "something"

Am I doing smth wrong or grep does not support > 1 word now?
It was a very useful feature, it would be great to have it back.

I am using:
CodeceptJS version: v2.6.8 + puppeteer

**Comment by PeterNgTr** [comment]
@ITJula just reopen this if you encounter the same with v3.0
