### ISSUE TITLE
objects in include {} are not accepted 

### ISSUE THREAD

**Issue by ITJula** [codeceptjs/CodeceptJS#2543]
#### What are you trying to achieve?

Instead of providing a path, I want to pass an object, when declaring a page object.

According to the documentation, objects are accepted to use:
"include: {} - actors and page objects to be registered in DI container and included in tests. Accepts objects and module require paths"

#### What do you get instead?

![image](https://user-images.githubusercontent.com/25804314/90648682-1f570a80-e23a-11ea-8bc0-41ca8ddad4fe.png)

### Details
CodeceptJS version: 2.6.8 + puppeteer

1. I have a separate project with pages, where I export the pages as following:

const myExample = require(./pages/myExample.js')

module.exports = {
  myExample
}

2. In the codecepjs.config file I want to use it as:
   include: {
      myPage: separatePages.myExample
    }

**Comment by DavertMik** [comment]
only string, right
