### ISSUE TITLE
Could not load plugin wdio from the Module './plugin/wdio'

### ISSUE THREAD

**Issue by Mayur150** [codeceptjs/CodeceptJS#2562]
exports.config = {
tests: '././*_test.ts',
//output: './output',
timeout: 10000,
helpers: {
WebDriver: {
url: 'https://localhost.com/dummy',
browser: 'chrome',
smartWait: 5000,
windowSize: '1920x1680',
desiredCapabilities: {
chromeOptions: {
useAutomationExtension: false,
// args: [
// '--headless',
// '--disable-gpu',
// '--disable-web-security',
// '--window-size=1200,1000',
// '--no-sandbox'
// ]
}
}
}
},
plugins: {
wdio: {
enabled: true,
services: [
['selenium-standalone', {
installArgs: {
version: '3.141.59',
baseURL: 'https://selenium-release.storage.googleapis.com',
drivers: {
chrome: {
version: '84.0.4147.30',
baseURL: 'https://chromedriver.storage.googleapis.com'
}
},
proxy: 'http://http.corporateproxy.com:port'
},
args: {
drivers: {
chrome: {
version: '84.0.4147.30'
}
}
}
}]
]
}
},
include: {
I: './steps_file.js'
},
bootstrap: null,
//mocha: { },
name: 'e2e'
}

"@wdio/cli": "^6.3.6",
"@wdio/selenium-standalone-service": "^6.1.14",
"codeceptjs": "^2.6.6",
"webdriverio": "^6.1.23"

Experiencing this Error :
Could not load plugin wdio from module './plugin/wdio':
name.toLowerCase is not a function

could someone help us i resolving this

**Comment by Obi-Dann** [comment]
Ran into the same issue. It looks like a bug in wdio plugin, but I manage to fix it with adding `webdriver@6` as a dependency. By default codeceptjs will include `webdriver@5` (which is also probably a bug) because it's a dependency of `@codeceptjs/configure`

**Comment by Mayur150** [comment]
> webdriver@6

do you mean to install the Webdriver dependency of version 6 in our package ?

**Comment by Mayur150** [comment]
@Obi-Dann Installed "webdriverio": "^6.4.2" Its not working

**Comment by PeterNgTr** [comment]
> Ran into the same issue. It looks like a bug in wdio plugin, but I manage to fix it with adding `webdriver@6` as a dependency. By default codeceptjs will include `webdriver@5` (which is also probably a bug) because it's a dependency of `@codeceptjs/configure`

Probably like @Obi-Dann said, https://github.com/codeceptjs/configure/blob/master/package.json#L27

**Comment by code1x1** [comment]
I created issue #2567 where I described the problem. 
The plugin reads version from wdio service installed inside codeceptjs package while the require is calling wdio service from node modules. Wouldn't it be better to try get package version from wdio service installed in node modules and use version from codeceptjs node modules wdio as fallback

**Comment by Mayur150** [comment]
@PeterNgTr changing the version will it fix ?

**Comment by gulench** [comment]
@Mayur150, the `wdio` plugin in your `codecept.conf.js` is configured using the WebdriverIO v6 format. However, in its current state, the `wdio` plugin does not parse the `services` configuration as per the WebdriverIO v6 format. Refer below, the relevant lines from the `wdio` plugin's source:

https://github.com/codeceptjs/CodeceptJS/blob/a1c9a18ab78d28b3284eba01ed64e00714fcd7b0/lib/plugin/wdio.js#L98-L100

The `wdio` plugin is expecting a *list* of **service names** in the `services` array. Here is the configuration that you mentioned in your report:

```javascript
  plugins: {
    wdio: {
      enabled: true,
      services: [
        ['selenium-standalone', {
            installArgs: {
              version: '3.141.59',
              baseURL: 'https://selenium-release.storage.googleapis.com',
              drivers: {
                chrome: {
                  version: '84.0.4147.30',
                  baseURL: 'https://chromedriver.storage.googleapis.com'
                }
              },
              proxy: 'http://http.corporateproxy.com:port'
            },
            args: {
              drivers: {
                chrome: {
                  version: '84.0.4147.30'
                }
              }
            }
          }
        ]
      ]
    }
```

**Comment by khanzzirfan** [comment]
@gulench and others, the correct way to mention the selenium args and selenium install args for codeceptjs configuration is 
This will solve the problem for could not load plugin wdio .... 
``` 
wdio: {
            enabled: true,
            services: ['selenium-standalone'],
            seleniumArgs: {
                version: '3.141.5', // Selenium standalone server version
                drivers: {
                    chrome: {
                        version: '75.0.3770.140', // Chromedriver version
                    },
                    firefox: {
                        version: '0.24.0', // Geckodriver version
                    },
                },
            },
            seleniumInstallArgs: {
                version: '3.141.5',
                baseURL: 'https://selenium-release.storage.googleapis.com',
                drivers: {
                    chrome: {
                        version: '75.0.3770.140',
                        arch: process.arch,
                        baseURL: 'https://chromedriver.storage.googleapis.com',
                    },
                    firefox: {
                        version: '0.24.0',
                        arch: process.arch,
                        baseURL: 'https://github.com/mozilla/geckodriver/releases/download',
                    },
                },
            },
        },
        
        ```

**Comment by gkushang** [comment]
If you're seeing this issue, pls update below to the latest,

```
“@wdio/selenium-standalone-service”: “latest",
“webdriverio”: “latest"
```
