### ISSUE TITLE
is it intentionally checking for version 5?

### ISSUE THREAD

**Issue by code1x1** [codeceptjs/CodeceptJS#2567]
Hi

Is this code line intentionally checking for version 5 even though most of these plugins are far beyond v6 atm?

https://github.com/codeceptjs/CodeceptJS/blob/a1c9a18ab78d28b3284eba01ed64e00714fcd7b0/lib/plugin/wdio.js#L106

The reason why I'm asking is because this function requires the plugins from <project>/node_modules/@wdio/x-service but the constructor is then called according to the installed service in <project>/node_modules/codeceptjs/node_modules/@wdio/x-service 
That  could be fixed by checking if plugins are installed in project node_modules or at least print some error message that user has to install a different version.

I would like to open the pr if you want any help?

**Comment by gulench** [comment]
Please see the [update](https://github.com/codeceptjs/CodeceptJS/issues/2562#issuecomment-686417281) to issue #2562. In its current state, the `wdio` plugin *parses* configuration as per the **Webdriverio v5** *format*:

https://github.com/codeceptjs/CodeceptJS/blob/a1c9a18ab78d28b3284eba01ed64e00714fcd7b0/lib/plugin/wdio.js#L98-L100

Yet , a little later in the plugin's *control flow*, it tries to be *compatible* with the **Webdriver v6** *semantics*, but *without passing* any **custom options** to the wdio service:

https://github.com/codeceptjs/CodeceptJS/blob/a1c9a18ab78d28b3284eba01ed64e00714fcd7b0/lib/plugin/wdio.js#L108-L111

**Comment by code1x1** [comment]
So this is not by design and should be fixed?
