### ISSUE TITLE
Playwright: checkOption method does not work when I use a label name.

### ISSUE THREAD

**Issue by ukiras123** [codeceptjs/CodeceptJS#2571]
#### What are you trying to achieve?
Trying to click on a checkbox using a label name.

#### What do you get instead?
It is not working on Playwright but works with Puppeteer.

> Provide console output if related. Use `--verbose` mode for more details.
[api] retrying click action
[api]   waiting for element to be visible, enabled and not moving
[api]   element is visible, enabled and does not move
[api]   scrolling into view if needed
[api]   done scrolling
[api]   checking that element receives pointer events at (618.5,609.06)
[api]   element does not receive pointer events
[api] retrying click action
[api]   waiting for element to be visible, enabled and not moving

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: ^2.6.10
* NodeJS Version: 6.7.0
* Operating System: OSX
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
 Playwright: {
    show: process.env.SHOW || false,
    waitForNavigation: 'networkidle0',
    waitForAction: 500,
    chrome: { args: chromiumArgs },
  },
```

**Comment by arcsun** [comment]
The default locater has too many restrictions, you could try making your own one, for example:
`
function xpath (pattern, index = 1) {
        let indexStr = `[${index}]`
        if (index <= 0) {
            indexStr = `[last()-${Math.abs(index)}]`
        }
        return `(//*[contains(text(),'${pattern}')] | //*[@*[contains(normalize-space(),'${pattern}')]])${indexStr}`
    }
`
it will find all element with specified text
