### ISSUE TITLE
Codeceptjs exit process after tests

### ISSUE THREAD

**Issue by code1x1** [codeceptjs/CodeceptJS#2573]
#### What are you trying to achieve?

Running codeceptjs with normal end if tests failed. 
I dont need the tests reports.
I'm fine if the process just shutdown normally so the test server can handle the return value of the test script.

#### What do you get instead?

Codeceptjs runs all tests and printing an end result with successful/failed tests.
But the process doesnt stop. I have to manually shutdown the process
If all tests passed codeceptjs process exit normally. 
If a test failed the codeceptjs process just prints the error log and waits for the user to end the process.
Cant use on CI Script because the server must kill the process.

  FAIL  | 55 passed, 14 failed   // 22m

### Details

package.json

```json
{
  "name": "robotinterface",
  "version": "2.1.0",
  "author": "xxx",
  "scripts": {
     "test:e2e:selenium": "npm run build-version && codeceptjs run --config test/codecept.conf.chromedriver.js",
  }
}
```

* CodeceptJS version: 2.6.10
* NodeJS Version: v12.16.3
* Operating System: Debian Linux ws-xxx 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
* chromedriver: 85.0.0
* Configuration file:

```js
exports.config = {
    tests: './e2e/**/*_test.js',
    output: './test-reports',
    timeout: 10000,
    helpers: {
        REST: {
            endpoint: "http://localhost/api/",
            defaultHeaders: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
            },
        },
        WebDriver: {
            // base url inside selenoid container
            url: 'http://localhost',
            // selenoid settings
            host: 'localhost',
            protocol: 'http',
            port: 9515,
            path: '/',
            browser: 'chrome',
            smartWait: 5000,
            desiredCapabilities: {
                chromeOptions: {
                    args: ["--disable-gpu", "--no-sandbox"]
                }
            }
        },
        DbHelper: {
            require: '../node_modules/codeceptjs-dbhelper'
        }
    },
    plugins: {
        allure: {
            enabled: false
        },
        screenshotOnFail: {
            enabled: false
        }
    },
    include: {
        I: './steps_file.js'
    },
    bootstrap: null,
    mocha: {},
    name: 'robotinterface'
}

```

Thank you :)

**Comment by code1x1** [comment]
ok i found it
you have to set bail: true in codeceptjs.conf.js

```js
    mocha: {
        bail: true
    },
```

**Comment by SAapronova** [comment]
the same problem
and bail: true doesn't help
