### ISSUE TITLE
Element is visible, but cannot be seen nor clicked??

### ISSUE THREAD

**Issue by naholyr** [codeceptjs/CodeceptJS#2587]
#### What are you trying to achieve?

I'm trying to click on a visible link on the page.

#### What do you get instead?

The console says "expected web application to include "a[data-poll-mode="run"]"" and fails.

I tried `click` then tried with `see` :

```js
I.see('a[data-poll-mode="run"]');
I.see({ css: 'a[data-poll-mode="run"]' });
I.see(locate('a').withAttr({ 'data-poll-mode': 'run' }));
```

Nothing works, so one could say "but dude, your element is not on the page, doh'!" but it gets weird here:

```js
// This displays "1"
console.log(await I.grabNumberOfVisibleElements('a[data-poll-mode="run"]'));
```

So the element **is** there.

Its HTML is ``<a href="#poll-popup" data-poll-mode="run" class="js-openPollPopup"><i>&#xe97f;</i></a>``, it's a custom font for symbols. Does it matter?

**How can there be such behavior difference betweet those methods?**

### Details

* CodeceptJS version: 2.6.10
* NodeJS Version: 14.9.0
* Operating System: Ubuntu 20.04.1 LTS
* Puppeteer: 5.3.0 (found in node_modules)
* Configuration file:

```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './test/*.js',
  output: './test/output',
  helpers: {
    Puppeteer: {
      url: 'http://localhost:8080',
      show: true,
      windowSize: '1200x900'
    },
    clickIfVisible: {
      require: './test/helpers/click-if-visible.js',
    },
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'LAP',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
};
```

**Comment by brunoklein** [comment]
Hey Nicolas! 

Try to use I.seeElement('a[data-poll-mode="run"]');

Other options:

I.seeElement("//a[@data-poll-mode='run']");
I.seeElement({ xpath: "//a[@data-poll-mode='run']" });

Sincerely,
Bruno Klein
