### ISSUE TITLE
waitForTimeout not working when selenoid plugin is used

### ISSUE THREAD

**Issue by suniljaiswal01** [codeceptjs/CodeceptJS#2589]
#### What are you trying to achieve?
I am trying to run my testcase using the default waitForTimeout Value. But when i use selenoid plugin as well, the waitForTimeout value is not getting used and my test are getting failed within milliseconds.

Below are my observation because of which the issue could have been occured:

https://github.com/codeceptjs/CodeceptJS/blob/master/lib/plugin/selenoid.js#L340
https://github.com/codeceptjs/CodeceptJS/blob/master/lib/plugin/selenoid.js#L352

Whenever the _setConfig method is called, waitForTimeout value is getting divided by 1000. because of which whatever is the initial value passed in the codecept.conf.js file, gets decreased before every test execution.

#### What do you get instead?
Not able to use selenoid plugin along with waitForTimeout.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
-- FAILURES:

  1) Selenoid
       Selenoid Plugin Test:
     element (//a[@class='Header-link']) still not visible after 0.00001 sec
  Scenario Steps:

  - I.waitForVisible("//a[@class='Header-link']") at Test.<anonymous> (selenoidIssue_test.js:5:7)
  - I.amOnPage("https://github.com") at Test.<anonymous> (selenoidIssue_test.js:4:7)
```

> Provide test source code if related

```js
Feature('Selenoid');

Scenario('Selenoid Plugin Test', (I) => {
    I.amOnPage('https://github.com');
    I.waitForVisible("//a[@class='Header-link']");
});

```

### Details

* CodeceptJS version:2.6.10
* NodeJS Version: 12.18.4
* Operating System: Windows 10
* puppeteer || webdriverio || protractor || testcafe version (if related) : webdriverio
* Configuration file:

```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './*_test.js',
  output: './output',
  
  helpers: {
    WebDriver: {
      host: "192.168.99.100",
      port: 4444,
      waitForTimeout: 10000,
      url: 'http://localhost',
      browser: 'chrome'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'CodeceptTest',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    },
    selenoid:{
      enabled: true,
      enableVideo: true,
      enableLog:true
    },
    wdio: {
      enabled: false,
      services: ['selenium-standalone']
    }
  }
}
```

**Comment by pmajewski24** [comment]
Same happens, if a Config is set/reset in a Scenario.

CodeceptJs: 3.3.6
Helper: WebDriver, Protractor, Appium
