### ISSUE TITLE
Type definitions are wrong for REST helper

### ISSUE THREAD

**Issue by miridius** [codeceptjs/CodeceptJS#2590]
#### What are you trying to achieve?

Use the REST helper in a typescript project

#### What do you get instead?

Typescript compile errors because the provided type definitions for the REST helper do not match the actual method signatures.

The _executeRequest method and all of the send* methods are async and return the response object, however the type definition marks them as returning void. This means that in my code using these methods if I actually try to use the response object, typescript throws an error: `Type 'void' is not assignable to type 'AxiosResponse<any>'`

In addition, the arguments for each method are all marked as being required, even though most of them are optional, which means I have to pass `undefined` for each argument to prevent typescript compiler errors. 

> Example showing both of the above issues
```ts
import { AxiosResponse } from 'axios';
const res: AxiosResponse = await this.sendPostRequest('', {});
```

```bash
helpers/steps_file.ts:46:13 - error TS2322: Type 'void' is not assignable to type 'AxiosResponse<any>'.

46       const res: AxiosResponse = await this.sendPostRequest('', {});
               ~~~

helpers/steps_file.ts:46:45 - error TS2554: Expected 3 arguments, but got 2.

46       const res: AxiosResponse = await this.sendPostRequest('', {});
                                               ~~~~~~~~~~~~~~~~~~~~~~~
```

### Details

* CodeceptJS version: 2.6.10
* NodeJS Version: 14.11.0
* Operating System: Windows 10

**Comment by vdhpieter** [comment]
@DavertMik @PeterNgTr Is this something that could be looked at? If you point me to the right direction I would be open to make a PR!

**Comment by PeterNgTr** [comment]
Hi @vdhpieter contribution is always welcome 🙏

**Comment by vdhpieter** [comment]
@PeterNgTr Ok, I took a quick look around the library and couldn't find where the typings are defined, are they generated? If so based on what?

**Comment by PeterNgTr** [comment]
@vdhpieter i guess the types are generated by jsdocs

![image](https://user-images.githubusercontent.com/7845001/126653660-f667f3c3-c662-4de4-9bed-e9922354b120.png)

**Comment by vdhpieter** [comment]
@PeterNgTr I made a PR but for some reason my JSDoc is not correct although every resource I check does it in the exact same way... Could you maybe have a look?

**Comment by PeterNgTr** [comment]
@vdhpieter did you run npm run docs to generate the docs? I guess you miss that part.

**Comment by vdhpieter** [comment]
@PeterNgTr I tried that but because detox won't install it's not working :( Secondly I also get this error:
```
ERROR: Unable to parse a tag's type expression for source file /Users/pieter/Repos/CodeceptJS/docs/build/REST.js in line 74 with tag title "returns" and text "{import('axios').AxiosResponse}": Invalid type expression "import('axios').AxiosResponse": Expected "!", "=", "?", "[]", "|", or end of input but "(" found.
```

**Comment by vdhpieter** [comment]
So I managed to install the packages and I think I was trying something impossible. using the typing from Axios in the JSDoc. So for now I just made it return a `Promise<any>` which is not perfect but already better than just `void`
