### ISSUE TITLE
Long lived secondary sessions

### ISSUE THREAD

**Issue by CRidge** [codeceptjs/CodeceptJS#2591]
#### What are you trying to achieve?
Trying to get a secondary session to live longer than a single test.

Many of our tests are on the form: Do something in application 1, see that something changes in application 2. To verify this, we use multiple sessions. The main window lives through several tests, which saves us going through a time consuming init process for each test. 

It would be great to have this possibility also for secondary sessions - let them live between tests.

#### What do you get instead?
Secondary sessions are torn down between each test and will need to re-init for each new test.

### Details
Looking at [session.js](https://github.com/codeceptjs/CodeceptJS/blob/master/lib/session.js):

```js
    event.dispatcher.once(event.test.after, () => {
      recorder.add('close session browsers', closeBrowsers);
    });
```

The session seems to be hard coded to be torn down after each test. It would be very useful to be able to configure somehow which event should cause it to be torn down: `event.test.after`, `event.suite.after` or possibly `event.global.after`.

* CodeceptJS version: 2.6.8
* NodeJS Version: 12.16.1
* Operating System: Windows 10
* puppeteer || webdriverio || protractor || testcafe version (if related): Puppeteer 5.2.1
* Configuration file: keepBrowserState and keepCookies are true - restart is false.

**Comment by DavertMik** [comment]
yeah, better not change this. You can create start a session in a helper and close it there if you need it
