### ISSUE TITLE
Add "playwright" in the list in readme

### ISSUE THREAD

**Issue by vivekbwaj** [codeceptjs/CodeceptJS#2594]
I would recommend adding 'playwright' to the list in section "CodeceptJS uses Helper modules to provide actions to I object. Currently CodeceptJS has these helpers:"
As playwright is an upcoming promising tool and I believe the repo has support for it, it could be made conspicuous by mentioning it in the readme

**Comment by PeterNgTr** [comment]
@vivekbwaj we added this :)
