### ISSUE TITLE
I am new to codeceptjs, Have used other open source a lot. please help me with my problem

### ISSUE THREAD

**Issue by suryap666** [codeceptjs/CodeceptJS#2625]
I am creating a generic function to verify the table

 async verifyTableContents(selectorOfTheTable, inputJsonArray, expectedRowNumber = null) {}   ===> something like this

**I got the table element**
const browser = this.helpers["WebDriver"];
const table = await browser._locateFields(selectorOfTheTable);

**Now how should I get the element of the element, like table header**
const tableHeaders = await table[0]._locate(`//th`);

I tried findElements('xpath', '//something')   ===> did not return the proper element back, It just has the element ID.

Please help me

**Comment by DavertMik** [comment]
after you received `table[0]` you should be able to operate with it as with any webdriverio elements. Probably your syntax can be:

```
table[0].$('//th')
```  

or something like that. 

This exposes webdriverio API so please check there:
https://webdriver.io/docs/api/element/$.html
