### ISSUE TITLE
waitForClickable doesn't take the waitForTimeout value in config file

### ISSUE THREAD

**Issue by IanHong66** [codeceptjs/CodeceptJS#2637]
#### What are you trying to achieve?

Set 'waitForTimeout' in config file, so I don't need to specify timeout in every wait* functions.

#### What do you get instead?

I find 'waitForTimeout' value is taken by waitForText, waitForVisible, waitForInvisible, waitForElement, waitForFunction but it's NOT taken by waitForClickable. For example, I set 'waitForTimeout' in config file as 5000 and one web element only becomes clickable after 2 seconds. If I use 

waitForClickable(locator);

script will fail, because it's using default timeout as 1 second instead of taking the config value of 5000 (ms).

But once I change the function to

waitForClickable(locator, 5);

script passes. That means waitForClickable(locator) doesn't take the 'waitForTimeout' value set in config file as the other wait* functions do.

### Details

* CodeceptJS version: v3.0.0
* NodeJS Version: v14.13.1
* Operating System: windows 10
* puppeteer || webdriverio || protractor || testcafe version (if related): webdriverio 3.141.59
* Configuration file:

```  helpers: {
      WebDriver: {
      url: process.env.BASE_URL_M2,
      browser: process.env.BROWSER || 'chrome',
      windowSize: "maximize",
      waitForTimeout: 5000,
      ......
      }
    }
```

**Comment by PeterNgTr** [comment]
hey @IanHong66 that works for me.

<img width="946" alt="Screenshot 2020-10-29 at 13 00 31" src="https://user-images.githubusercontent.com/7845001/97567006-e7610600-19e6-11eb-9906-f3abeaac95cb.png">

**Comment by IanHong66** [comment]
thank you @PeterNgTr . Yes you are right. I wrote a simple test and verified it did wait for 'waitForTimeout' milli seconds. My original script didn't work probably because js is not fully loaded yet. So that element was clickable but didn't trigger following actions. Please close this ticket. Thanks.
