### ISSUE TITLE
Ideas - online report

### ISSUE THREAD

**Issue by rebajz** [codeceptjs/CodeceptJS#2640]
I know  this your page.: https://codecept.io/reports/

I use allure report. 

I have some ideas, but I am not very good programmer, maybe some people help... (as @DavertMik, @PeterNgTr, @Vorobeyko, @pablopaul, others) 

It is possible each step (results) from codeceptjs save to some json file immediately when is executed? Why? When yes, probably is possible use Elastic search and Kibana for online test reports and more... By this way is possible see online report, when is something wrong with run tests, user not lost results...

Maybe is possible use json files from allure report, but allure convert all json files to report, when all tests are done.

Maybe is possible use some library from npm, or do new plugin for codeceptjs.

**Comment by PeterNgTr** [comment]
hey @rebajz there is https://www.npmjs.com/package/@reportportal/agent-js-codecept . Have you tried this? :)

**Comment by rebajz** [comment]
@PeterNgTr Before few hours, yes, :-)
