### ISSUE TITLE
CodeCeptJS is not running when execute  "npm run codeceptjs:demo" for first time installing CodeCeptJS

### ISSUE THREAD

**Issue by nhathau** [codeceptjs/CodeceptJS#2642]
#### What are you trying to achieve?
Run test with :
npm run codeceptjs:demo
#### What do you get instead?
`TypeError: Cannot set property id of #<Test> which has only a getter
    at C:\Skeleton2\node_modules\codeceptjs\lib\mochaFactory.js:53:46
    at Array.forEach (<anonymous>)
    at Suite.eachTest (C:\Skeleton2\node_modules\mocha\lib\suite.js:438:14)
    at C:\Skeleton2\node_modules\mocha\lib\suite.js:440:11
    at Array.forEach (<anonymous>)
    at Suite.eachTest (C:\Skeleton2\node_modules\mocha\lib\suite.js:439:15)
    at Mocha.mocha.loadFiles (C:\Skeleton2\node_modules\codeceptjs\lib\mochaFactory.js:53:21)
    at Mocha.run (C:\Skeleton2\node_modules\mocha\lib\mocha.js:970:10)
    at C:\Skeleton2\node_modules\codeceptjs\lib\codecept.js:170:15
    at new Promise (<anonymous>)

Cannot set property id of #<Test> which has only a getter`

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.0.0
* NodeJS Version: 14.15.0.
* Operating System: Window 10
* Configuration file:

```js
# {
    "name": "codeceptjs-tests",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "codeceptjs": "codeceptjs run --steps",
        "codeceptjs:headless": "HEADLESS=true codeceptjs run --steps",
        "codeceptjs:ui": "codecept-ui --app",
        "codeceptjs:demo": "codeceptjs run --steps -c node_modules/@codeceptjs/examples",
        "codeceptjs:demo:headless": "HEADLESS=true codeceptjs run --steps -c node_modules/@codeceptjs/examples",
        "codeceptjs:demo:ui": "codecept-ui --app  -c node_modules/@codeceptjs/examples"
    },
    "devDependencies": {
        "@codeceptjs/configure": "^0.6.0",
        "@codeceptjs/examples": "^1.2.1",
        "@codeceptjs/ui": "^0.4.2",
        "codeceptjs": "^3.0.0",
        "playwright": "^1.5.2"
    }
}
```

**Comment by PeterNgTr** [comment]
please upgrade to codeceptjs 3.0.1

**Comment by nhathau** [comment]
thanks @PeterNgTr , my issue is fixed
