### ISSUE TITLE
[Feature request] Run scenarios in a feature by mentioning line numbers 

### ISSUE THREAD

**Issue by VaasRamsay** [codeceptjs/CodeceptJS#2645]
#### Proposal
Ability to run scenarios by mentioning `feature_path:line_number`. This is a pretty common usecase in Cucumber.Js and would be very useful to have this feature. 

Config should accept list of scenarios like this -
```js
"gherkin": {
  "features": [
    "./features/home.feature:12",
    "./features/home.feature:41",
    "./features/search.feature:23",
  ],
  ...
}
```

**Comment by SamBreaksThings** [comment]
@DavertMik I'm happy to raise a PR if you're cool with introducing this feature. WDYT?

**Comment by DavertMik** [comment]
@VaasRamsay if you are still here PR is still appreciated
however, I better close this issue to not have it stuck
