### ISSUE TITLE
Playwright headless mode throwing error

### ISSUE THREAD

**Issue by lucasbit** [codeceptjs/CodeceptJS#2646]
#### What are you trying to achieve?
Run demo script or my script in headless mode using command from docs: "npm run codeceptjs:headless " (normal mode works fine). Problem occurs with Chromium and Firefox
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.
**error**: _"'HEADLESS' is not recognized as an internal or external command,
operable program or batch file."_

* CodeceptJS version: 3.0.1
* NodeJS Version: 12.19.0
* Operating System: Windows
* puppeteer || webdriverio || protractor || testcafe version **Playwright with Chromium and Firefox**
![image](https://user-images.githubusercontent.com/29520131/97688487-7d099d80-1a9a-11eb-9d85-a2025937f0ab.png)
![image](https://user-images.githubusercontent.com/29520131/97688549-8c88e680-1a9a-11eb-94c7-f4e975726964.png)

**Comment by SamBreaksThings** [comment]
Can you comment out `setHeadlessWhen` and change the `show` flag under `helpers` section to `false`? 
```js
  helpers: {
    Playwright: {
      url: "http://localhost",
      show: false,
      browser: 'chromium'
    }
  },
```

**Comment by lucasbit** [comment]
Thanks for the quick reply @SamBreaksThings.

That has fixed the issue. Thanks
