### ISSUE TITLE
REST helper: Global axios instance gets mutated

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/CodeceptJS#2652]
[Here](https://github.com/codeceptjs/CodeceptJS/blob/10e86bebfd731817e2f2cbe12d5184224c6f818d/lib/helper/REST.js#L53) the global axios instance gets mutated, this leads to an ugly error, when another module depends on the axios defaults like the `node-slack-sdk` does. See [this issue](https://github.com/slackapi/node-slack-sdk/issues/1088#issuecomment-683510886) for reference.

The error then is `TypeError: Cannot convert undefined or null to object at new WebClient (.../node_modules/@slack/web-api/dist/WebClient.js:110:44)`

Please advice how to move this from a global mutation to a local mutation so we are compatible with third party modules.

**Comment by ranendelman** [comment]
Hi @pablopaul, did you manage to resolve the issue? Trying to use the `@slack/web-api` and getting the same error `TypeError: Cannot convert undefined or null to object at new WebClient`,
Thanks.

**Comment by pablopaul** [comment]
@ranendelman this should be fixed within CodeceptJS version 3.0.4 - please try to upgrade or use [this workaround](https://github.com/pablopaul/codeceptjs-slack-reporter#usage-with-codeceptjs-rest-helper) if you cant. Hope this helps.
