### ISSUE TITLE
How to use getFileContents function ? Need more documentation

### ISSUE THREAD

**Issue by MathieuNo** [codeceptjs/CodeceptJS#2653]
#### What are you trying to achieve?

I'm trying to use the getFileContents function to get the content of a PDF file. 
I read Codecept documentation but it's very short and without an example. Hard to understand how to use this function.

#### What do you get instead?

When I run my test, the output is : 

```bash
I.getFileContents is not a function
```

My test is :

```js
    I.handleDownloads()
    I.click("Exporter")
    I.amInPath('logs/downloads')
    let filename = 'myfile.pdf'
    I.seeFileNameMatching(filename)
    let contentFile = await I.getFileContents(filename)
    I.say(contentFile)
```

### Details

* CodeceptJS version: 2.6.11
* NodeJS Version: v13.10.1
* Operating System: W10
* puppeteer

**Comment by Georgegriff** [comment]
This looks to be a documentation bug, there is no publically exposed method named getFileContents. 

https://codecept.io/helpers/FileSystem/#seeinthisfile may help.

If you want to get file contents you could write a custom helper that works with the node fs module.



Custom helper docs:

https://codecept.io/helpers/#extending-codeceptjs-with-custom-helpers
