### ISSUE TITLE
Update CodeceptJS version on docker hub

### ISSUE THREAD

**Issue by VikentyShevyrin** [codeceptjs/CodeceptJS#2654]
#### What are you trying to achieve?
I want to pull CodeceptJS 3.XX from docker hub by using ```docker pull codeception/codeceptjs:3.0.0```
#### What do you get instead?
`manifest for codeception/codeceptjs:3.0.0 not found`
The latest version of CodeceptJS on https://hub.docker.com/r/codeception/codeceptjs is 2.6.4.

### Details

* CodeceptJS version: 3.0.0
* NodeJS Version: 13.8.0
* Operating System: Windows

**Comment by parikshithk** [comment]
same issue here! now going back to 2.6.4 :|

**Comment by jlcityofglass** [comment]
Same issue here! Pump!

**Comment by VikentyShevyrin** [comment]
Fixed in 3.0.5 https://hub.docker.com/r/codeceptjs/codeceptjs
