### ISSUE TITLE
how to modify the desired capability inside the test case for Appium Helper

### ISSUE THREAD

**Issue by spoo-ui** [codeceptjs/CodeceptJS#2657]
#### What are you trying to achieve?
I am using appium with codeceptjs. As a requirement, I need to modify the device(mobile simulator) as per the test step given in BDD(test data). 
Given I load config for "Device1" where Device1 has udid FAY5ZDU48DR85SR4

below is the way im trying to change the config.
    let newconfig = { helpers: { Appium: {
        platform: "Android",
        desiredCapabilities: {
            "udid" :  "FAY5ZDU48DR85SR4"
        } 
    }}}
config.append(newconfig) 
the config modifies the udid but is not refreshed/loaded in that test case. Next test case the desired device(udid) is connected. 
If same code is used in hook with event.suite.before/event.test.before it works. but i need to modify in test case

Can anybody please help?

Also in Appium is there way to add mutliple devices to Appium helper? I have test case where 2 mobile phones are needed simultaneously.

### Details

Using  codecept with Appium
* Configuration file: Initial value
exports.config = {
  output: './output',
  helpers: {
    Appium: {
      required: './pages/desiredCap.js',
      platform: "Android",
      restart: true,
      desiredCapabilities: {
        platformVersion: "11",
        udid: "emulator-5554"
    }
    }
  },

need to modify/add udids to connect desired device

**Comment by idxn** [comment]
I think you could access config object with
```javascript
let config = this.helpers['Appium'].config
`

**Comment by spoo-ui** [comment]
> I think you could access config object with
> 
> ```js
> let config = this.helpers['Appium'].config
> ```

I can copy the config and modify. But How to do I restart the session( may be AppiumDriver.createSession() ) so that new device/config is taken.

**Comment by idxn** [comment]
@spoo-ui Set configuration manualStart to true and use `this.helpers["Appium"]._startBrowser()` to manually open the application. Appium helper is inherit from webdriver helper so sometimes you might take a look on webdriver helper doc for some valuable clues.
https://codecept.io/helpers/WebDriver/#configuration

**Comment by spoo-ui** [comment]
@idxn thanks for your help.. it solved my problem. I used startBrowser without manualStart as manualStart is not working in latest version. I saw few people already reported the issue and waiting for fix..
