### ISSUE TITLE
[Question] Why the browser not setting up basic auth credentials when using restart: true

### ISSUE THREAD

**Issue by golfzaptw** [codeceptjs/CodeceptJS#2659]
I set config like this and then I use command `yarn codeceptjs run-workers 3 --grep parallel`
Why CodeceptJS restart the browser and not set basic auth when starting a new window?

```
let playwrightConfig = {
    url: `${process.env.SITE_URL}/${process.env.SITE_LANGUAGE}`,
    show: true,
    restart: true,
    basicAuth: {
        username: process.env.USERNAME_HOST,
        password: process.env.PASSWORD_HOST,
    },
    waitForNavigation: 'load',
    waitForTimeout: 30000,
    getPageTimeout: 60000,
    waitForAction: 500,
    browser: 'chromium',
}
```

### Details

* CodeceptJS version: v3.0.1
* NodeJS Version: v12.14.1
* Operating System: OSX v 10.15.7
* playwright version: v1.5.2

**Comment by idxn** [comment]
@golfzaptw From the code, playwright helper will set the basic authentication only if there is a amOnPage step called

https://github.com/codeceptjs/CodeceptJS/blob/1c02e9e96e0cbb566b1c6b336cd4127d6e600991/lib/helper/Playwright.js#L644

Therefore, you might need to call the amOnPage for each of the test.

Another approach is to make a PR to set the basic authen in the _startBrowser() instead.

**Comment by golfzaptw** [comment]
@idxn As far as I see, this function is not set `isAuthenticated` to false after all step is done and close browser then I use amOnPage it not set credentials because conditions are `this.isAuthenticated !== true` 

https://github.com/codeceptjs/CodeceptJS/blob/1c02e9e96e0cbb566b1c6b336cd4127d6e600991/lib/helper/Playwright.js#L320

**Comment by idxn** [comment]
@golfzaptw You may try setting isAuthenticated manually somewhere.
`this.helpers["Playwright"].isAuthenticated=false`

**Comment by golfzaptw** [comment]
@idxn thank you so much for clarifying
