### ISSUE TITLE
Demo not working with Puppeteer

### ISSUE THREAD

**Issue by MickaelTH** [codeceptjs/CodeceptJS#2664]
#### What are you trying to achieve?
Followed the tutorial on this page https://codecept.io/puppeteer/#setup

#### What do you get instead?
Clickable element "Sign in" was not found inside element //html/body/div[1]/header

> Provide console output if related. Use `--verbose` mode for more details.

```bash
I am on page "https://github.com"
    I click "Sign in", "//html/body/div[1]/header"
"Clickable element "Sign in" was not found inside element //html/body/div[1]/header
  ✖ FAILED in 6735ms
```

> Provide test source code if related

```js
I.amOnPage('https://github.com');
I.click('Sign in', '//html/body/div[1]/header');
I.see('Sign in to GitHub', 'h1');
I.fillField('Username or email address', 'something@totest.com');
I.fillField('Password', '123456');
I.click('Sign in');
I.see('Incorrect username or password.', '.flash-error');
```

### Details

* CodeceptJS version: 3.01
* NodeJS Version: 10
* Operating System: Ubuntu 20.04
* puppeteer

Let me know if you need more info.

**Comment by DavertMik** [comment]
GitHub changed the design, not an issue of CodeceptJS
but docs might be updated.
