### ISSUE TITLE
throwing an error in run-rerun prevents testresults from being imported to testrail

### ISSUE THREAD

**Issue by shr2** [codeceptjs/CodeceptJS#2684]
#### What are you trying to achieve?
I want to retest failed testcases automatically using run-rerun command. The results shall be imported to testrail.
My codecept tests are very stable and many failed ones will be failing again in rerun. In that case codeceptJS is throwing an error (see line of code below) and my testrail-import addon won't get triggered. 

https://github.com/codeceptjs/CodeceptJS/blob/94aa2a857e206211649909d56dcd46af52b5265b/lib/rerun.js#L60

Could you please switch from throwing an Error to just output.error? That would work for me.

### Details

* CodeceptJS version: 2.6.11

![image](https://user-images.githubusercontent.com/17846323/99534476-bd787f00-29a7-11eb-93db-b66ccf1bd24d.png)

**Comment by DavertMik** [comment]
run-rerun was removed
