### ISSUE TITLE
I.* calls in a Before hook don't appear in the Allure xml file

### ISSUE THREAD

**Issue by crazyvan25** [codeceptjs/CodeceptJS#2689]
#### What are you trying to achieve?

I run codeceptjs with the allure plugin:

`codeceptjs run --steps --plugins allure`

I have a `Before` hook:

```js
Before(({ I }) => {
    I.amOnPage(...));
    I.setCookie(...);
    I.setCookie(...);
});
```

The 3 I.* appear in the terminal when I run the scenario.

In the Allure xml file, I am expecting to see the 3 `I.*` calls followed by the `I.*` calls in the `Scenario`.

#### What do you get instead?

The xml file only has the `I.*` calls in the `Scenario`.

### Details

* CodeceptJS version: 3.0.1
* Configuration file:

```js
exports.config = {
    tests: './tests/*.js',
    output: './output',
    helpers: {
        Puppeteer: {
            url: '',
            show: false,
            chrome: {
                args: ['--no-sandbox'],
            },
            fullPageScreenshots: true,
            uniqueScreenshotNames: true,
        },
    },
    include: {
        I: './models/actor.js',
        signInPage: './models/signIn.js',
        cookies: './models/cookies.js',
        url: './models/url.js',
    },
    bootstrap: null,
    mocha: {},
    plugins: {
        allure: {},
    },
};
```

**Comment by jancorvus** [comment]
It works if you remove all lines related to `isHookSteps` variable from codeceptjs/lib/plugin/allure.js
I had to copy the original plugin to my repo and change that way and re-include the plugin with `require` pointing to the plugin in my repo.
I am still confused why it can't be fixed likewise in the original code.
