### ISSUE TITLE
[Autocomplete] - Missing autocomplete for custom helper when there are both custom helper and steps_file 

### ISSUE THREAD

**Issue by PeterNgTr** [codeceptjs/CodeceptJS#2710]
#### What are you trying to achieve?
I would like to have autocomplete when there are both custom helper and steps_file.

#### What do you get instead?
There is an issue I'm encountering right now, in my repo, I have both `steps_file` and `custom helper`. After running `npx codeceptjs run def`, there is autocomplete for steps_file but there is not for custom helper. 

#### Sample repo?
So I updated this repo https://github.com/PeterNgTr/codeceptjs-rest-demo to replicate the issue no autocomplete for custom helper.

### Details

* CodeceptJS version: 3.0.2

**Comment by SDETDeven** [comment]
Hello @PeterNgTr ,

For me I am not getting autocomplete for both steps_file.ts  as well as custom helpers. Is there anything specific we need to setup for getting autocomplete in steps_file.ts.

Thanks,
Deven J.

**Comment by PeterNgTr** [comment]
Hi @SDETDeven did you run the codeceptjs def and in your config file you set I: 'path/to/stepFiles'?

**Comment by SDETDeven** [comment]
Hello @PeterNgTr ,

Yes I ran npx codeceptjs run def. Also I have an entry in codecept.conf.js like 
include: {
    I: './steps_file.ts',
}

**Comment by PeterNgTr** [comment]
Could you share your steps_file.ts?

**Comment by SDETDeven** [comment]
Hello @PeterNgTr ,

Please find below the sample steps_file.ts

const { actor } = require('codeceptjs');
export = function () {
  return actor({
    // Define custom steps here, use 'this' to access default methods of I.

    // login function will open signin module, enter credentials and OTP from constant.ts file for login.
    async login() {
      //Open Signin and give login credentials
      this.amOnPage('/');
      this.wait(2);
      this.click(signIn);
      this.wait(1);
}

**Comment by PeterNgTr** [comment]
Did you have tsconfig.json?

**Comment by SDETDeven** [comment]
Yes, Please find below the content of that file.

{
  "compilerOptions": {
    "target": "esnext",
    "moduleResolution": "node",
    "module": "commonjs",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"],
    "baseUrl": "./",
    "paths": {
      "@/tests": ["/tests/*"]
    },
    "types": ["node", "./steps"],
    "resolveJsonModule":true
  }
}

**Comment by PeterNgTr** [comment]
A little bit different from mine, thou

```
 
{
  "ts-node": {
    "files": true
  },
  "compilerOptions": {
    "target": "es2018",
    "lib": ["es2018"],
    "esModuleInterop": true,
    "module": "commonjs",
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
  },

````

**Comment by SDETDeven** [comment]
Hello,

Will that really matter ? Also if I change my tsconfig same as yours, will have to run some command to make the changes reflect properly ?

**Comment by PeterNgTr** [comment]
Tbh, I don't really understand TS much, that configuration is getting from codeceptjs typescript boilerplate 😀

**Comment by SDETDeven** [comment]
Hello @PeterNgTr ,

Could you please let me know how did manage to read the API response ?

const res = I.sendGetRequest("/rtos");
res.status .  --> Gives me an error message here

For me it says 'status does not exist for type Void' because sendGetRequest has return type of Void.

Is there anything specific we need to do ?

Thanks,
Deven J.

**Comment by PeterNgTr** [comment]
Hey @SDETDeven, you should use async/await to get the response. Hope this helps. 

```
const res = await I.sendGetRequest("/rtos");
```
