### ISSUE TITLE
mockRequest with WebDriver is not intercepting HTTP requests

### ISSUE THREAD

**Issue by IanHong66** [codeceptjs/CodeceptJS#2714]
#### What are you trying to achieve?
I want to use I.mockRequest with WebDriver on local HTTP mailhog webpage. Clicking 'Inbox (6)' triggers HTTP GET request to this endpoint: 'http://magento2.test:8025/api/v2/messages?limit=50'. After start mocking, if I click this 'Inbox (6)', this API request should be intercepted and '404' should be returned according to my setting:

I.amOnPage('xxx');
I.mockRequest('GET', '/api/v2/messages?limit=50', 404);
I.click('body > div > div > div.col-md-2.col-sm-3 > ul > li:nth-child(2) > a')

In Chrome browser inspector, I'm expecting a '404' response status code.

#### What do you get instead?

It always gets '200' instead of '404'. It behaves like there is no mocking at all. I did this in interactive debug mode. Screenshot is attached below:
![image](https://user-images.githubusercontent.com/29475644/101720429-b7cf0e80-3af9-11eb-8d3a-e3f546eb136b.png)

```js
 I.amOnPage('http://magento2.test:8025')
    And I should see order number text
      I am on page "http://magento2.test:8025"
 I.startMocking()
      I start mocking
 I.mockRequest('GET','/api/v2/messages*',400)
      I mock request "GET", "/api/v2/messages*", 400
 I.click('body > div > div > div.col-md-2.col-sm-3 > ul > li:nth-child(2) > a')
      I click "body > div > div > div.col-md-2.col-sm-3 > ul > li:nth-child(2) > a"
 I.mockRequest('GET','/api/v2/messages?limit=50',400)
      I mock request "GET", "/api/v2/messages?limit=50", 400
 I.click('body > div > div > div.col-md-2.col-sm-3 > ul > li:nth-child(2) > a')
      I click "body > div > div > div.col-md-2.col-sm-3 > ul > li:nth-child(2) > a"
 I.
```

### Details

* CodeceptJS version: v3.0.2
* NodeJS Version: v14.13.1
* Operating System: Windows 10
* puppeteer || webdriverio || protractor || testcafe version (if related): webdriverio v6.10.0
* Configuration file:

```js
    MockRequestHelper: {
      require: '@codeceptjs/mock-request',
    },
```
package.json:
```js
  "devDependencies": {
    "@codeceptjs/mock-request": "^0.3.0",
    "@pollyjs/adapter-puppeteer": "^5.0.0",
    "@pollyjs/core": "^5.0.0",
    "@wdio/allure-reporter": "^6.5.2",
    "@wdio/browserstack-service": "^6.10.0",
    "@wdio/cli": "^6.10.0",
    "@wdio/selenium-standalone-service": "^6.10.0",
    "codeceptjs": "^3.0.2",
    "global-agent": "^2.1.12",
    "mocha": "^8.1.3",
    "mocha-multi": "^1.1.3",
    "mochawesome": "^6.1.1",
    "mochawesome-merge": "^4.2.0",
    "mochawesome-report-generator": "^5.1.0",
    "puppeteer": "^5.5.0",
    "webdriverio": "^6.10.0"
  },
  "dependencies": {
    "chai": "^4.2.0",
    "codeceptjs-chai": "^2.2.0",
    "dotenv": "^8.2.0",
    "mocha-junit-reporter": "^2.0.0",
    "wdio-browserstack-reporter": "~0.1.1"
  }
```

**Comment by leonid-sviderskii-mtl** [comment]
I have the same issue. 

The only thing is that they say "_This helper partially works with WebDriver. It can intercept and mock requests only on already loaded page._" and don't provide any real-life example so it's kinda impossible to understand if you are doing things correctly or not.

**Comment by DavertMik** [comment]
sorry, webdriver does not support mockRequest natively so if this metod was called before request started it won't intercept request
