### ISSUE TITLE
Codeceptjs V3 - Allure Report for Gherkin is broken after V3(codeceptjs@3.0.2)

### ISSUE THREAD

**Issue by gkushang** [codeceptjs/CodeceptJS#2720]
#### What are you trying to achieve?

Create Allure Report for Gherkin but it is broken

#### What do you get instead?

Allure report for Gherkin (Given, When, Then) is broken with V3 of CodeceptJS

<img width="1356" alt="Screen Shot 2020-12-09 at 11 29 59 AM" src="https://user-images.githubusercontent.com/3663389/102021614-ec87d380-3d4e-11eb-8a91-5f6208af4743.png">

## Reproduce

```js
git clone git@github.com:salesforce/codeceptjs-bdd.git
cd codeceptjs-bdd/packages/create-codeceptjs-bdd-tests/acceptance
yarn

yarn acceptance --features
yarn acceptance:report

```

### Details

* CodeceptJS version: codeceptjs@3.0.2
* NodeJS Version: v12.19.0
* Operating System: Mac
* puppeteer || webdriverio || protractor || testcafe version (if related) ALL
* Configuration file: https://github.com/salesforce/codeceptjs-bdd/blob/develop/examples/webcomponents-playwright-webdriver-example/codecept.conf.js

**Comment by IanHong66** [comment]
I got the same problem with:

codeceptjs@3.0.2
nodejs@14.13.1

Ran a few test cases then run this command >allure serve output
the html page has no content:
![image](https://user-images.githubusercontent.com/29475644/104689393-8da2e900-5756-11eb-9856-c1bdba916ae3.png)

**Comment by gkushang** [comment]
I also see, the Steps under `Before` hooks does not display in the Allure report

**Comment by sotirispa** [comment]
It is so bad that this problem is still not solved. It is blocking us from using the codeceptjs with bdd in a proper way.

**Comment by vitaliisotnichenko** [comment]
> I got the same problem with:
> 
> codeceptjs@3.0.2
> nodejs@14.13.1
> 
> Ran a few test cases then run this command >allure serve output
> the html page has no content:
> ![image](https://user-images.githubusercontent.com/29475644/104689393-8da2e900-5756-11eb-9856-c1bdba916ae3.png)

It means that your test results can't be discovered, check that you indicate correct directory with allure results
