### ISSUE TITLE
grabValueFrom - everytime string

### ISSUE THREAD

**Issue by rebajz** [codeceptjs/CodeceptJS#2738]
Why grabValueFrom everytime return value as string?

For example, input can contains numbers, etc.

Testers who use typescript, will be like checked types in inputs...

**Comment by elaichenkov** [comment]
It's all about specifications.
For instance in [Webdriver](https://dom.spec.whatwg.org/#dom-element-getattribute), `grabValueFrom` method uses the `getAttribute` method which returns the null or string.

In [Playwright](https://microsoft.github.io/playwright/docs/next/api/class-jshandle#jshandlejsonvalue) `grabValueFrom` method uses the `getProperty` and the `jsonValue` and the last one returns a JSON representation of the object. If the object has a `toJSON` function, it will not be called.
