### ISSUE TITLE
locators in console log

### ISSUE THREAD

**Issue by rebajz** [codeceptjs/CodeceptJS#2740]
i try run test with --steps and --verbose

  await I.click({xpath: '//*[text()="Overview"]'});
  await I.click('Device Definition');
  pokus = await I.grabValueFrom({xpath: '//*[@id="definitionName"]//input'});

in console is visible this:

    I click {"xpath":"//*[text()=\"Overview\"]"}
    » [SmartWait (10000ms)] Locating {xpath: //*[text()="Overview"]} in 10000
    I click "Device Definition"
    I grab value from {"xpath":"//*[@id=\"definitionName\"]//input"}
    » [SmartWait (10000ms)] Locating [object Object] in 10000

1) In click method is added ", therefore xpath is more difficult to read (in smartWait is good)

2) In last smarWait is Locating as [object Object], not show correctly xpath

**Comment by elaichenkov** [comment]
It seems like a bug.
Possible solution is to parse `locator` object with `JSON.stringify()` method [here](https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/WebDriver.js#L720).

```diff
  async _smartWait(locator) {
-   this.debugSection(`SmartWait (${this.options.smartWait}ms)`, `Locating ${locator} in ${this.options.smartWait}`);
+   this.debugSection(`SmartWait (${this.options.smartWait}ms)`, `Locating ${JSON.stringify(locator)} in ${this.options.smartWait}`);
    await this.defineTimeout({ implicit: this.options.smartWait });
  }
```
