### ISSUE TITLE
Playwright plugin don't want to cooperate with secret()

### ISSUE THREAD

**Issue by Naimadnap** [codeceptjs/CodeceptJS#2767]
#### What are you trying to achieve?
Try to use `secret()` in fillField function in ts config

#### Error
```
LoginPage.ts:18:41 - error TS2345: Argument of type 'Secret' is not assignable to parameter of type 'string'.
```

Secret class definition from this version in `node_modules/codeceptjs/typings/types.d.ts`

```js
    class Secret {
        constructor(secret: string);
        toString(): string;
        static secret(secret: any): Secret;
    }

```

and fillField 

```js
fillField(field: CodeceptJS.LocatorOrString, value: string): void;
```

### Details

* CodeceptJS version: 3.0.4
* NodeJS Version: 12
* Operating System: macOS
* Playwright 1.7.1

**Comment by elaichenkov** [comment]
It seems the issue with types in all helpers, not only in playwright because the `fillField` takes only `string` value when the `secret` method returns an instance of the `Secret` class.
