### ISSUE TITLE
Axios dependency with high vulnerability issue

### ISSUE THREAD

**Issue by AlexandreBoliveira87** [codeceptjs/CodeceptJS#2779]
In our company, we had to solve all alerts in npm audit and axios is the only that we could not solve since its a fixed dependency from codeceptjs, please update to the latest version, more details on Axios problem:

https://www.npmjs.com/advisories/1594

Thank you!

**Comment by sgarfinkel** [comment]
This was resolved via https://github.com/codeceptjs/CodeceptJS/pull/2746 and can be closed.
