### ISSUE TITLE
Allow to use `--grep` with dry-run

### ISSUE THREAD

**Issue by damian-zygmuntowicz-siili** [codeceptjs/CodeceptJS#2787]
During development, I use often tag @WIP to run only one test for debugging. 

I would to like check before commit if all WIP tags are deleted from the code.

**Comment by PeterNgTr** [comment]
hey @damian-zygmuntowicz-siili my approach is using `Scenario.only ` to debug a test, then using this https://www.npmjs.com/package/eslint-plugin-codeceptjs as pre commit hook of git to avoid committing the `Scenario.only`

**Comment by damian-zygmuntowicz-siili** [comment]
@PeterNgTr I try this but VS code shows in red what annoys me personally. Is any solution to disable this for vscode and run in precommit (I use husky)

**Comment by PeterNgTr** [comment]
hey @PeterNgTr my VS code working fine. I don’t see any error.
<img width="189" alt="Screen Shot 2021-01-29 at 2 26 44 PM" src="https://user-images.githubusercontent.com/7845001/106280340-141ef680-623e-11eb-88bb-4e7cbc983c58.png">

**Comment by damian-zygmuntowicz-siili** [comment]
I see this
![image](https://user-images.githubusercontent.com/39622070/106287861-99f36f80-6247-11eb-89bd-e25af2b8345f.png)

**Comment by PeterNgTr** [comment]
hey @damian-zygmuntowicz-siili 

here is my eslintrc and it's working fine.

```
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "eslint-plugin-codeceptjs"],
  "rules": {
    "@typescript-eslint/no-var-requires": 0,
    "codeceptjs/no-skipped-tests": 1
  },
  "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended", "plugin:codeceptjs/recommended"]
}
```
![Screen Shot 2021-02-01 at 11 34 07 AM](https://user-images.githubusercontent.com/7845001/106447135-6a2fac00-6481-11eb-973f-28c8dc611ea8.png)

**Comment by damian-zygmuntowicz-siili** [comment]
Still this same because VSC in my config use eslint in realtime so I need to have separate conf. I wrote one line script and add it to pre-commit so it works in my case (unix system) but still, it would be nice to have this in dry-run 

here is my WIP-checker `npx codeceptjs --config ./config/codecept.conf.js dry-run | grep '@WIP' && exit 1 || exit 0`
