### ISSUE TITLE
TypeScript: wrong type definition for `Locator.addFilter`

### ISSUE THREAD

**Issue by danielrentz** [codeceptjs/CodeceptJS#2794]
#### What are you trying to achieve?
Use basic functionality like class `Locator` in TypeScript

#### What do you get instead?
Cannot use `Locator.addFilter()` because types.d.ts defines it as function without parameters.

Furthermore I noticed that most Locator methods are not documented at all.

Am I right that the type definitions are auto-generated from JSDoc comments?

### Details
* CodeceptJS version: 3.0.4

**Comment by PeterNgTr** [comment]
Hey @danielrentz , yeah. I think you're right. The definition is generated from jsdocs.

**Comment by danielrentz** [comment]
Hi @PeterNgTr I would like to provide a PR with documentation for the `Locator` class. What is the workflow to generate the type definitions? Manually generate and commit, or is there some automation somewhere?
