### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by pavelloz** [codeceptjs/CodeceptJS#2816]
#### What are you trying to achieve?

Im trying to see if codecept is a valid alternative for testcafe, by going through getting started documentation but i got stuck on first command, then on second command from docs.

#### What do you get instead?

Im trying to generate some example, because `codeceptjs run --steps`  or `codeceptjs run my_test.js` does not run anything for me.

```bash
➜  lol git:(master) ✗ npx codeceptjs generate:test
Creating a new test...
----------------------
Cannot read property 'match' of undefined
➜  lol git:(master) ✗ node -v
v14.4.0
```

> Provide test source code if related

### Details

* CodeceptJS version: 3.05
* NodeJS Version: 14.4.0
* Operating System: mac os 10.14.6
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file: none

**Comment by PeterNgTr** [comment]
Yeah, there is understandable that this is an open source not commercial one, thus everyone's contributions are in their free time. I'm still using codeceptjs and working fine from my end. :).

**Comment by pavelloz** [comment]
Yeah im pretty sure once you know it its good, but learning curve is where it lies when it comes to adoption/switching from a different solution. API looks very promising, but if i cant get to API phase, it doesnt matter ;)

**Comment by PeterNgTr** [comment]
Aha, I'm coming from different frameworks thou! I was using many before landing on codeceptjs. :)

**Comment by DavertMik** [comment]
@pavelloz yeah, If a project was not released in 24 hours it may be considered abandoned 

https://www.theolognion.com/npm-now-marks-packages-as-abandoned-after-24h-since-the-last-commit/

According to error, you seem to have a broken config. Try to rerun `npx codeceptjs init` script in a fresh directory

Join our Slack for such kind of questions. 

http://bit.ly/chat-codeceptjs

**Comment by pavelloz** [comment]
Usually unmaintained docs mean unmaintained project, because noone reports / fixes bugs in it, especially in getting started.

**Comment by SamBreaksThings** [comment]
@pavelloz Probably not a healthy comment on open-source communities. If you want to see if a project is maintained or not, PTAL at the forums and community discussions, especially recent activity. By that scale, CodeceptJS is very much maintained. Also, contribution is very much welcome from anyone, meaning if you see something broken, feel free to raise a PR. Lastly, it's highly unlikely that something basic is broken given that its used by thousands of people. Happy testing :)
