### ISSUE TITLE
[Appium] lexical error when using ids in locator builder

### ISSUE THREAD

**Issue by akapitoha** [codeceptjs/CodeceptJS#2825]
#### What are you trying to achieve?
I try to use element's resource id in locator builder
smth like
`locate('#some.sample.app:id/someId').withText("text")`

#### What do you get instead?

I get
```
Error: Lexical error on line 1. Unrecognized text.
```

though it works fine via xpath `locate("//*[@resource-id='some.sample.app:id/someId']").withText("text")`

### Details

* CodeceptJS version: 3.0.5
* NodeJS Version: 14.15.2
* Operating System: Mac OS Mojave
* webdriverio

**Comment by DavertMik** [comment]
I don't think locator builder works good with Appium
In Appium XPath may not work correctly
