### ISSUE TITLE
Q: Why doesn't version 3.x expose re-rerun command anymore?

### ISSUE THREAD

**Issue by runlevel5** [codeceptjs/CodeceptJS#2828]
In version 2.4 to 2.6, I could access the re-run via the public interface of CLI `npx codeceptjs run-rerun`. However in version 3.x, that command is removed yet there is no mention about this breaking changes in CHANGELOG or Upgrade Guide.

I would like to ask what is the replacement functionality for rerun in 3.x? Many thanks in advance

**Comment by ruudvanderweijde** [comment]
See https://github.com/codeceptjs/CodeceptJS/issues/2670

**Comment by runlevel5** [comment]
Closed in favour of #2670
