### ISSUE TITLE
amOnPage truncate the long URL

### ISSUE THREAD

**Issue by linjin-harvey** [codeceptjs/CodeceptJS#2831]
I'm trying to open a long url (365 col), but amOnPage truncate the URL. 
Not only truncate the url on my console but also on automated browser, so the truncated URL cannot render the page correctly
my code is simply as below, fastApply url is : https://www.cm.eheaffhmedicareplans.com/ehi/muse-service/quick-apply?allid=4345345&zip=90001&county=LOS+ANGELES&carrierId=342342&planId=t55&campaign=ehmp_plancomparemulti_v3&token=cb1ec99e-a5ba-4be8-94fb-454564564&reqdate=04/01/2021&padate=&pbdate=&requestFrom=PPE&aoseSessionId=2088852&salesRep=glorihong-1512970546610&type=MA&gender=M&smoker1=n&segmentId=000
```js
  I.amOnPage(ppeLinks.fastApply);
```

![image](https://user-images.githubusercontent.com/16532219/110087807-17724880-7dcf-11eb-8958-35d51928a2f0.png)

**Comment by linjin-harvey** [comment]
The url attached above is not right one since I don't want to showing the company url in open platform. The key is amOnPage truncate the url

**Comment by DavertMik** [comment]
@linjin-harvey what backend do you use? 
I'm pretty sure we pass the string value as it is. So maybe the receiving driver is cutting the URL.
