### ISSUE TITLE
Codeceptjs called from Jenkins not working correctly

### ISSUE THREAD

**Issue by rebajz** [codeceptjs/CodeceptJS#2839]
1) I create folder c:\desktop automation
2) in this folder i install codeceptjs (npx create-codeceptjs .)
3) i do codecept init (npx codeceptjs init)
4) i create first demo test (demo_test.js)

Demo test contains:
Feature('Only try functionality');

Scenario('Visit page', ({ I }) => {
    I.amOnPage('https://www.google.com/');
    I.wait(5);
});

5) I go to cmd, and visiting folder c:\desktop automation
6) I call node_modules\.bin\codeceptjs run .\demo_test.js --steps
7) now i see:
C:\desktop automation>node_modules\.bin\codeceptjs run .\demo_test.js --steps
CodeceptJS v3.0.5
Using test root "C:\desktop automation"

Only try functionality --
  Visit page
    I am on page "https://www.google.com/"
    I wait 5
  √ OK in 10432ms

  OK  | 1 passed   // 13s

C:\desktop automation>

I have installed in same machine locale jenkins (only with green ball plugin). In this jenkins i have job: 02runDemoCodeceptProject

This job is very simple, contains only build option: execute Windows batch command with this:
cd "c:\desktop automation"
node_modules\.bin\codeceptjs run .\demo_test.js --steps

When i run this job, i see in console log this problem:
Running as SYSTEM
Building in workspace C:\Windows\system32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\02runDemoCodeceptProject
[02runDemoCodeceptProject] $ cmd /c call C:\Windows\TEMP\jenkins8634734597980877900.bat

C:\Windows\system32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\02runDemoCodeceptProject>cd "c:\desktop automation" 

c:\desktop automation>node_modules\.bin\codeceptjs run .\demo_test.js --steps 
CodeceptJS v3.0.5
Using test root "c:\desktop automation"

Only try functionality --

  × "before all" hook: codeceptjs.beforeSuite for "Visit page" in 418ms
Error: browserType.launch: Failed to launch chromium because executable doesn't exist at C:\Windows\system32\config\systemprofile\AppData\Local\ms-playwright\chromium-854489\chrome-win\chrome.exe
Try re-installing playwright with "npm install playwright"

-- FAILURES:

  1) Only try functionality
       "before all" hook: codeceptjs.beforeSuite for "Visit page":
     browserType.launch: Failed to launch chromium because executable doesn't exist at C:\Windows\system32\config\systemprofile\AppData\Local\ms-playwright\chromium-854489\chrome-win\chrome.exe
Try re-installing playwright with "npm install playwright"
  rror
      at Object.captureStackTrace (node_modules\playwright\lib\utils\stackTrace.js:48:19)
  
  

  FAIL  | 0 passed, 1 failed   // 425ms
Run with --verbose flag to see complete NodeJS stacktrace
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE

**Comment by rebajz** [comment]
I try switch helper to webdriverio, and this working correctly in jenkins.
Running as SYSTEM
Building in workspace C:\Users\info\AppData\Local\Jenkins\.jenkins\workspace\pokus
[pokus] $ cmd /c call C:\Users\info\AppData\Local\Temp\jenkins4542990666704241256.bat

C:\Users\info\AppData\Local\Jenkins\.jenkins\workspace\pokus>cd "c:\desktop automation" 

c:\desktop automation>node_modules\.bin\codeceptjs run .\demo_test.js 
CodeceptJS v3.0.5
Using test root "c:\desktop automation"

Only try functionality --

  √ Visit page in 9781ms

  OK  | 1 passed   // 36s
Finished: SUCCESS

**Comment by rebajz** [comment]
maybe important info: win10 (64bit 20H - last version), nodejs 14.16.0 64 bit. Installed jenkins: Jenkins 2.277.1

**Comment by DavertMik** [comment]
no idea, looks like Playwright issue
see their troubleshooting
