### ISSUE TITLE
allow multiple test files as arguments to concept run / run-workers

### ISSUE THREAD

**Issue by nicko-winner** [codeceptjs/CodeceptJS#2853]
#### What are you trying to achieve?
Would like to run multiple test files at one time as arguments to codeceptjs run / run-workers

#### What do you get instead?
`codecept run myTest1.js myTest2.js` - as of today codecept will only run myTest1.js and will not run multiple files.

> Provide test source code if related
https://github.com/codeceptjs/CodeceptJS/blob/3.x/bin/codecept.js#L85 would be nice if it took more than one test as an argument.

### Details
CircleCI allows you split tests between build executors however codecept does not have an easy to to pass a list of files to codecept to run / run-workers. Related circle CI docs: https://circleci.com/docs/2.0/parallelism-faster-jobs/#using-the-circleci-cli-to-split-tests . It would be nice if one could specify a group of files to run tests on via the command line without needing a custom runner.

**Comment by nicko-winner** [comment]
my current workaround: in my circleCI YAML
``` sh
    # Split tests across circleCI execurtors
    # https://circleci.com/docs/2.0/parallelism-faster-jobs/#using-the-circleci-cli-to-split-tests
    export TESTS_TO_RUN=$(circleci tests glob 'tests/**/*/test_smoke.js' | circleci tests split)
    # add suffix to test files that we can match with our codecept.js config ie: tests: './tests/**/*/*RUNME.js'
    for file in $TESTS_TO_RUN;
      do cp $file `echo $file | sed 's/\(.*\.\)js/\1_RUNME.js/'`; done
```

**Comment by DavertMik** [comment]
User `--grep` for that and Feature titles to grep by.
