### ISSUE TITLE
Using mocha-junit-reporter with run-workers

### ISSUE THREAD

**Issue by karoletrych** [codeceptjs/CodeceptJS#2861]
#### What are you trying to achieve?
Running tests using multiple workers `codeceptjs run-workers 5` and using mocha-junit-reporter .

```
  mocha: {
    "reporterOptions": {
        "mochaFile": "output/result.xml"
    }
  }
```

#### What do you get instead?
Result file is overwritten by last test which was executed.

I tried adding [hash] as stated in mocha-junit-reporter Readme:
```
mocha: {
    "reporterOptions": {
        "mochaFile": "output/result.[hash].xml"
    }
  },
```
But when i do that output xml isn't generated at all.

### Details
* CodeceptJS version: 3.0.6
* mocha-junit-reporterversion: 2.0.0
* NodeJS Version: v14.16.0
* Operating System: Windows 10
* playwright: 4.2.3

**Comment by karoletrych** [comment]
Nevermind, forgotten about --reporter mocha-junit-reporter when testing the [hash] version 😅

**Comment by ngraf** [comment]
Thanks for the indirect tip with "[hash]". That is what I was looking for!
