### ISSUE TITLE
Weird error message when running simple tests with codeceptjs ui instead of CLI reporter

### ISSUE THREAD

**Issue by shapeshifta78** [codeceptjs/CodeceptJS#2865]
#### What are you trying to achieve?

I would like to run my tests with the codeceptjs ui. CLI is running fine already. I just started and have created some basic tests that open a page.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
 Cannot set property 'id' of undefined
      at RealtimeReporterHelper._emitMetaStepChangedIfNecessary (node_modules/@codeceptjs/ui/lib/codeceptjs/realtime-reporter.helper.js:266:29)
      at /home/tom/Projects/fl-frontend/test-e2e/node_modules/@codeceptjs/ui/lib/codeceptjs/realtime-reporter.helper.js:135:14

```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: latest
* NodeJS Version: 12
* Operating System: Ubuntu 18
* Configuration file:

```js
# default config used
```

**Comment by ydmitry** [comment]
Have the same error with latest CodeceptJS version

**Comment by arturslogins** [comment]
Any progress on this issue?

**Comment by ydmitry** [comment]
Seems fix was done, but not released yet (too long to wait, please release)
https://github.com/codeceptjs/ui/pull/119
