### ISSUE TITLE
Want to see a GUI browser's behavior during running the test

### ISSUE THREAD

**Issue by hon9g** [codeceptjs/CodeceptJS#2880]
#### What are you trying to achieve?

Want to see a GUI browser's behavior during running the test.

#### What do you get instead?
Logs shows well, But I can not see the GUI browser working.

> Provide console output if related. Use `--verbose` mode for more details.

`$ codeceptjs run --debug`
```bash
# paste output here
CodeceptJS v3.0.6
Using test root "/tests"
Helpers: Puppeteer
Plugins: screenshotOnFail, retryFailedStep, tryTo

LiveCommercePocWidget --
  hello
    I am on page "/"
    › [Url] http://app:3000/
    › [Browser:Warning] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
    › [Browser:Log] [Fast Refresh] rebuildingJSHandle:[Fast Refresh] rebuilding
    I see "NAP"
  ✔ OK in 1897ms


  OK  | 1 passed   // 3s
```

> Provide test source code if related

```js
// paste test
Feature("LiveCommercePocWidget");

Scenario("hello", ({ I }) => {
  I.amOnPage(`/`);
  I.see("NAP");
});
```

### Details

* CodeceptJS version: 3.0.6
* NodeJS Version: v14.16.0 
* Operating System: NAME="Ubuntu" VERSION="18.04.5 LTS (Bionic Beaver)"
* puppeteer version: ^8.0.0
* Configuration file:
```js
const { setHeadlessWhen } = require("@codeceptjs/configure");

// turn on headless mode when running with HEADLESS=true environment variable
// export HEADLESS=true && npx codeceptjs run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: "./widgets/*_test.js",
  output: "./output",
  helpers: {
    Puppeteer: {
      url: "http://app:3000",
      show: true,
      windowSize: "375x667",
      browser: "chrome",
      chrome: {
        args: ["--no-sandbox"],
      },
    },
  },
  bootstrap: null,
  mocha: {},
  name: "app",
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true,
    },
    tryTo: {
      enabled: true,
    },
    screenshotOnFail: {
      enabled: true,
    },
  },
};

```

* More:
  * I am using official docker image for running codeceptJS.
  * The web Application, which I want to test, is built on another docker dns named `app`.

**Comment by brunoklein** [comment]
Hey @hon9g! I guess by using docker you wont be able to see the browser. 

Your options:

1. Use WebDriver or Playwright and enable the VNC (this way you can see the browser and test execution in your selenium/moon server)

2. run your tests without docker, use `npx codeceptjs run`. As you set `show: true` in your codecept.conf file the browser should appear on your PC.

**Comment by hon9g** [comment]
I want to use dockerized application and also want to see the browser. :/
I guess porting config in docker can slove this problem. (haven't try yet kk)

If there are anyone already know the solution, plz let me know.

**Comment by DavertMik** [comment]
For Docker the only solution is to use VNC as tunnel... But better avoid it
