### ISSUE TITLE
Support click and hold mouse button functionality

### ISSUE THREAD

**Issue by iampershing** [codeceptjs/CodeceptJS#2886]
Hello. 
I need help to realize next scenario
x.clickAndHold(900, 800);
x.moveMouse(1100, 1200);
x.releaseClick();
Unfortunately, I did not find any helpers to do that. 
Tried to realize via Drag and Drop but no results.
Configuration is the next:
Playwright + CodeceptJS
Could somebody help me with that ?

**Comment by DavertMik** [comment]
You can implement this with Playwright API and usePlaywrightTo method
