### ISSUE TITLE
Error from listener function resets the actual test exit code

### ISSUE THREAD

**Issue by VaasRamsay** [codeceptjs/CodeceptJS#2898]
Throwing an error from inside an event listener function returns zero exit-code even if the test execution failed.

Background: I have a wrapper shell script invoking CodeceptJS. I capture the exit code from the command in CI. It returns a zero exit code and the step passes, even when few tests failed. CLI reporter shows the actual test failures, but the exit code is `0` when an error is thrown inside an event listener (for a different purpose). On removing the listener, non-zero exit code is returned.

**Comment by DavertMik** [comment]
Sorry, cant help. Event listeners are invoked out of main loop so they are ignored
