### ISSUE TITLE
[Appium] Can't interactive with the page element of webview in Android application

### ISSUE THREAD

**Issue by ansonliao** [codeceptjs/CodeceptJS#2904]
I am running `Codecept` version `3.0.7`, and running the hybrid Android application, facing that Codecept can switch into Webview, the problems are:
1. Some page elements of the webview, codecept can recognize, but some can't recognize.
2. The page element of the webview can be recognized by codecept, but can't interactive, for example, I would like to click the element, the action is performed but nothing happens in the application (should something happen, for example, navigate to a new page, trigger the input field, etc.)
3. perform the click action by `I.click()` is failed, it is passes if `I.tap()`, why?

![2021-05-19 20 45 50](https://user-images.githubusercontent.com/6060224/118815973-5307b380-b8e4-11eb-8b6e-4f13a6f84a54.jpg)

When perform `click` action by `I.click()` in the webview, will be error, and the error message: 
> ERROR webdriver: Request failed with status 404 due to unknown command: unknown command: Cannot call non W3C standard command while in W3C mode
> unknown command: unknown command: Cannot call non W3C standard command while in W3C mode

![2021-05-19 20 45 44](https://user-images.githubusercontent.com/6060224/118816009-5b5fee80-b8e4-11eb-9011-c69ae9b38682.jpg)

And have a strange problem, as the above scanrio, `I.click()` action is failed in the webview, expect the test case will be failed, but finally codecept says the test is passed! Why? I don't understand.

![2021-05-19 20 45 54](https://user-images.githubusercontent.com/6060224/118815926-484d1e80-b8e4-11eb-9a4b-202c8d42f523.jpg)

Could you help to provide some solutions to my problems?

Thanks.

**Comment by DavertMik** [comment]
Really sorry, cant help 😭
