### ISSUE TITLE
Condition in PageObject is skipped?

### ISSUE THREAD

**Issue by stracker-phil** [codeceptjs/CodeceptJS#2917]
#### What are you trying to achieve?

I test various states of an application and toggle certain settings during tests. When a test fails, the app is left in an unknown state and I try to implement conditional logic in a Page Object to handle that case.

Specific: 

One test enables the "Debug mode" in the app settings and then confirms the correct output on the front end. That test failed. The next run also failed because the test could not enable "Debug mode" (it was already active).

I created this method inside a Page Object to handle the case:

```js
async maybeEnableDebug() {
    I.amOnPage('/config/advanced');

    const isActive = await I.executeScript(() => {
        return document.querySelector('a.disable-debug-mode') !== null;
    });

    console.log('Is debug mode active?', isActive);

    if (!isActive) {
        console.log('Enable debug mode');
        I.click('a.enable-debug-mode');
    }
    console.log('Debug mode enabled');
}
```

I expect to see the following output with the `--steps` param:

```
    I am on page /config/advanced
    I execute script [...]
    Is debug mode active? false
    Enable debug mode
    I click a.enable-debug-mode
    Debug mode enabled
```

#### What do you get instead?

However, the method correctly enters the condition but does not process the `I.click()` command. I get this output in the console:

```
    I am on page /config/advanced
    I execute script [...]
    Is debug mode active? false
    Enable debug mode
    Debug mode enabled
```

### Details

* CodeceptJS version: 3.0.7
* NodeJS Version: 14.15.4
* Operating System: MacOS
* puppeteer version (if related): 10.0.0

**Comment by stracker-phil** [comment]
Btw: If there is a better way to ensure a clean/known app state before starting the tests, please let me know. I only need conditions because some (failed) tests leave settings in an undefined state.

**Comment by stracker-phil** [comment]
I think I found the/a solution to implement conditions: The [`tryTo()`](https://codecept.io/plugins/#tryto) plugin.

```js
async maybeEnableDebug() {
    I.amOnPage('/config/advanced');

    await tryTo(() => I.click('a.enable-debug-mode'));
}
```

**Comment by nikocanvacom** [comment]
you have two options on how to ensure order of log and actions
1. put `await` in front of `I.click`:
```
await I.click('a.enable-debug-mode');
console.log(''log output after click'); 
```
2. Use CodeceptJS action for logging
```
I.click('a.enable-debug-mode');
I.say('log output after click');
```
