### ISSUE TITLE
How to return an array of elements? - similarly to querySelectorAll

### ISSUE THREAD

**Issue by bojanraden** [codeceptjs/CodeceptJS#2925]
### What are you trying to achieve?

Writing the following command in the console:

`document.querySelectorAll("[type='checkbox']")`

Returns:

`NodeList(12) [input.jss719, input.jss719, input.jss719, input.jss719, input.jss719, input.jss719, input.jss719, input.jss719, input.jss719, input.jss719, input.jss719, input.jss719]`

**This is exactly what I want to achieve in Codeceptjs, so I can later loop through the elements.**

### What do you get instead?

I've tried creating custom functions like:

```
 allSelector: function (selector)  {
  return Array.from.document.querySelectorAll(selector)
}
```

However, I keep getting `null` when console logging later in the test:

```
  let checkboxes =  (await I.grabAttributeFrom("[type='checkbox']"))

  console.log(checkboxes)
```

**Comment by DavertMik** [comment]
Implement this as a method of a custom helper
