### ISSUE TITLE
Execution hangs on using async/await in Before hook

### ISSUE THREAD

**Issue by mighty98** [codeceptjs/CodeceptJS#2927]
#### What are you trying to achieve?
My Before hook needs to perform functions like checking the local storage, waiting for URL etc but on having an asynch custom helper function which I use in before hook the execution hangs without even launching url
#### What do you get instead?
Execution hangs
In my case it doesn't even load the URL 
NOTE: If I remove the await steps in the function it works fine
> Provide console output if related. Use `--verbose` mode for more details.

```bash
[..................] / : timing config:load:flatten Completed in 4ms
```

> Provide test source code if related
`stayActiveInSession = async (page: string) => {
    console.log('stay active in ' + page);
    I.amOnPage('https://test.ui.mcafee-cloud.com');
    I.waitInUrl('test');
    const url = await I.grabCurrentUrl();
    I.say('current url is ' + url);
  };`
`Before(async ({ I }) => {
  await I.stayActiveInSession('rules');
});`
```
```

### Details

* CodeceptJS version:3.0.7
* NodeJS Version:
* Operating System:Windows 10

**Comment by DavertMik** [comment]
Not sure, i can help here 😭
