### ISSUE TITLE
CodeceptJS travis CI builds are failing on docker hub pull limit

### ISSUE THREAD

**Issue by nikocanvacom** [codeceptjs/CodeceptJS#2932]
e.g.
https://github.com/codeceptjs/CodeceptJS/pull/2912
- https://travis-ci.org/github/codeceptjs/CodeceptJS/jobs/773522940

https://github.com/codeceptjs/CodeceptJS/pull/2916
- https://travis-ci.org/github/codeceptjs/CodeceptJS/jobs/773771578

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by DavertMik** [comment]
Thanks. The best decision so far is to move away from Travis
Which we did in recent days
