### ISSUE TITLE
BDD: the examples mention "And", but it's not defined 

### ISSUE THREAD

**Issue by dominikabieder** [codeceptjs/CodeceptJS#2935]
<img width="438" alt="Screenshot 2021-06-23 at 11 18 28" src="https://user-images.githubusercontent.com/31188583/123071257-cc7b5000-d414-11eb-8d17-d55cad95fc84.png">
#### What are you trying to achieve?
I want to use And in my BDD steps.

```
Given x
When x
And x
Then
```

 _And_ is mentioned in the examples for BDD in the documentation https://codecept.io/bdd/#gherkin, but it doesn't work.

<img width="775" alt="Screenshot 2021-06-23 at 11 17 41" src="https://user-images.githubusercontent.com/31188583/123071084-a48bec80-d414-11eb-80b8-448d5e092a51.png">

#### What do you get instead?
 _And_ is not defined and TS complains.
`TS2304: Cannot find name 'And'.`

<img width="571" alt="Screenshot 2021-06-23 at 11 18 23" src="https://user-images.githubusercontent.com/31188583/123071233-c5ecd880-d414-11eb-8a2c-d9a7afd6636d.png">

<img width="438" alt="Screenshot 2021-06-23 at 11 18 28" src="https://user-images.githubusercontent.com/31188583/123071311-d8671200-d414-11eb-8c23-b8b97c7207b3.png">

**Comment by nikocanvacom** [comment]
`And` makes sense in scenarios. In step definition you would use relevant Given/When/Then keyword instead. It this case `Then` could be used:
```
Then("I provide appointment details", () => {
  I.click('Jetzt Finanzierung beschreiben');
})
```

**Comment by dominikabieder** [comment]
no, _then_ focuses on the final result. for the time being I'm just using another _when_ as a workaround.

Given X
When I do X
And I do Y
Then I see X

**Comment by nikocanvacom** [comment]
That is correct, I was looking at screenshot, and in screenshot `And` scenario step was referring to `Then` step. In your case `When` is probably right one. 
`And` shouldn't be used in step definitions... so the fact that it is not available for step definition is by-design, it's not a bug.

**Comment by dominikabieder** [comment]
This is a screen of a BDD example from wikipedia. _And_ is a helpful way of expressing that an action requires many steps and I think the users would benefit from having it in the step definitions. 

<img width="582" alt="Screenshot 2021-06-24 at 14 45 23" src="https://user-images.githubusercontent.com/31188583/123264962-d5dee800-d4fa-11eb-80c1-4dbcf8e905a5.png">

**Comment by nikocanvacom** [comment]
In feature files, not in step definition files. In step definition files `And` doesn't make sense as it has no context of previous steps.
