### ISSUE TITLE
Can allure plugin use JSON file format?

### ISSUE THREAD

**Issue by xyngfei** [codeceptjs/CodeceptJS#2936]
#### What are you trying to achieve?
allure plugin should generate `JSON` format instant of `XML` format file

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

![image](https://user-images.githubusercontent.com/17619539/123080463-868fad80-d44f-11eb-9792-ee8efe9ba724.png)

> Provide test source code if related

```

### Details

* CodeceptJS version: 3.0.6
* NodeJS Version: v14.16.1
* allure-commandline: 2.13.8
* Operating System: macOS cataline 10.15.7 
* **Puppeteer** || webdriverio || protractor || testcafe version (if related)
* Configuration file: codecept.conf.js

plugins: {
    allure: {
      enabled: true,
      outputDir: "./output",
      fullPageScreenshots: true,
      screenshotsForAllureReport: true,
      useCucumberStepReporter: true,
    },
  },

```

**Comment by DavertMik** [comment]
We support Allure 1.x at this moment which generates xml format. If you want Allure 2.x you can ask Allure team to support codeceptjs
