### ISSUE TITLE
Cannot execute multiple sessions simultaneously

### ISSUE THREAD

**Issue by lehoanglu0ng** [codeceptjs/CodeceptJS#2940]
#### What are you trying to achieve?
-> Execute multiple sessions simultaneously

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
The sessions execute sequentially
```

> Provide test source code if related

```js
userList.map(user => {
    session(user.userName, () => {
        I.loginAs(user)
    })
})

I also try with

userList.map(async (user) => {
    await session(user.userName, () => {
        I.loginAs(user)
    })
})

even

Promise.All(userList.map(async (user) => {
    await session(user.userName, () => {
        I.loginAs(user)
    })
}))
```

### Details

* CodeceptJS version: 3.0.7
* NodeJS Version: 16.2.0
* Operating System: macOS 11.4 M1
* Playwright 1.12.2

**Comment by DavertMik** [comment]
I dont think this is valid case for codeceptjs. Cant say for sure what might be wrong here but better not use this behavior 😁
