### ISSUE TITLE
UnhandledPromiseRejectionWarning: RequestError: read ECONNRESET

### ISSUE THREAD

**Issue by AllysonYuShiong** [codeceptjs/CodeceptJS#2944]
#### What are you trying to achieve?
To use config of webdriverio restart set to true without getting the UnhandledPromiseRejectionWarning: RequestError: read ECONNRESET error in the console. I want to have a fresh restart of web session without throwing me the error.

### Details

* CodeceptJS version: 3.0.7
* NodeJS Version: v14.17.0
* Operating System: Mac OS X Big Sur 11.4
* webdriverio
* Configuration file:

```js
exports.config = {
  tests: './scenarios/**/*_test.js',
  output: './output',
  helpers: {
    WebDriver: {
      url: https://buycoke.com,
      browser: chrome,
      restart:true,
      maximize:true
    },
    REST:{}
  },
  include: {
    I:  './steps_file.js'
  },
  plugins:{
      pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    },
    wdio: {
          enabled: true,
          services: ['selenium-standalone']
    }
  },
  bootstrap: null,
  name: 'codeceptjs'
}
```

### Screenshot
![Screenshot 2021-07-04 at 4 00 40 PM](https://user-images.githubusercontent.com/21327961/124377886-008e2500-dce1-11eb-8f7a-27f35a700d3a.png)

**Comment by AllysonYuShiong** [comment]
@PeterNgTr can you help me with this issue? this is not related to the async/await because I don't have the issue when I set the restart to false. Also, it is reproducible with a single test scenario with a session inside. Any workaround is very much appreciated.

**Comment by DavertMik** [comment]
Sorry, have no idea what can be wrong here
