### ISSUE TITLE
Page crashed error when using Codeceptjs with Puppeteer in a docker container 

### ISSUE THREAD

**Issue by ItIsFabian** [codeceptjs/CodeceptJS#2966]
#### What are you trying to achieve?
We are using Codecept productively, generating executable codecept code and executing that code via Puppeteer in a Docker container. 

#### What do you get instead?

We have made the observation that when 
* large tests with around 20 scenarios  and around 15-20 steps each are executed 
* the "Popup already exists and was not closed." error occurs at least once 

the "Puppeteer page error Error: Page crashed!" is thrown again and again, causing an infinite loop and thus no output log with the execution result is produced. The Log however is important to us because we can only run the tests in headless mode in our container, so the user only receives the log as test execution result and basis for debugging the created tests. 

_Note:  The suggestions mentioned in https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker have been tried and had no impact._

Log captured live from the container:
[log_nf_format.txt](https://github.com/codeceptjs/CodeceptJS/files/6884768/log_nf_format.txt)

Test Code: 
[main_test_nd.txt](https://github.com/codeceptjs/CodeceptJS/files/6884782/main_test_nd.txt)

### Details

* CodeceptJS version: 3
* NodeJS Version: 12.18.04
* Operating System: Suse Linux with Docker v19.03.11
* puppeteer: 10.
* Configuration file: [config.txt](https://github.com/codeceptjs/CodeceptJS/files/6884786/config.txt)

**Comment by DavertMik** [comment]
sorry, can't help
