### ISSUE TITLE
In codeceptjs npm i command downloads the advance version of chrome 93 rather than current version of chrome 92.0.4515.107

### ISSUE THREAD

**Issue by fauwazahmad** [codeceptjs/CodeceptJS#2967]
#### What are you trying to achieve?
I run the script and getting below error on the console.

#### What do you get instead?
Can't connect to WebDriver.
                Error: Failed to create session.
                session not created: This version of ChromeDriver only supports Chrome version 93
                Current browser version is 92.0.4515.107 with binary path /usr/bin/google-chrome
                Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
                System info: host: 'ds-taxonomy01-int-g1ds-xonomy-name-generator-ui-full-16276h5hpd', ip: '10.136.3.125', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1046-azure', java.version: '11.0.8'
                Driver info: driver.version: unknown
                remote stacktrace: #0 0x55b3629d48c3 <unknown>
                #1 0x55b362747ae8 <unknown>
                #2 0x55b36276e260 <unknown>
                #3 0x55b362769b98 <unknown>
                #4 0x55b362765eea <unknown>
                #5 0x55b36279fb17 <unknown>
                #6 0x55b362799e63 <unknown>
                #7 0x55b362770883 <unknown>
                #8 0x55b362771935 <unknown>
                #9 0x55b362a02b63 <unknown>
                #10 0x55b362a1626b <unknown>
                #11 0x55b362a174ef <unknown>
                #12 0x55b362a03c70 <unknown>
                #13 0x55b362a17a85 <unknown>
                #14 0x55b3629f9d4b <unknown>
                #15 0x55b362a315a8 <unknown>
                #16 0x55b362a31728 <unknown>
                #17 0x55b362a4b1ed <unknown>
                #18 0x7f08f5ca86db start_thread
                
                
                Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 2.6.11
* NodeJS Version: 12.18.0
* Operating System: Window
* puppeteer || webdriverio || protractor || testcafe version (if related): webdriverio
* Configuration file:

```js
# paste config here
```

**Comment by DavertMik** [comment]
Please use [selenium-standalone](https://www.npmjs.com/package/selenium-standalone) package to manage browsers and webdriver deps

**Comment by fauwazahmad** [comment]
Hi @DavertMik ,
Thanks for you suggestion.
Issue is resolved as now it is downloading the correct version.
