### ISSUE TITLE
Plugin to record subtitles for video

### ISSUE THREAD

**Issue by DavertMik** [codeceptjs/CodeceptJS#2976]
With a video recording enabled for Playwright it is important also to show the progress of a test within that video.
The easiest solution so far is to generate subtitles to each video recorded by Playwright.

* Subtitles will include all executed steps and saved into *.srt file. 
* This srt file should be named after a video file which was saved (can be obtained from `test.artifacts.video` **after** a test)

The flow is:

* create a plugin
* listen to all `step.before` events
* write all steps into memory
* after a test check for `test.artifacts.video` to be found
* if this is found - write subtitles file

**Comment by DavertMik** [comment]
@anirudh-modi

**Comment by Elverslane** [comment]
pay attention to the fresh update of the [allure](https://github.com/allure-framework/allure-js/releases/tag/v2.0.0-beta.11)
