### ISSUE TITLE
Unable to `grabCookies` for `Playwright` in `BeforeSuite`

### ISSUE THREAD

**Issue by anirudh-modi** [codeceptjs/CodeceptJS#2977]
#### What are you trying to achieve?
I have a `BeforeSuite`, where I was trying to set cookies and then get them back, an example code is
```js
BeforeSuite(async ({ I}) => {
    I.setCookie([{
        name: 'user',
        value: 'Anirudh'
    }]); // set some cookies
    const user = await I.grabCookie('user');
});
```

#### What do you get instead?
I have been getting an error.

```bash
"before all" hook: BeforeSuite for "DropDown Test":
     Cannot read property 'cookies' of undefined
      at Playwright.grabCookie (node_modules/codeceptjs/lib/helper/Playwright.js:1545:47)```

### Details

* CodeceptJS version: 3.1.11
* NodeJS Version: v14.17.4
* Operating System: macOs
* playwright
* Configuration file: 

```js
exports.config = {
  tests: './core/tests/*_test.js',
  output: // value
  helpers: {
    REST: {
      endpoint: // value
    },
    Playwright: {
      show: mode === 'local',
      browser: process.env.NODE_EXTRA_TEST_BROWSER,
      waitForNavigation: 'load',
    },
  },
  bootstrap: null,
  mocha: {},
  name: // value
  plugins: {
    pauseOnFail: { enabled: false },
    tryTo: {
      enabled: true,
    },
    screenshotOnFail: {
      enabled: true,
    },
  },
};
```

**Comment by anirudh-modi** [comment]
Upon investigating I found it is due to the recent changes done in playwright helper, as shown in this PR
https://github.com/codeceptjs/CodeceptJS/pull/2974/files?file-filters%5B%5D=.js

Where, we have moved the code which sets `this.browserContext` from `_startBrowser` to `_before`, because of which when I was calling the `I.grabCookies`, `this.browserContext`  is no longer set as the code for setting `browserContext` is moved to `_before` as shown in this code
https://github.com/codeceptjs/CodeceptJS/blob/5bda7fc8dd8b76fb8fccaf2ed3fda023dbac70c9/lib/helper/Playwright.js#L357-L370

**Comment by anirudh-modi** [comment]
I want to fix this issue but as a fix for this I wanted to understand why the code for setting browserContext was moved from `_startBrowser` to `_before`.

@DavertMik Any thoughts on this?

**Comment by DavertMik** [comment]
Browser is not available in beforeSuite:

![image](https://user-images.githubusercontent.com/220264/129096271-895db219-9e70-4586-bd05-15965a34d514.png)

I recommend using autoLoginPlugin instead. Or at least check how it works, maybe you can take the idea or extend it to match your needs.
