### ISSUE TITLE
Need Configuration for automatically selecting client certificate in mutual TLS based test cases

### ISSUE THREAD

**Issue by nagaraj-pattar** [codeceptjs/CodeceptJS#2990]
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || protractor || testcafe version (if related)
* Configuration file:

```js
# paste config here
```

**Comment by DavertMik** [comment]
Not enough information
