### ISSUE TITLE
allow saveElementScreenshot to save to specified path

### ISSUE THREAD

**Issue by ogiexela** [codeceptjs/CodeceptJS#2996]
#### What are you trying to achieve?
Better structure screenshots.
I.saveElementScreenshot('some element', `firefox/600x800/regression/banner/small_banner.png`)

which should save to 

`firefox -> 600x800 -> regression -> banner -> small_banner.png`

#### What do you get instead?
The above case doesn't work. `saveElementScreenshot` only takes a file name without path and saves it to the folder defined in the `codecept.conf.js` which results in all screenshots going to the same folder and makes it hard to manage.

**Comment by PeterNgTr** [comment]
oh why don't you just name like this `firefox_600x800_regression_banner_small_banner.png`?

**Comment by DavertMik** [comment]
you can create custom method in a helper which will save wherever you want.
you can take `saveScreenshot` as a reference for that
