### ISSUE TITLE
Protractor Mouse Right click not working in firefox browser

### ISSUE THREAD

**Issue by A-Kavin** [codeceptjs/CodeceptJS#2998]
System:
Firefox Version: 90.0.2 (64-bit)
Protractor Version: 7.0.0
Typescript
Webdriver updated

Issue in Firefox Browser:
WebDriverError: HTTP method not allowed

Code:
await browser.actions().click(protractor.Button.RIGHT).perform();

**Comment by DavertMik** [comment]
Sorry, protractor is deprecated by protractor team and we are also not going to support it
