### ISSUE TITLE
I.grabValueFromAll is not working - using PlayWright directly is working.

### ISSUE THREAD

**Issue by m3t4n** [codeceptjs/CodeceptJS#3008]
#### What are you trying to achieve?
grab value of matching elements in page
#### What do you get instead?
undefined
> Output: 
```bash
>>>> i = 0: undefined
>>>> i = 1: undefined
>>>> i = 2: undefined
>>>> i = 3: undefined
>>>> i = 4: undefined
>>>> i = 5: undefined
>>>> i = 6: undefined
>>>> i = 7: undefined
```
> Source Code

```js
let strValues = await I.grabValueFromAll("span.value");
for(let i=0; i<strValues.length; i++) {
      this.log.debug(">>>> i = " + i + ": "+ strValues[i]);
}
```

>Using Playwright API:
```bash
>>>> i = 0: 50,042
>>>> i = 1: 58,135
>>>> i = 2: -8,093
>>>> i = 3: +50,042
>>>> i = 4: 1,187,973
>>>> i = 5: 1,261,104
>>>> i = 6: -73,131
>>>> i = 7: +1,187,973
```
> Source Code

```js
I.usePlaywrightTo("grabValuesFromAll", async ({page}) => {
    let elms = await page.$$("span.value");
    for(let i=0; i<elms.length; i++) {
        this.log.debug(">>>> i = " + i + ": "+ await elms[i].innerText());
    }
});
```
### Details

* CodeceptJS version:  3.1.0
* NodeJS Version: 14.16.1
* Operating System: MACOS
* playwright

**Comment by Georgegriff** [comment]
Your code samples do different things the first one using grabValueFromAll is meant to be used on proper input HTML element which have value attributes, you are using a span.

Where as your example of usePlaywrightTo uses .innerText which works because spans have this, they do not have values.

**Comment by m3t4n** [comment]
thank you @Georgegriff seems like i should've used grabTextFromAll instead. confused me. thank you. would've been great if the documentation stated that this method will look for the value attribute.
