### ISSUE TITLE
Command re-rerun doesn't work 

### ISSUE THREAD

**Issue by MoonMaster** [codeceptjs/CodeceptJS#3009]
#### What are you trying to achieve?
I want to run a command to restart failed tests https://codecept.io/commands/#run-rerun
#### What do you get instead?
The console says that the run-rerun command does not exist

![image](https://user-images.githubusercontent.com/4430846/131481377-6c307a63-c2bb-4c26-9fe6-41b7128737cd.png)

**Comment by PeterNgTr** [comment]
closed as favor of https://github.com/codeceptjs/CodeceptJS/issues/2670
