### ISSUE TITLE
Appium: Incorrect/missing types/params for some methods in TypeScript definition

### ISSUE THREAD

**Issue by mirao** [codeceptjs/CodeceptJS#3039]
#### What are you trying to achieve?
* Setup [TypeScript](https://codecept.io/typescript/#typescript) in CodeceptJS
 
Methods `I.touchPerform()`, `I.hideDeviceKeyboard()` or `I.removeApp()` should work in TypeScript tests, e.g.:

```js
    I.touchPerform([{
        action: "longPress",
        options: assetsFragment.visibilityActionCoordinates
    }, { action: "release" }]);
    I.hideDeviceKeyboard();
    I.removeApp(commonPage.appName);
```

#### What do you get instead?
They work in JavaScript tests only.
In TypeScript tests you get these TS errors:

* touchPerform: `Expected 0 arguments, but got 1.ts(2554)`
* hideDeviceKeyboard: `Expected 1 arguments, but got 0.ts(2554)
types.d.ts(529, 28): An argument for 'strategy' was not provided.`
* removeApp: `Expected 2 arguments, but got 1.ts(2554)
types.d.ts(328, 34): An argument for 'bundleId' was not provided.`

**I checked that:**
* `touchPerform` has incorrect TS definition (missing param):
node_modules/codeceptjs/typings/types.d.ts:
```js
touchPerform(): void;
```
* `hideDeviceKeybord` has this definition:
```js
hideDeviceKeyboard(strategy: 'tapOutside' | 'pressKey'): void;
```
but it doesn't match the example in Appium.js (which works for me in JavaScript):
![image](https://user-images.githubusercontent.com/12584138/133074657-d4eba4b1-edbf-4b83-bdb1-769012d82290.png)
* `removeApp` has mandatory `bundleId`, but it works even with `appId` only (in JavaScript):
TS definition:
![image](https://user-images.githubusercontent.com/12584138/133075009-3e54377a-2789-4552-8f2c-8561a9465a08.png)
Appium.js:
![image](https://user-images.githubusercontent.com/12584138/133075057-ae78ec56-60ba-4259-9aa4-00fc39ddd01c.png)

> Provide console output if related. Use `--verbose` mode for more details.

**Workaround in my code:**
* `touchPerform`: Ignore the TS/ESlint checks:
```js
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
I.touchPerform([{
        action: "longPress",
        options: assetsFragment.visibilityActionCoordinates
}, { action: "release" }]);
```
* `hideDeviceKeybord`: Use explicit "tapOutside"
```js
I.hideDeviceKeyboard("tapOutside");
```
* `removeApp`: Use explicit `undefined` in `bundleId`
```js
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
I.removeApp(commonPage.appName, undefined!);
```
### Details

* CodeceptJS version: 3.0.7
* NodeJS Version: v12.22.6
* Operating System: Ubuntu 20.10

**Comment by DavertMik** [comment]
Hi, could you look into fixing these? 
Our types are generated from JSDoc in Appium helper

This is how definitions are generated https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/command/definitions.js
