### ISSUE TITLE
Autocompletion for TypeScript does not work if I("Actor") has extensions in IntelliJ IDEA Ultimate

### ISSUE THREAD

**Issue by frixatrix** [codeceptjs/CodeceptJS#3056]
#### What are you trying to achieve?
Auto-complete in Intellij IDEA Ultimate for codeceptjs/typescript/puppeteer/mochawesome setup when "Actor"(I) is extended with custom steps file.
I did extension as described here: https://codecept.io/pageobjects/#actor

#### What do you get instead?
Auto-complete stoops working for parent methods and for custom ones.

#### STR
Example done with https://github.com/codeceptjs/typescript-boilerplate

I commented out in `loginPage.ts` method link:

```js
  // async link () {
  //   await I.waitForVisible(this.locator)
  // }
```

and added same code to `steps_file.ts`

```js
export = function (): any {
  return actor({
    // Define custom steps here, use 'this' to access default methods of I.
    // It is recommended to place a general 'login' function here.
	link: async function (): Promise<void> {
		  await this.waitForVisible(this.locator)
	  }
  });
};
```

Then added include to `codeceptjs.conf.js`:
```js
  include: {
	I: 'steps_file.ts',
```

Then run `codeceptjs def .`

```
> codeceptjs def .
TypeScript Definitions provide autocompletion in Visual Studio Code and other IDEs
Definitions were generated in steps.d.ts
```

Then opened `Typescript_Example_test.ts`
And pointer mouse on any methods called from 'I'.

#### Result:

0 methods of I available for TS for autocomplete.

![Screenshot 2021-09-30 at 15 33 04](https://user-images.githubusercontent.com/25078398/135465239-38bcf4be-7995-4498-a735-4544b8ab1a26.png)
![Screenshot 2021-09-30 at 15 33 09](https://user-images.githubusercontent.com/25078398/135465247-abee1972-58db-4284-9081-22be7fa63448.png)
![Screenshot 2021-09-30 at 15 33 14](https://user-images.githubusercontent.com/25078398/135465251-541ae527-16c5-40dd-b820-24f6fdc93d59.png)
![Screenshot 2021-09-30 at 15 33 24](https://user-images.githubusercontent.com/25078398/135465252-88ab1d73-f43d-4e22-834d-051bb2f7fc09.png)

And if I don't do those changes - everything works as expected:

![Screenshot 2021-09-30 at 15 34 05](https://user-images.githubusercontent.com/25078398/135465347-5de83fbf-f85f-4283-a27d-40ea8b3375c7.png)
![Screenshot 2021-09-30 at 15 34 10](https://user-images.githubusercontent.com/25078398/135465352-e3125552-9620-44ae-b32f-58cc5e3d4b86.png)

### Details

* CodeceptJS version:  3.0.0 
* NodeJS Version:14.15.1
* Operating System:MacOSX
* puppeteer 
* Configuration file:

```js
require('ts-node/register')
const { setHeadlessWhen } = require('@codeceptjs/configure');
const { bootstrap } = require('./presettings.ts');

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './tests/**_test.ts',
  output: './output',
  helpers: {
    // Playwright: {
    //   url: 'https://github.com',
    //   show: false,
    //   windowSize: '1200x900',
    //   browser: 'chromium'
    // },
	  Puppeteer: {
		  url: './',
		  basicAuth: { username: 'user', password: 'pass' },
		  show: true,
		  windowSize: '1280x900',
		  waitForNavigation: "networkidle0"
	  },
    CustomHelper: {
      require: './CustomHelper.ts'
    }
  },
  bootstrap,
  include: {
	// I: 'steps_file.ts',
    loginPage: './loginPage.ts',
    homePage: './homePage.ts'
  },
  name: 'typescript-boilerplate',
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}

```

**Comment by angelov-a** [comment]
I am have the same observation as @daigo75.

Adding `WithTranslation<Methods>` manually to `I` definition fixes the issue to some extent.

**Update**: Make sure not to use `any` as a return type of the `steps_file.ts` export. The type should be inferred instead.

```
export = function () {
   return actor({})
}
```
