### ISSUE TITLE
Cannot use global plugins with Typescript

### ISSUE THREAD

**Issue by jonguenther** [codeceptjs/CodeceptJS#3146]
#### What are you trying to achieve?

I am trying to use plugins like `tryTo` globally in Typescript, however, it seems that they are not defined.

#### What do you get instead?

Typescript is throwing `Cannot find name 'tryTo'.ts(2304)`

```ts
Scenario('login', ({ I }) => {
  tryTo(() => I.amOnPage('/login'); // this fails
  I.seeElement({ name: 'login' });
  // ...
});
```

A workaround would be

```ts
const tryTo = codeceptjs.container.plugins('tryTo');

Scenario('login', ({ I }) => {
  tryTo(() => I.amOnPage('/login'); // this works, but parameters are any
  I.seeElement({ name: 'login' });
  // ...
});
```

However, `tryTo` then has no type definition (defined as `any`). My question would be if it is possible to use plugins like `tryTo` globally and with a type definition in Typescript (latter one being more important).

See this [Stackblitz](https://stackblitz.com/edit/github-a5tddk?file=homePage.ts) as example (note that there are a few more type issues).

### Details

* CodeceptJS version: `3.2.1`
* NodeJS Version: `14.17.6`
* Operating System: MacOS

<details>
<summary> Configuration file </summary>

```js
require('ts-node/register');

exports.config = {
  tests: './src/e2e/tests/*_test.ts',
  output: './logs/e2e/',
  helpers: {
    Playwright: {
      url: 'https://localhost:8080/',
      show: !process.env.HEADLESS,
      browser: 'chromium',
    },
  },
  include: {
    I: './steps_file.js',
  },
  bootstrap: null,
  mocha: {},
  name: 'TS-Test',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true,
    },
    tryTo: {
      enabled: true,
    },
    screenshotOnFail: {
      enabled: true,
    },
  },
};
```

</details>

**Comment by emanuelwong** [comment]
I was looking at the documentation and it seems that you need to use registerGlobal:
Configuration
registerGlobal - to register tryTo function globally, true by default
If registerGlobal is false you can use tryTo from the plugin:
const tryTo = codeceptjs.container.plugins('tryTo');

```
tryTo: {
      enabled: true,
      registerGlobal: true
    },
```
    
    [https://codecept.io/plugins/#:~:text=click(%27Agree%27%2C%20%27.cookies%27))%3B-,%23,-Configuration]

**Comment by jonguenther** [comment]
According to the [docs](https://codecept.io/plugins/#configuration-12), `registerGlobal` should be enabled by default if `tryTo` is set to enabled 😕

**Comment by jonguenther** [comment]
Thanks for your reply @emanuelwong , but as you mentioned in your quote, `registerGlobal` should be enabled by default if `tryTo` is set to enabled, so Typescript theoretically should pick it up, shouldn't it? 😕

**Comment by ryanknittel-fdx** [comment]
I cannot find any type definitions for the global plugin functions like `tryTo` in CodeceptJS's `d.ts` files.

**Comment by sboudouk** [comment]
any news on this ?

**Comment by kobenguyent** [comment]
hey @sboudouk hope this https://github.com/codeceptjs/CodeceptJS/pull/3461 will kill the issue.

**Comment by sboudouk** [comment]
Thanks @PeterNgTr , will look forward to this.
