### ISSUE TITLE
retryTo plugin don't wait pollInterval before retry

### ISSUE THREAD

**Issue by arcsun** [codeceptjs/CodeceptJS#3147]
#### What are you trying to achieve?
try some action ,failed, wait pollInterval, then retry.

#### What do you get instead?
try some action ,failed,  then retry immediately.

> Provide console output if related. Use `--verbose` mode for more details.
![image](https://user-images.githubusercontent.com/7878584/143382644-0ca06f10-b702-4c24-93b8-69a09def6349.png)

### Details

* CodeceptJS version: 3.2.2
* NodeJS Version:
* Operating System: macos 12
* puppeteer || webdriverio || testcafe version (if related)   playwright
* Configuration file:

```js
{
  retryTo: {
      enabled: true,
      pollInterval: 1000,
      registerGlobal: true
    }
}
```

**Comment by DavidK-Visiba** [comment]
In the `retryTo.js` file, there is only one use of the `pollInterval` variable but that line is commented out by @DavertMik.
