### ISSUE TITLE
[Customize Helper] How to define an async customize helper 

### ISSUE THREAD

**Issue by SonNguyenVN** [codeceptjs/CodeceptJS#3192]
#### What are you trying to achieve?
Define a customize helper with async
#### What do you get instead?
When calling customize helper method (myAsyncMethod), it does not wait to finish method
#### test
Feature('LoginNavigate');

Scenario('Login to Demo site', async ( I ) => {
    await I.launchChannel();
});

#### helper class
  async launchChannel() {
    await myAsyncMethod()
   // it does not wait for this method finish
  }

**Comment by kobenguyent** [comment]
Hey @SonNguyenVN do you happen to try with latest version of codeceptjs? Closing for now. Feel free to reopen if this is still the case.
