### ISSUE TITLE
CodeceptJS：Can you support third-party browsers?

### ISSUE THREAD

**Issue by cc258369** [codeceptjs/CodeceptJS#3204]
#### What are you trying to achieve?
except chromium，Firefox，webkit,

### Details

* CodeceptJS version:3.0.7
* NodeJS Version:
* Operating System:
* puppeteer || webdriverio || testcafe version (if related)
* Configuration file:

**Comment by PeterNgTr** [comment]
I believe codeceptjs supports what the engines support. (wdio, puppeteer, etc.)

**Comment by DavertMik** [comment]
yes, everything that Playwright or webdriverio supports is supported
