### ISSUE TITLE
Enhancement Feature.only

### ISSUE THREAD

**Issue by sulthan-ahmed** [codeceptjs/CodeceptJS#336]
#### What are you trying to achieve?

I want to just run all the tests within a feature.  I know you can just run a scenario by doing scenario.only but it would be cool just to run the feature.only in isolation.  Perhaps, it's possible but I couldn't find it in the docs

**Comment by DavertMik** [comment]
You can run a single file, that's probably it:

```
codeceprjs run . tests/my_feature_test.js
```

Yes, this dot `.` is confusing but it points that config should be taken from current directory. Probably this will be changed in next versions. Also implementing `Feature.only` is nice idea too.

**Comment by sulthan-ahmed** [comment]
nice one, I couldn't get it working on our project https://github.com/UKHomeOffice/firearms/ it might be the way we run codecept in our package.json codeceptjs run ./node_modules/so-acceptance --steps.  therefore I attempted the following `./node_modules/.bin/codeceptjs ./node_modules/so-acceptance/ apps/common/acceptance/features/activity.js`

**Comment by DavertMik** [comment]
The signature is

```
codeceptjs <path-to-config> <path-to-file-related-to-config>
```
In your case that can be `.` ( saw config in your root folder):
```
./node_modules/.bin/codeceptjs . ./node_modules/so-acceptance/apps/common/acceptance/features/activity.js
```

Alternatively you can use `--grep` and filter a feature by its name.

P.S. I plan to change this weird behavior in next major release. However, I don't have estimates right now.

**Comment by sulthan-ahmed** [comment]
Thanks for your help 🙂
