### ISSUE TITLE
Default `seleniumAddress` doesn't allow to use `seleniumServerJar`

### ISSUE THREAD

**Issue by romanovma** [codeceptjs/CodeceptJS#425]
#### What are you trying to achieve?

Run Selenium automatically when tests are started like described here: [Starting the Server from a Test Script](https://github.com/angular/protractor/blob/master/docs/server-setup.md#standalone-selenium-server)

#### What do you get instead?
Protractor still tries to use hosted Selenium instead of local. 
`W/driverProviders - Using driver provider hosted, but also found extra driver provider parameter(s): seleniumServerJar`

### Details

This is because of protractor logic which described in help: `Please note that if you set seleniumAddress, the settings for seleniumServerJar, seleniumPort, seleniumArgs, browserstackUser, browserstackKey, sauceUser and sauceKey will be ignored.` and can be found in the source as well: https://github.com/angular/protractor/blob/ca4f1acda3672942307d0f102d586c8889dd3d68/lib/driverProviders/index.ts#L31

Removing default seleniumAddress doesn't help sadly: https://github.com/Codeception/CodeceptJS/blob/3987de3e5145335147b713fe256fede3369e2483/lib/helper/Protractor.js#L69, because now get the following error: `The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.`

**Comment by EvtK** [comment]
Yes, I have exactly the same issue. Any progress on this?
