### ISSUE TITLE
switchTo NightmareJS

### ISSUE THREAD

**Issue by ajaysolleti** [codeceptjs/CodeceptJS#440]
#### What are you trying to achieve?

Navigate to a child frame and continue executing the tests

#### What do you get instead?

`I.swtichTo` is not a recognised function when using NightmareJS helper

### Details

* CodeceptJS version: 0.5.1
* NodeJS Version: 7.7.1
* Operating System: macOS
* Nightmare version (if related): 2.10.0

**Comment by DavertMik** [comment]
Yes, it is not implemented in Nightmare yet
Could you look into NightmareJS and implement this specific step inside NightmareJS helper?
Please submit a pull request.

**Comment by satsukikorin** [comment]
I think this related to, and should it be coordinated with, [issue 450](https://github.com/Codeception/CodeceptJS/issues/450).
