### ISSUE TITLE
test downloads…

### ISSUE THREAD

**Issue by kevinfoerster** [codeceptjs/CodeceptJS#461]
using nightmare, I try test downloads on a page. depending on nightmares configuration, it behaves differently but not correct, the download does not start
`
I.click('Download')
// triggers a request to a pdf, which should be downloaded
I.acceptPopup()
// does accept the download prompt
`

#### What are you trying to achieve?

if `show: true` is set, electron shows a download dialog but does not accept the shown dialog

if `show: false` is set, electron opens anyway after `I.click('Download')` has been clicked but the download dialog is neither shown nor confirmed.

### Details

* CodeceptJS version: v0.5.1
* NodeJS Version: v4.4.5
* Operating System: Mac OS
* Nightmare
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": "http://localhost",
      "show": true
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "test"
}
```

**Comment by joeypedicini92** [comment]
I have the same issue. I think there's a way using the Nightmare helper you can hook into the electron 'will-download' event and maybe auto accept. But this would be a great feature to have
