### ISSUE TITLE
feature request: 3rd variable when using selector

### ISSUE THREAD

**Issue by joelgrimberg** [codeceptjs/CodeceptJS#520]
When I use xpath, I use it like this:
`I.waitForElement('//*[@id="js_items_content"]/li[1]/div[2]/div[2]/div[5]/div/div[1]/a'); //first item `

console-output gives me:

>  • I wait for element "//*[@id="js_items_content"]/li[1]/div[2]/div[2]/div[5]/div/div[1]/a" 

would be cool to be able to use it like:
`I.waitForElement('//*[@id="js_items_content"]/li[1]/div[2]/div[2]/div[5]/div/div[1]/a', 'first item'); `
and console output:

>  • I wait for element "fist item" 
this gives me much more readability

**Comment by tfiwm** [comment]
Yes it is a good idea to give the possibility to have your custom error message like you do if you make an assertion. Like it :)

**Comment by DavertMik** [comment]
Interesting proposal but I'd rather implement it in a different way. Probably we can have a `selector` object. So it could be used like:

```js
selector(locator, description) => { locator, description }
```
Inside a test a locator will be used, in a console a description will be printed
