### ISSUE TITLE
"codeceptjs run --debug-brk" does nothing

### ISSUE THREAD

**Issue by mo** [codeceptjs/CodeceptJS#559]
"./node_modules/.bin/codeceptjs run --debug-brk" runs my test as usual without stopping on an initial breakpoint and no debugger URL is printed either.

**Comment by DavertMik** [comment]
I'm not sure why should have it worked the way you wanted. There is no `--debug-brk` option in command

Please tell more about how you want it to debug

**Comment by mo** [comment]
I found it in "--help" (see screenshot)

**Comment by mo** [comment]
![image](https://user-images.githubusercontent.com/7117/27400407-49bce8f2-56c0-11e7-8644-4c757fc5b5f8.png)

**Comment by DavertMik** [comment]
Oh, looks like this is inherited from mocha framework but it is not used :(
Sorry
