### ISSUE TITLE
Headless Chrome slows tests by 10x

### ISSUE THREAD

**Issue by fatso83** [codeceptjs/CodeceptJS#561]
#### What are you trying to achieve?
I am trying to run my tests in headless Chrome using the `--headless` argument. I expect the tests to run in approximately the same amount of time as the usual runs, as running [a clean webdriverio script](https://stackoverflow.com/questions/42303119/selenium-webdriverio-chrome-headless/44328140#44328140) runs faster headless than in a normal browser window.

#### What do you get instead?
The tests run about ten times as slow, using 44 seconds instead of 4 seconds.

```bash
$ time $(npm bin)/codeceptjs run --verbose > headless-output.txt

real	0m44.973s
user	0m0.992s
sys	0m0.068s

$ nvim codecept.json # removing --headless option

developer at developer-XPS-13-9360 in ~/dev/dx-nuflo/tests/acceptance (acceptance-testing)
$ time $(npm bin)/codeceptjs run --verbose > output.txt

real	0m4.879s
user	0m0.768s
sys	0m0.088s
```

<details>
<summary>verbose output from headless run</summary>

```json

CodeceptJS v0.6.3
Using test root "/home/developer/dev/dx-nuflo/tests/acceptance"

Top level-routes --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook WebDriverIO._beforeSuite()
 a page to add a new encounter should be rendered
 > [Session] Starting singleton browser session
   [2] Starting recording promises
   Emitted | test.before
   [2] Queued | hook WebDriverIO._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "/encounter/new")
   [2] Queued | amOnPage: "/encounter/new"
   Emitted | step.after (I am on page "/encounter/new")
   [2] Queued | return step result
   Emitted | step.before (I see "LOGG INN")
   [2] Queued | see: "LOGG INN"
   Emitted | step.after (I see "LOGG INN")
   [2] Queued | return step result
   [2] Queued | fire test.passed
   [2] Queued | finish test
   Emitted | step.start (I am on page "/encounter/new")
 • I am on page "/encounter/new"
   Emitted | step.start (I see "LOGG INN")
 • I see "LOGG INN"
   Emitted | test.passed ([object Object])
 ✓ OK in 22317ms

   Emitted | test.after
   [2] Queued | hook WebDriverIO._after()
 > [Session] cleaning cookies and localStorage
 fooScen
   [3] Starting recording promises
   Emitted | test.before
   [3] Queued | hook WebDriverIO._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "/encounter/new")
   [3] Queued | amOnPage: "/encounter/new"
   Emitted | step.after (I am on page "/encounter/new")
   [3] Queued | return step result
   Emitted | step.before (I see "FOOLOGG INN")
   [3] Queued | see: "FOOLOGG INN"
   Emitted | step.after (I see "FOOLOGG INN")
   [3] Queued | return step result
   [3] Queued | fire test.passed
   [3] Queued | finish test
   Emitted | step.start (I am on page "/encounter/new")
 • I am on page "/encounter/new"
   Emitted | step.start (I see "FOOLOGG INN")
 • I see "FOOLOGG INN"
   [3] Error | Error
   [3] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [3] <teardown> Queued | hook WebDriverIO._failed()
   [3] <teardown> Queued | () => done(err)
   [3] <teardown> Stopping recording promises
 > Screenshot has been saved to /home/developer/dev/dx-nuflo/tests/acceptance/output/fooScen.failed.png
 ✖ FAILED in 11599ms

   Emitted | test.after
   [3] <teardown> Queued | hook WebDriverIO._after()
 > [Session] cleaning cookies and localStorage
   [4] Starting recording promises
   Emitted | suite.after ([object Object])
   [4] Queued | hook WebDriverIO._afterSuite()

-- FAILURES:

  1) Top level-routes: fooScen:

      expected web page to include "FOOLOGG INN"
      + expected - actual

      -Innlogging
      -Brukernavn
      -Passord
      -LOGG INN
      +FOOLOGG INN
      
  
  Scenario Steps:
  
  - I.see("FOOLOGG INN") at Test.Scenario (top-level-routes_test.js:18:5)
  - I.amOnPage("/encounter/new") at Test.Scenario (top-level-routes_test.js:14:5)
  
  Error
      at Object.<anonymous> (/home/developer/dev/dx-nuflo/node_modules/codeceptjs/lib/helper/WebDriverIO.js:1129:51)
      at Object.exec (/home/developer/dev/dx-nuflo/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (/home/developer/dev/dx-nuflo/node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at /home/developer/dev/dx-nuflo/node_modules/webdriverio/build/lib/webdriverio.js:538:32
      at _fulfilled (/home/developer/dev/dx-nuflo/node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (/home/developer/dev/dx-nuflo/node_modules/q/q.js:883:30)


  FAIL  | 1 passed, 1 failed   // 34s
   Emitted | global.result ([object Object])


real	0m44.973s
user	0m0.992s
sys	0m0.068s

```

</details>

<details>
<summary>verbose output from normal (non-headless) run</summary>

```
CodeceptJS v0.6.3
Using test root "/home/developer/dev/dx-nuflo/tests/acceptance"

Top level-routes --
   [1] Starting recording promises
   Emitted | suite.before ([object Object])
   [1] Queued | hook WebDriverIO._beforeSuite()
 a page to add a new encounter should be rendered
 > [Session] Starting singleton browser session
   [2] Starting recording promises
   Emitted | test.before
   [2] Queued | hook WebDriverIO._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "/encounter/new")
   [2] Queued | amOnPage: "/encounter/new"
   Emitted | step.after (I am on page "/encounter/new")
   [2] Queued | return step result
   Emitted | step.before (I see "LOGG INN")
   [2] Queued | see: "LOGG INN"
   Emitted | step.after (I see "LOGG INN")
   [2] Queued | return step result
   [2] Queued | fire test.passed
   [2] Queued | finish test
   Emitted | step.start (I am on page "/encounter/new")
 • I am on page "/encounter/new"
   Emitted | step.start (I see "LOGG INN")
 • I see "LOGG INN"
   Emitted | test.passed ([object Object])
 ✓ OK in 2748ms

   Emitted | test.after
   [2] Queued | hook WebDriverIO._after()
 > [Session] cleaning cookies and localStorage
 fooScen
   [3] Starting recording promises
   Emitted | test.before
   [3] Queued | hook WebDriverIO._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I am on page "/encounter/new")
   [3] Queued | amOnPage: "/encounter/new"
   Emitted | step.after (I am on page "/encounter/new")
   [3] Queued | return step result
   Emitted | step.before (I see "FOOLOGG INN")
   [3] Queued | see: "FOOLOGG INN"
   Emitted | step.after (I see "FOOLOGG INN")
   [3] Queued | return step result
   [3] Queued | fire test.passed
   [3] Queued | finish test
   Emitted | step.start (I am on page "/encounter/new")
 • I am on page "/encounter/new"
   Emitted | step.start (I see "FOOLOGG INN")
 • I see "FOOLOGG INN"
   [3] Error | Error
   [3] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [3] <teardown> Queued | hook WebDriverIO._failed()
   [3] <teardown> Queued | () => done(err)
   [3] <teardown> Stopping recording promises
 > Screenshot has been saved to /home/developer/dev/dx-nuflo/tests/acceptance/output/fooScen.failed.png
 ✖ FAILED in 1299ms

   Emitted | test.after
   [3] <teardown> Queued | hook WebDriverIO._after()
 > [Session] cleaning cookies and localStorage
   [4] Starting recording promises
   Emitted | suite.after ([object Object])
   [4] Queued | hook WebDriverIO._afterSuite()

-- FAILURES:

  1) Top level-routes: fooScen:

      expected web page to include "FOOLOGG INN"
      + expected - actual

      -Innlogging
      -Brukernavn
      -Passord
      -LOGG INN
      +FOOLOGG INN
      
  
  Scenario Steps:
  
  - I.see("FOOLOGG INN") at Test.Scenario (top-level-routes_test.js:18:5)
  - I.amOnPage("/encounter/new") at Test.Scenario (top-level-routes_test.js:14:5)
  
  Error
      at Object.<anonymous> (/home/developer/dev/dx-nuflo/node_modules/codeceptjs/lib/helper/WebDriverIO.js:1129:51)
      at Object.exec (/home/developer/dev/dx-nuflo/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (/home/developer/dev/dx-nuflo/node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at /home/developer/dev/dx-nuflo/node_modules/webdriverio/build/lib/webdriverio.js:538:32
      at _fulfilled (/home/developer/dev/dx-nuflo/node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (/home/developer/dev/dx-nuflo/node_modules/q/q.js:883:30)


  FAIL  | 1 passed, 1 failed   // 4s
   Emitted | global.result ([object Object])


real	0m4.879s
user	0m0.768s
sys	0m0.088s

```

</details>

#### Test source code

```javascript

Feature('Top level-routes');

Scenario('a page to add a new encounter should be rendered', (I) => {
  I.amOnPage('/encounter/new');
  I.see('LOGG INN');
});

// just to see how a failing test looks
Scenario('fooScen', (I) => {
  I.amOnPage('/encounter/new');
  I.see('FOOLOGG INN');
});
```

### Details

* CodeceptJS version: 0.6.3
* NodeJS Version: 8.1.2
* Operating System: Ubuntu 16.04 LTS
* WebDriverIO: 4.8.0
* Configuration file:

<details>
<summary>This is my configuration:</summary>

```json
{
  "tests": "./*_test.js",
  "timeout": 5000,
  "output": "./output",
  "helpers": {
    "WebDriverIO" : {
      "browser": "chrome",
      "desiredCapabilities": {
          "browserName": "chrome",
          "chromeOptions": {
              "args": [
                  "headless",
                  "disable-gpu"
              ]
          }
      },
      "windowSize": "320x568",
      "restart": false,
      "timeouts": {
        "script": 10000,
        "page load": 3000,
        "implicit" : 5000
      },
      "url": "http://localhost:23450"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "acceptance tests",
  "windowSize": "320x568"
}
```

</details>

**Comment by laurentpayot** [comment]
@fatso83 Did you try with node < 8 such as 7.10.0?

**Comment by fatso83** [comment]
Tried with Node 7.4.0. Still a lot slower.

A test run took 26 seconds with the non-headless browser and 1m5s with `--headless`. Not 10x slow, but at least 4x slower (probably due to more page loading in these tests, obscuring performance).

**Comment by DavertMik** [comment]
Thanks, I will investigate this issue

**Comment by DavertMik** [comment]
I reproduced the issue but I still have no clue what's wrong.
Just changing Chrome from headless to window makes test run much faster. Can this be caused because by `disable-gpu` flag? I don't know. Probably headless Chrome is not so stable enough

**Comment by Setitch** [comment]
I see the same slowness with and without --dissable-gpu so thats not the case. When i connect to the headless i see SO MANY ssl warning and so on - i think its just due to that.

**Comment by DavertMik** [comment]
Thanks. Maybe this could be the case

**Comment by mogryo** [comment]
Hey. Is there any updates on this issue? We've ran into similar problem on some of our machines. Our tests just timeout because of the enormous time it takes for headless chrome to do what we ask. And  if launched not in headless it runs smooth. 

We ran into this problem on windows 7. With latest driver 2.33 and latest chrome. But it's very random. On other machines with the same configuration it runs perfectly in headless (well, not exactly perfectly, but only ~1.5x times slower). Perhaps you have an idea what should we check on these machines? to pin point the mystical difference between them.

**Comment by emesterhazy** [comment]
Also experiencing extremely slow load times when using Chrome in headless mode in Windows 7 with the latest version of Chromedriver, Chrome, and Selenium. Interestingly I'm not having any issues on Windows 10.

**Comment by JamesMilnerUK** [comment]
I'm coming at this from a different place, but interestingly there's an open issue on ChromeDriver which sounds suspiciously related: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2054&q=jenkins&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by laskeym** [comment]
I'm in the same boat as @emesterhazy .  I currently have Chrome Version 63.0.3239.132 and ChromeDriver 2.35 on Windows 7 and headless hangs up on retrieving the sites.  When I come home from work, I'll mess around with this on my Debian 9 and Windows 10 machine and report the results.

Simple test of retrieving the Facebook home page and grabbing  login forms:
**Windows 7:**
- Headless = 111.667s
- Non-Headless = 3.018s

**Comment by oligee80** [comment]
Try these two ChromeOptions:
```
options.addArguments("--proxy-server='direct://'");
options.addArguments("--proxy-bypass-list=*");
```
I dunno in wich forum it was but this did the trick for me

**Comment by hYpac0w** [comment]
@oligee80 THANK YOU SO MUCH!
These options finally got headless chrome working for me :)

**Comment by Resh5** [comment]
@oligee80 Thanks much!!! It worked for me as well.

**Comment by yashwanth2804** [comment]
@oligee80  Really thank you buddy, I have been breaking my head for that issue,

**Comment by krrahulmanikanta** [comment]
I am trying this on win 10. After adding the arguments that @oligee80 has mentioned, I do not see any difference. Is there something else that I should be doing?

**Comment by Resh5** [comment]
@krrahulmanikanta Is your Chrome version compatible?

**Comment by krrahulmanikanta** [comment]
@Resh5 Yes, I am using chromedriver v2.38 and my chrome is of v66

**Comment by Resh5** [comment]
@krrahulmanikanta It workes fine for me . But I am in Windows7
   System.setProperty("path to driver);
		  ChromeOptions chromeOptions = new ChromeOptions();
		  chromeOptions.addArguments("--headless");
		  chromeOptions.addArguments("window-sized1200,600");
		  chromeOptions.addArguments("--proxy-server='direct://'");
		  chromeOptions.addArguments("--proxy-bypass-list=*");
		  ChromeDriver driver = new ChromeDriver(chromeOptions);

**Comment by Robula** [comment]
I'm seeing a similar issue using Puppeteer and Chromium (no WebDriver), the proxy arguments do not seem to make a difference in my case. This may be an issue related to Chromium.

**macOS:** 10.13.4
**Node:** 8.10.0
`headless: true` results in `7747.209ms`
`headless: false` results in `4775.771ms`

**Comment by oppahansi** [comment]
@oligee80 Thanks

**Comment by pardovot** [comment]
> Try these two ChromeOptions:
> 
> ```
> options.addArguments("--proxy-server='direct://'");
> options.addArguments("--proxy-bypass-list=*");
> ```
> 
> I dunno in wich forum it was but this did the trick for me

Don't know if you'll actually see this, but it seems like the following solved the issue for me: options.addArguments("--proxy-server=");
The question is, why? I'm running the simplest code ever which is something like:
new WebDriver, driver.get("https://www.google.com").
This takes around 2 minutes, and solved be that argument, but I really can't understand what exactly it does..
Thanks! :)

**Comment by GeorgeDubuque** [comment]
I am having a similar issue on this one still. I tried with the following arguments 
```
options.add_argument("--proxy-server='direct://'")
options.add_argument("--proxy-bypass-list=*")
options.add_argument("--proxy-server=")
```
I am still not seeing any speed up. 40 seconds to run in headless and 4 seconds to run in windowed mode. I am running ChromeDriver 75.0.3770.140.

Please let me know if anyone solves this one! Could really help me out. All I am doing is calling ```driver.get("https://www.google.com")```

**Comment by GeorgeDubuque** [comment]
> I am having a similar issue on this one still. I tried with the following arguments
> 
> ```
> options.add_argument("--proxy-server='direct://'")
> options.add_argument("--proxy-bypass-list=*")
> options.add_argument("--proxy-server=")
> ```
> 
> I am still not seeing any speed up. 40 seconds to run in headless and 4 seconds to run in windowed mode. I am running ChromeDriver 75.0.3770.140.
> 
> Please let me know if anyone solves this one! Could really help me out. All I am doing is calling `driver.get("https://www.google.com")`

Ok so after looking into it a bit more it seems that avoiding using headless chrome is the solution for me. Instead I use the pyvirtualdisplay library and set its visibilty to false. This sped up my performance 10x. Here is the code:
```
from selenium import webdriver
from pyvirtualdisplay import Display
import time

start = time.time()
display = Display(visible=0, size=(800, 600))
display.start()
driver = webdriver.Chrome(
        "/home/george/Desktop/chromedriver")
driver.get("https://www.google.com")
driver.quit()
display.stop()
end = time.time()
print(end-start)
```
with output:
```
5.253071069717407
```
instead of:
```
42.1179986000061
```

**Comment by HansHagberg** [comment]
Was searching for solution to a similar problem so I'm adding a note for reference:

Running a test scenario with headless Chromium and 100 instances. Machine is an AMD 2950X with 16 phys cores @4 GHz, 128 GB RAM and an Nvidia GTX 1660 GPU on Windows 10. This machine turns into a sluggish mess when running this with GPU-disabled in chromium startup. With GPU enabled, response is acceptable. With 200 clients, machine goes very sluggish (useless) again even with GPU.

With 200 instances, GPU utilization is very low (<10%) and CPU is ~35%
Task manager says 17300 threads and 420000 handles.

It seems to be some windows resource causing degradation because when doing a remote login session with another account while the load is running, the new session has no problems with response. So it looks like Windows and not the hardware being the bottleneck. Contemplating trying with Windows server to see if that helps.

**Comment by 3590Duncan** [comment]
I have experienced this, but with Electron. Here are some screenshots from my headed vs headless run in Electron. The spec has 3 tests in it. Completes in 53 seconds headed and 1:52 Headless
<img width="768" alt="Screen Shot 2019-09-27 at 1 45 10 PM" src="https://user-images.githubusercontent.com/49245425/65801102-201c1500-e12d-11e9-9663-4f4cf0bc485c.png">
<img width="445" alt="Screen Shot 2019-09-27 at 1 42 35 PM" src="https://user-images.githubusercontent.com/49245425/65801122-2c07d700-e12d-11e9-9ea7-a7f914252844.png">

**Comment by wilsonweb** [comment]
I saw some people get this to work and others do not have any success with it:

```
chromeOptions.addArguments("--proxy-server='direct://'");
chromeOptions.addArguments("--proxy-bypass-list=*");
```

I did not have success at first ether, then I looked at my code and realized that I have called setChromeOptions() more than one time and wondered if options are getting over-written. I moved things around to make only one call to `setChromeOptions()` and it worked.


```
var $driver = require("selenium-webdriver");
let chrome = require("selenium-webdriver/chrome");

const chromeOptions = new chrome.Options();//.headless();
chromeOptions.addArguments("--headless"); 
chromeOptions.addArguments("--proxy-server='direct://'");
chromeOptions.addArguments("--proxy-bypass-list=*");
chromeOptions.addArguments("window-size=1024,1324");
chromeOptions.addArguments("--blink-settings=imagesEnabled=false"); 

var $browser = new $driver.Builder()
	.forBrowser("chrome")
	.setChromeOptions(chromeOptions) 
	.withCapabilities(capabilities)
	//.forBrowser('firefox')
	.build();

```
You can ignore the lines dealing with hiding images, windows size etc. if you choose.

**Comment by zjhgx** [comment]
in my case, add the following argument solve my problem
` chrome_options.add_argument('blink-settings=imagesEnabled=false')`

**Comment by mikemangas** [comment]
> 

Where do you insert this?

**Comment by mys1erious** [comment]
Only thing that worked for me is adding UserAgent to the options:
`options.add_argument("user-agent=Chrome/110.0.5481.77")`
