### ISSUE TITLE
Support for mouseDown, mouseMove, and mouseUp

### ISSUE THREAD

**Issue by hanthomas** [codeceptjs/CodeceptJS#62]
While click and rightClick works for most cases, we also need to be able to perform additional mouse functions to simulate drag and drop.

**Comment by DavertMik** [comment]
Thanks for the idea. I think the overall implementation is pretty simple and you can get done it yourself and send a PR. We use WebdriverIO as backend, and they have all those methods implemented in nice manner. I think they have even drag-and-drop thing. And you can submit pull request with adding those methods to CodeceptJS. All you need to write them in analogy with `rightClick` or `doubleClick` (i.e. to allow usage of strict locators and wrapping promises).

I will be glad to merge it

**Comment by hanthomas** [comment]
Seems simple enough.  I noticed that the docs mention being able to extend WebDriverIO via custom helpers.  So, I was heading down that path.  But, this functionality seems generic enough to create a PR so others can benefit.

**Comment by DavertMik** [comment]
Yes, sure, generic solved issues are welcome. That's the mission of CodeceptJS - to solve common issues in nice way )

**Comment by DanielRuf** [comment]
I think this is still relevant.
