### ISSUE TITLE
multiple Appium configs

### ISSUE THREAD

**Issue by michahell** [codeceptjs/CodeceptJS#630]
Is it currently possible to have more than one Appium helper config?
We tried specifying `multiremote`, but the Appium helper does not know that command (we guessed it might since appium also builds on top of webdriverIO).

Inversely, Is it possible to use a WebDriverIO helper specifying Appium configs there in a multiremote block?

**Comment by DavertMik** [comment]
Not yet but I think this can be implemented soon.
You know, that was the first release including Appium so we couldn't manage to include everything

**Comment by APshenkin** [comment]
@michahell BTW, did you try `multiremote` with Appium and WebdriverIO. Is it working OK?
I'm worry that this will not work so great as http://codecept.io/advanced/#multiple-execution. In multiple execution each configuration runs in separate process and can't affect others configurations.
What you think about it?

**Comment by eduardofinotti** [comment]
@michahell @APshenkin I use scripts in my package.json override the Appium configuration:

`"scripts": {
"Android-8.1": "codeceptjs run -c ./devices_config/android.json --override '{\"helpers\": {\"Appium\": { \"desiredCapabilities\": {\"deviceName\": \"emulator-5554\", \"platformVersion\": \"8.1\", \"autoGrantPermissions\": true,  \"customName\": \"Nexus 6\" }}}}'"
},`
