### ISSUE TITLE
how to check iframe height in nightmare

### ISSUE THREAD

**Issue by tvinerkar** [codeceptjs/CodeceptJS#642]
#### What are you trying to achieve?
verify iframe height
#### What do you get instead?
I.grabCssPropertyFrom is not function
> Provide console output if related. Use `--verbose` mode for more details.
I.grabCssPropertyFrom('#make-taller', 'height');
```bash
# paste output here
```

> Provide test source code if related

```php
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by APshenkin** [comment]
@tvinerkar `grabCssPropertyFrom` is supported only for WebdriverIO now. You can try to create custom helper and then share it with us, so we will add it to main code
