### ISSUE TITLE
Is there a way to restart the browser in the middle of the test?

### ISSUE THREAD

**Issue by siddharthdhar** [codeceptjs/CodeceptJS#677]
#### What are you trying to achieve?
My Test Scenario: Login with User 1 and create some data. As a part of same test, logout and login with User 2 to view the data. I am using Google's authentication api. 
#### What do you get instead?
In the test, if I am logged in as User 1 and once I logout, I cannot login with User 2 in the same chrome browser session unless the browser is restarted. Google's authentication redirects me to User 1 profile automatically without taking me to the authentication window. To be able to run my tests, I need to restart the window in the middle of the test. Protractor gives an option to restart the window, but I am unable to use it as a Helper method as once the browser window is restarted by Protractor, codeceptjs errors out.
> Provide console output if related. Use `--verbose` mode for more details.

```bash
"after each" hook: finialize codeceptjs for "Group Admin should be able to create a Private Radar" in 3ms
NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

1) Add and View Radars: Group Admin should be able to create a Private Radar:
     no such session
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.12.6 x86_64)
```

> Provide test source code if related

```js
class BrowserHelper extends Helper {
  restartBrowser() {
    let client = this.helpers['Protractor'].browser;
    client.restart();
  }
}
```

### Details

* CodeceptJS version: 1.0.0
* NodeJS Version: 6.9.4
* Operating System: OSX
* Protractor || WebDriverIO || Nightmare version (if related) : Protractor 5.1.2
* Configuration file:

```js
# paste suite config here
```

**Comment by APshenkin** [comment]
@siddharthdhar Currently there is no abylity to restart browser manualy, but I think this is a good feature.
