### ISSUE TITLE
I.see() doesn't have comprehensive fail description

### ISSUE THREAD

**Issue by BorisOsipov** [codeceptjs/CodeceptJS#714]
#### What are you trying to achieve?
I write code like :
```js
I.see(4, {css: '.someclass'})
```
When test fails I want to know why it fails from console output.
#### What do you get instead?
I got message
```bash
expected element {css: '.someclass'} to include "5"
```
No information what went wrong. Is element empty or may be has text "4"?
I can't understand what wrong with my system under test.

#### What I would like to get?
Something like that:
```bash
+ expected: element {css: '.someclass'} to include "5"
- actual: element {css: '.someclass'}  includes "66"
```

### Details

* CodeceptJS version: 1.0.2
* WebDriverIO

**Comment by DavertMik** [comment]
what if there are more than one element for .someclass?
But yeah, output can be improved

**Comment by BorisOsipov** [comment]
>>What if there are more than one element for .someclass?
Take the first. It's tests author problem when he is writing such weak locators.

>>what if output is very very long?
"640 K ought to be enough for anybody." (с)
We can cut original text and add message that it was done. I don't have ideas...

>>I.see('*', 'div');
>> It will scan for all divs on page and will list all its internal texts! What a mess.
Yep, I realize that underhood we need to get all page element's texts in such a case. It also will lead to bad perfomance due additional communication selenium--browser(
It is trade off between ability to write weak locators(like location by text) and getting the best assert output...

**Comment by BorisOsipov** [comment]
Seems already implemented or not actual. thx
