### ISSUE TITLE
Data Driven Tests

### ISSUE THREAD

**Issue by MitkoTschimev** [codeceptjs/CodeceptJS#726]
#### What are you trying to achieve?

Thanks for the Data Driven Tests which are really cool but i already reached a point which is not supported.
Our tests are only starting one session per feature and the scenarios are depending each other. Why we are doing this? Because e.g. login and logout takes to much time and we do it once per feature. So if we want to use Data Driven Tests than we need the same feature set on Feature level and the current argument should be than injectable in all scenarios and maybe even Before, BeforeSuite, ...

It is not a bug it is more a proposal ;)

Do you have any plans to introduce this kind of feature?

**Comment by APshenkin** [comment]
@tfiwm Yes, looks like good enhancement, but I can't give you any estimates for implementing

**Comment by kardosgreenjade** [comment]
This still seems to be an issue, curious why it was closed?

**Comment by kardosgreenjade** [comment]
@DavertMik Hello, I have hit the same problem in the most recent version, I can't inject the current data into the Before/After hooks. Has this been solved otherwise?

**Comment by DavertMik** [comment]
Please create a new issue and describe it, this is 5 years old so probably not so relevant
