### ISSUE TITLE
I.attachfile function not working after implementing SmartWait in codecept.json

### ISSUE THREAD

**Issue by ninpop25** [codeceptjs/CodeceptJS#734]
#### What are you trying to achieve?
I implemented SmartWait in my codecept.json file like below.
 I applied SmartWait in my Codecept.json like below , but the issue is that after implementing it I.attachfile function [I.attachFile("input.dz-hidden-input","TestForms.xsn");] is not working.

"WebDriverIO": {
"url": "https://formsviewertest.azurewebsites.net",
"browser": "chrome",
"windowSize":"maximize",
"restart": "true",
"smartWait": 90000,
"timeouts": {
"script": 90000,
"page load": 90000,
"implicit": 90000,
"explicit": 90000
}
},

#### What do you get instead?
After this I.attachfile [I.attachFile("input.dz-hidden-input","TestForms.xsn");] is not working.
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```
     ESOCKETTIMEDOUT

  Scenario Steps:

  - I.attachFile("input.dz-hidden-input", "#44689-Version Test.xsn") at Test.<a
onymous> (testplan\fv_versionTest_test.js:13:7)

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```
**Note** : nothing happens and code is stuck

**Comment by DavertMik** [comment]
Sorry I need some time to reproduce and investigate it.

**Comment by ninpop25** [comment]
@DavertMik : thanks for replying :)

I will be waiting for your response with solution as I am stuck on this issue and not able to move ahead in my project

**Comment by ninpop25** [comment]
@DavertMik : did you found any solution to issue that I described?

**Comment by ninpop25** [comment]
@APshenkin : please look into this issue asap
@DavertMik : did you find any solution to it?

**Comment by ninpop25** [comment]
@DavertMik @APshenkin : is there a way to get rid of this issue?

**Comment by akshay-agrawal04** [comment]
+1

**Comment by nsm1363** [comment]
+1

**Comment by BrunoExterckotter** [comment]
+1

**Comment by LukoyanovE** [comment]
Could anybody give a code example for failing test?
I cannot reproduce it on google search by image. File could be attached by `I.attachFile("//input[@type='file']", "kitty.jpg");`

Cannot find "input.dz-hidden-input" on "https://formsviewertest.azurewebsites.net" from issue code
