### ISSUE TITLE
Request: Decouple config file location and test root

### ISSUE THREAD

**Issue by lennym** [codeceptjs/CodeceptJS#767]
#### What are you trying to achieve?

We have a number of projects using codecept, and they load a shared config file, which we keep in an npm module for easy sharing across our projects.

However, we recently upgraded codecept due to the issues in 0.5.x with it exiting with a 0 exit code when the test code errors, and now the test root is set to the location of that config file with no way to override it.

It would be good if the test root was configurable in some way, either from a command line flag, or a property in codecept.conf.js

**Comment by DavertMik** [comment]
Looks like a good idea. Thanks for pointing
