### ISSUE TITLE
Intercept and modify contents of a request header

### ISSUE THREAD

**Issue by kamblehr** [codeceptjs/CodeceptJS#776]
#### What are you trying to achieve?
I wanted either to write own or custom api to intercept and modify contents of a request at various stages. Something like https://www.npmjs.com/package/nightmare-webrequest-addon.

#### What do you get instead?
Code is not getting executed.

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

var Nightmare = this.helpers["Nightmare"];
         Nightmare.Nightmare.action('onBeforeSendHeaders', function (name, options, parent, win, renderer, done) {
             debugger;
     
             //parent.on('onBeforeSendHeaders', function () {
                 //debugger;
                 win.webContents.session.webRequest.onBeforeSendHeaders(['*://!*./!*'], function(details, callback) {
                     debugger;
                    details.requestHeaders['User-Agent'] = 'MyAgent';
                    callback({cancel: false, requestHeaders: details.requestHeaders});
                });
             //});
         });

```js
// paste test
```

### Details

* CodeceptJS version: 1.0.3
* NodeJS Version: 6.9.1
* Operating System: macOS Sierra
* Protractor || WebDriverIO || Nightmare version (if related): Nightmare -- ^2.7.0
* Configuration file:

```js
# paste suite config here
```

But somehow it is not  .action() getting called. Am I missing anything or doing wrong?

Thanks in advance..!

-Harshal

**Comment by DavertMik** [comment]
Sorry, Nightmare's code is really complicated so I couldn't suggest you anything... :|
