### ISSUE TITLE
Custom Runner Error

### ISSUE THREAD

**Issue by zerocowl** [codeceptjs/CodeceptJS#838]
#### What are you trying to achieve?
Run a test with a function  
#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
```

> Provide test source code if related

```js
let Container = require('codeceptjs').container;
let Codecept = require('codeceptjs').codecept;

let config = { helpers: { WebDriverIO: { browser: 'chrome', url: 'http://localhost' } } };
let opts = { steps: true };

// create runner
let codecept = new Codecept(config, opts);

// create helpers, support files, mocha
Container.create(config, opts);

// initialize listeners
codecept.bootstrap();

// load tests
codecept.loadTests('*_test.js');

// run tests
codecept.run();
```

### Details

* CodeceptJS version: 1.1
* NodeJS Version: 8.9.3
* Operating System: Windows 10
* Puppeteer: ^0.13.0
* Configuration file:

**Comment by erdem-atg** [comment]
Our first pages of the SUT's are jsf but rest of all are angular. We are starting the automation with webdriverio helper, afterward we want to change our helper as protractor in runtime-code.

We tried to change the helper by writing custom runner code (mentioned above) in after method of the page test.
We have the same issue. We were thinking that we are writing the code in wrong place but it seems as if it is an issue. 

Solution and guidence will be appreciated :)

**Comment by zerocowl** [comment]
Hi!
I solved this way:
`const Codecept = require('codeceptjs').codecept
const fs = require('fs')
const path = require('path')
let codecept = null

const config = { helpers: { WebDriverIO: { browser: 'chrome', url: 'http://localhost' } }, tests: './*_test.js' }
const opts = { steps: true }

// validation path optional
const getRoot = function (currentPath) {
  if (!currentPath) currentPath = '.'
  if (!path.isAbsolute(currentPath)) currentPath = path.join(process.cwd(), currentPath)
  currentPath = fs.lstatSync(currentPath).isDirectory() || !path.extname(currentPath) ? currentPath : path.dirname(currentPath)
  return currentPath
}

const root = getRoot('./')

try {
  codecept = new Codecept(config, opts)
  codecept.init(root, (err) => {
    if (err) throw new Error(`Error while running bootstrap file :${err}`)
    codecept.loadTests()
    codecept.run()
  })
} catch (err) {
  console.log(err.message)
  process.exit(1)
}
`

**Comment by erdem-atg** [comment]
Hi,
@zerocowl;  
It's giving following error: Cannot find module 'codeceptjs'
We have writtin sutom runner code into //Page/deneme.js git() function and called git() function inside //"/spec/test.js".   
"hooks": ["./Page/deneme.js"] code added to codeceptjs.json

What is wrong?

//codecept.json
{
  "tests": "./spec/test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://www.nightmarejs.org",
      "browser": "chrome",
       "restart": "true"
    }
  },
  "hooks": [
    "./Page/deneme.js"
  ],
  "include": {
    "I": "./steps_file.js",
   "login": "./Page/login.js",
   "deneme": "./Page/deneme.js",
     },
  "bootstrap": false,
  "mocha": {},
  "name": "Desktop"
}

////////////////////
//Page/deneme.js

'use strict';
let I;

module.exports = {

  _init() {
    I = actor();
  },

git(){
  const Codecept = require('codeceptjs').codecept
  const fs = require('fs')
  const path = require('path')
  let codecept = null

  const config = { helpers: { WebDriverIO: { browser: 'chrome', url: 'http://www.nightmarejs.org/' } }, tests: './test.js' }
  const opts = { steps: true }

  // validation path optional
  const getRoot = function (currentPath) {
    if (!currentPath) currentPath = '.'
    if (!path.isAbsolute(currentPath)) currentPath = path.join(process.cwd(), currentPath)
    currentPath = fs.lstatSync(currentPath).isDirectory() || !path.extname(currentPath) ? currentPath : path.dirname(currentPath)
    return currentPath
  }
  const root = getRoot('./')
  try {
    codecept = new Codecept(config, opts)
    codecept.init(root, (err) => {
      if (err) throw new Error(`Error while running bootstrap file :${err}`)
      codecept.loadTests()
      codecept.run()
    })
  } catch (err) {
    console.log(err.message)
    process.exit(1)
  }
}
}

//////////////////
//"/spec/test.js",

Feature('Login Tests');
Before((I) => { // or Background
  I.amOnPage('http://www.nightmarejs.org');
I.wait(1);
});

Scenario('Happy path login with custom runner', (I, login, deneme) => {
  deneme.git();
});

**Comment by zerocowl** [comment]
Let's see ...
Your test path in config should be the location of your test files
or you can add the file in the method call `run ()`.
Validate if the module is installed too, maybe that's exactly what it is.

Like that => `codecept.run('./spec/test.js')`

**Comment by erdem-atg** [comment]
Hi, yes test path is the location of test file.
It already works fine if "require('codeceptjs')" code is not called. 
When "const Codecept = require('codeceptjs').codecept" code segment is removed there is no problem...

Maybe there is a problem to reach codeceptjs API and so [require('codeceptjs').codecept]. Is there anything should we do to install codeceptJS API to project. *codeceptjs is already installed on local.

Can you write your working code as above: json file content, hook file that codecept object is called, test file and any toher related code segment.
Thanks.

**Comment by zerocowl** [comment]
Ok....
Important: **JSON config** and **defaultConfig** are the same thing.
My code: https://gist.github.com/001a31700c776e1b255b379a7b15c0c6.git

**Comment by erdem-atg** [comment]
It is ok, thanks :) 
Actually related code matters; 
1. runner.js what is the path of the file in project?
2. json config-hook definition of the file, is it like: "hooks": ["./runner.js"], 
3. test.js file code that you call the runner.js code to change the helper...

**Comment by zerocowl** [comment]
**Folders:**

> - execTest
>       - runner.js
>       - package.json
>       - steps_file.js
>       - cons_test.js

Code: https://gist.github.com/zerocowl/80e2217a6de75826709ace00dec52f56

**Comment by erdem-atg** [comment]
Where are you calling/executing runner.js (custom runner) code? It seems as if It isn't called/executed in this scenario.

In "cons_test.js" file after "I.see('Home')"command helper should be changed-runner.js code should be called in a method (before next page).
