### ISSUE TITLE
Is it possible to link test.title with step.name inside _afterStep?

### ISSUE THREAD

**Issue by ipozhidaev** [codeceptjs/CodeceptJS#841]
Hi,
I'd like to link test.title with step.name after each step.
Similar to:
Scenario-1.Step1
Scenario-1.Step2
If i understood correctly, inside _afterStep i could get only step objects.
But maybe there is a way to do this?
Thanks.

**Comment by DavertMik** [comment]
Yes, `step` does not include `test` object in it. I think you could create a custom listener. You could listen for `event.test.before` and get a current test object there and then listen for `event.step.after` to get the current step. Here is documentation on that http://codecept.io/hooks/#custom-hooks

I think you can learn this from our steps listener https://github.com/Codeception/CodeceptJS/blob/master/lib/listener/steps.js
