### ISSUE TITLE
config "desiredCapabilities" is ignored in "multiple" "browsers" unless also defined in "helpers" "WebDriverIO"

### ISSUE THREAD

**Issue by jamie-beck** [codeceptjs/CodeceptJS#850]
#### What are you trying to achieve?

I would like to define different "desiredCapabilities" for each browser in multiple.

#### What do you get instead?

"desiredCapabilities" is completely ignored in "multiple" "browsers" config unless "desiredCapabilities" is also defined in "helpers" "WebDriverIO".

### Details

* CodeceptJS version: 1.1.1
* NodeJS Version: 8.9.3
* Operating System: Windows 10

**Comment by Nazanin1369** [comment]
I'd like to take this enhancement

**Comment by LukoyanovE** [comment]
@Nazanin1369 , @jamie-beck 
What a purpose of this enhancement?

If You don't want to use desiredCapabilities, just don't use it both in multiple and WebDriverIO sections.

Each of multiple desiredCapabilities just extends default (in WebDriverIO section).
If it empty, it would use only desiredCapabilities in multiple.

For example:
First browser ("chrome") will use all from WebDriverIO.desiredCapabilities.
Second - WebDriverIO.desiredCapabilities + its own desiredCapabilities.
Third - WebDriverIO.desiredCapabilities + its own desiredCapabilities + overrides described in WebDriverIO.desiredCapabilities:
```
            "ignoreHTTPSErrors": false,
            "acceptInsecureCerts": false,
```

```
"multiple": {
    "basic": {
      "browsers": [
        "chrome",
        {
          "browser": "safari",
          "desiredCapabilities": {
            "os": "OS X",
            "os_version": "High Sierra",
            "resolution": "maximize"
          }
        },
        {
          "browser": "chrome",
          "desiredCapabilities": {
            "os": "OS X",
            "os_version": "High Sierra",
            "resolution": "maximize",
            "ignoreHTTPSErrors": false,
            "acceptInsecureCerts": false,
          }
        }
      ]
    }
  },
  "helpers": {
    "WebDriverIO": {
      "url": "https://hidden.com/",
      "browser": "Chrome",
      "user": "hidden",
      "key": "hidden",
      "desiredCapabilities": {
        "browserstack.local": false,
        "browserstack.video": true,
        "ignoreHTTPSErrors": true,
        "acceptInsecureCerts": true,
        "acceptInvalidCerts": true,
        "acceptSslCerts": true
      }
    }
  },
```
