### ISSUE TITLE
Support puppeteer.connect

### ISSUE THREAD

**Issue by marci4** [codeceptjs/CodeceptJS#862]
#### What are you trying to achieve?

The puppeteer api allows you to use an already running instance instead of always launching a new one.
In some enviroments it is not possible to launch a new instance every time, e.g. if you have a application with CefSharp using registered js objects.

[API-documentation for puppeteer.connect](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions)

#### What do you get instead?

Right now, you can only launch a new instance with the PuppeteerHelper

### Details

* CodeceptJS version: 1.1.1
* NodeJS Version: v.8.9.2
* Operating System: Win7

# EDIT:
There are some changes with pupeteer v.0.13.0 !!
`browser.close now closes Chromium even if used with pupeteer.connect`

**Comment by DavertMik** [comment]
Thanks, that should be implemnted

**Comment by nareshgnT** [comment]
Any update this issue. if any help needed i can pitch in.
