### ISSUE TITLE
[feature] React selectors

### ISSUE THREAD

**Issue by FDiskas** [codeceptjs/CodeceptJS#863]
Hi,
it would be nice have something like extra module for testing react aps.
I'ts hard to select react rendered components So this would be great.

thanks
Good example https://github.com/DevExpress/testcafe-react-selectors

**Comment by DavertMik** [comment]
Absolutely agree. We are open to contributions. If you know React you can try to implement that as a package. If you have questions on implementation I'm here, please ask.

**Comment by rosko** [comment]
It seems it's already done in version 2.1.4. 
@DavertMik please, confirm
