### ISSUE TITLE
   invalid element state: Element is not currently intractable and may not be manipulated

### ISSUE THREAD

**Issue by mathis7875** [codeceptjs/CodeceptJS#881]
#### What are you trying to achieve?
Trying to click on element 

#### What do you get instead?
   invalid element state: Element is not currently interactable and may not be manipulated

> Provide test source code if related
I use xpath, css  and text and still get same error above.

I.resizeWindow(1440, 806);
    I.amOnPage('/en-us/login');
    I.click('#btn-login');
    I.click('New Order');
    I.click('Sell');
    I.fillField('volume', 1000000);
    I.click('#order-simple > div > div:nth-child(1) > form > fieldset > div.row.vpad20.center > span:nth-child(1) > button')
    I.click('Submit Order');
    I.wait(3);
    I.see('Insufficient');

### Details

* CodeceptJS version: 1.1
* NodeJS Version: latest
* Operating System: mac sierra high
*  WebDriverIO using stand-alone selenium and chrome driver
* Configuration file:

  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "restart":true,
      "url": 
      "browser": "chrome",
        "desiredCapabilities": {
          "chromeOptions": {
                   "args": ["allow-running-insecure-content"]
          }
      }
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {
    "reporterOptions": {
      "reportDir": "output"
  }
  },
  "name": "testautomation"

**Comment by reubenmiller** [comment]
@mathis7875 Sorry for the late reply. Are you still having issues with this?

It sounds like a problem with the interaction between selenium and the chrome driver, but can you provide the verbose output from your test? (i.e. add `--debug` to the command line when running the test)

**Comment by Nbsaw** [comment]
Same issues when i fillField the input

**Comment by mirao** [comment]
I have the same problem with fillField(), in Chrome only (Firefox works fine).
Tested with Chrome 69, ChromeDriver 2.40, Selenium 3.8.1.
I tried waitForElement() or waitForEnabled() before fillField(), but without success. If I add the absolute delay wait(1) instead, it works well even in Chrome.

**Comment by Orou-dev** [comment]
Ive this issue too using Symfony/Panther as Im trying to test a form. Only solution I found was to use a waitFor(); But It doesnt work everytime I dont kniw why

**Comment by Swetargoenka** [comment]
I am also running into this issue

**Comment by PeterSomora** [comment]
@Swetargoenka did yuu find the solution?

**Comment by artur-sim** [comment]
Hey guys,

in my case front end was on react i guess, and button did not have an id, i have tried so many option and i tried executingJS waiting to executejs, actually it worked but i was still throwing an error , saying that cannot excute click method. so finally i started to read more carefully and found [here](https://codeception.com/docs/03-AcceptanceTests) that there is a special class 

> Codeception\Util\Locator 

 and i can use it with click, so setting my locator to `Codeception\Util\Locator::lastElement('#login-methods-body-user_credentials'))` worked, i hope you can select an option that works for you there.
