### ISSUE TITLE
Cannot create codecept configuration file on Windows

### ISSUE THREAD

**Issue by Francute** [codeceptjs/CodeceptJS#888]
I was trying to do the [quickstart](http://codecept.io/quickstart/) running `codeceptjs init`. After answering every question, there is no codecept configuration file anywhere in the project folder. I tried with all defaults and running through npx too, but configuration file never appears anywhere in the folders tree.

I get no errors or outputs. Everything seems fine, but no configuration file created anywhere.

### Details

* CodeceptJS version: codeceptjs-webdriverio 1.1.0
* NodeJS Version: 8.9.4
* Operating System: **Windows 10 (v. 10.0.16299)**
* Configuration file: _This is the issue..._

**Comment by reubenmiller** [comment]
@Francute Are you still having problems with this?

I would recommend using just the `codeceptjs` package and not the meta packages, as the meta-packages are not updated in the same cylce, plus they will be phased out soon.

Though can you try the following procedure for me? I am going to assume you're in a powershell console on windows (if you are not already using powershell, I can highly recommend it :))
1.Install codeceptjs globally:  `npm install -g codeceptjs`
1. Cd to your desktop (where you will definitely have persmissions): `cd $Env:USERPROFILE\Desktop` 
1. Create a new directory for testing: `mkdir "test-debug"`
1. Cd into the new directory `cd "test-debug"`
1. Init codeceptjs and select all webdriverio and the defaults (i.e. just hit enter): `codeceptjs init`
1. Install webdriverio dependency: `npm install -g webdriverio`
1. Check if the codeceptjs file now exists. `Test-Path "$Env:USERPROFILE\Desktop\test-debug\codecept.json"`. You should get back True to prove that it exists.

Let me know how it goes.
