### ISSUE TITLE
Create one HTML report with mochawesome and run multiple

### ISSUE THREAD

**Issue by frantallukas10** [codeceptjs/CodeceptJS#907]
#### What are you trying to achieve?
Create one HTML report for every test.js file

#### What do you get instead?
https://ibb.co/eyE63x

> codeceptjs run-multiple --all --reporter mocha-multi

```js
Feature('test1')
BeforeSuite(I => {
	console.log('Start testing bla bla bla 1')
})
AfterSuite(I => {
	console.log('Finished testing bla bla bla 1')
})
const scenario1 =
	'@test1|' +
	'bla bla bla 1'
Scenario(scenario1, function*(I) {
I.login('id')...
})
```
// ================
```js
Feature('test2')
BeforeSuite(I => {
	console.log('Start testing bla bla bla 2')
})
AfterSuite(I => {
	console.log('Finished testing bla bla bla 2')
})
const scenario1 =
	'@test2|' +
	'bla bla bla 2'
Scenario(scenario1, function*(I) {
I.login('id')...
})
```
// =============
```js
Feature('test3')
BeforeSuite(I => {
	console.log('Start testing bla bla bla 3')
})
AfterSuite(I => {
	console.log('Finished testing bla bla bla 3')
})
const scenario1 =
	'@test3|' +
	'bla bla bla 3'
Scenario(scenario1, function*(I) {
I.login('id')...
})
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file: 
"dependencies": {
"codeceptjs": "^1.1.3",
"concurrently": "^3.5.1",
"puppeteer": "^1.0.0"
},
"devDependencies": {
"mocha": "^4.1.0",
"mocha-multi": "^0.11.1",
"mocha-junit-reporter": "^1.15.0",
"mochawesome": "^3.0.1",
"mochawesome-report-generator": "^3.1.0"
}

```js
const multipleConfig= {
	test1: {
		grep: '@test1',
		browsers: ['chrome'],
	},
	test2: {
		grep: '@test2',
		browsers: ['chrome'],
	},
	test3: {
		grep: '@test3',
		browsers: ['chrome'],
	},
}
const defaultConfig = {
	tests: './src/tests/**/*.js',
	timeout: 900,
	output: './output',
	helpers: {
		Puppeteer: {
			windowSize: '1280x800',
			browser: 'chrome',
			chrome: {args: ['--no-sandbox', '--disable-setuid-sandbox']},
			url: 'http://localhost',
			uniqueScreenshotNames: false,
			show: false,
			waitForAction: 1000,
			restart: true,
		},
		MyHelpers: {
			require: './helpers/helpers.js',
		},
	},
	mocha: {
		reporterOptions: {
			'mocha-junit-reporter': {
				stdout: '-',
				options: {
					mochaFile: './output/result.xml',
				},
			},
			mochawesome: {
				stdout: './output/console.log',
				options: {
					reportDir: './output',
					reportPageTitle: 'Report page',
					reportFilename: 'report',
					quiet: true,
					json: false,
					html: true,
					overwrite: true,
					inline: true,
				},
			},
		},
	},
	multiple: multipleConfig,
	bootstrap: false,
	include: {},
	name: 'codecept',
}
```

**Comment by reubenmiller** [comment]
I'm not sure that this is worth doing in CodeceptJS.

Have you looked at a Jenkins plugin?  For example I use the [HTML Plublisher Plugin](https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin) in my Jenkins project. It won't combine reports but you can specify more than 1 report, and it will generate a tab per report.

**Comment by cherrieg** [comment]
@reubenmiller  Could you help merge these reports to 1 report when we use the "run-multiple" command?
I think it's worthy to do that because we just wanna check 1 report after running.Thank you very much.

**Comment by Rob-Doherty** [comment]
It would be really useful to have a single report for a parellel test run.

**Comment by lokeshJR** [comment]
Any update on this single report for multiple test runs?

**Comment by gabrielbergmann** [comment]
Would be a great feature, I'm facing the same problema in my project. @DavertMik
