### ISSUE TITLE
Parallel execution of multiple test suites in multiple instances of same browser

### ISSUE THREAD

**Issue by cluehr** [codeceptjs/CodeceptJS#929]
#### What are you trying to achieve?

I'm considering CodeceptJS to use in one of our projects. I'm expecting to have a big number of automated tests there. In a similar project we had around 400, distributed over multiple test suites using the Robot Framework. Executing these tests one after another it takes more than an hour. But in Robot Framework, you can execute test suites in parallel using the `pabot` runner.
Here I found the multiple-execution feature, but as I understand it, it can be used to execute tests in different browsers. I would like to start multiple instances of the same browser. Each instance is then executing one test suite. Can this be done, or do I have to take care of this myself by starting CodeceptJS multiple times with different test suites assigned to be executed?

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by reubenmiller** [comment]
You can use the multi configuration for the same browser, you just have to specify which browsers you want to run with the configuration.

**Comment by DavertMik** [comment]
> Can this be done, or do I have to take care of this myself by starting CodeceptJS multiple times with different test suites assigned to be executed?

Both. 

My personal preference to run parallel tests on continuous integration server. This way you can ensure that tests are isolated.

**Comment by reubenmiller** [comment]
@cluehr Does this answer your question?

**Comment by allenhwkim** [comment]
I have the same requirement. 

Let's say I have 10 test files, and I want run all 10 tests at the same time not in sequence.
Assuming each test takes 1 minute to run, I want to finish tests in 1-2 minute, not in 10 minute.

**Comment by michaltrunek** [comment]
I tried to execute tests in parallel but managed to get max 2 tests running at the same time, is it possible to run more of them when using run-multiple please? 

**setup in codeceptjs conf file:**
```
multiple: {
        parallel: {
            chunks: 3
        }
    }
```
**setup in docker-compose file for zalenium selenium-hub:**
```
# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4445:4444
    command: >
      start --desiredContainers 3
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled false
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY

```

**Comment by vijayalakshmi-openturf** [comment]
How to do robot framework in codeceptjs? can anybody guide me ?
