### ISSUE TITLE
amOnPage fails to navigate to fragments on Puppeteer

### ISSUE THREAD

**Issue by enapupe** [codeceptjs/CodeceptJS#945]
#### What are you trying to achieve?
Run codeceptjs instructions with a different helper: puppeteer

#### What do you get instead?
Timeouts to execute  `I am on page "/#/profile/kind/account"`

> Provide console output if related. Use `--verbose` mode for more details.

```bash
 • I am on page "/#/profile/kind/account"
 ✖ FAILED in 43666ms
```

> Provide test source code if related

```js
I.amOnPage('/#/profile/kind/account');
```

### Details

* CodeceptJS version: 1.1.4
* NodeJS Version: v9.5.0
* Operating System: Darwin enapupe.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64 (MacOS 10.12.6 (16G1212))
* Configuration file:

```js
{
  "output": "./output",
  "helpers": {
    "Puppeteer": {
      "url": "https://staging.test.com",
      "show": true,
      "windowSize": "1300x900",
      "waitForAction": 400,
      "waitForTimeout": 2000,
      "chrome": {
        "args": ["--no-sandbox"]
      }
    }
  },
  "include": {
    "Auth": "./tests/acceptance/helpers/auth.js"
  },
  "mocha": {},
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "tests": "./tests/acceptance/*_test.js",
  "timeout": 10000,
  "name": "web"
}

```

To be clear, this code runs fine with WebDriverIO helper, amOnPage seems to work fine with regular paths, just fails with fragments (#).

**Comment by enapupe** [comment]
Actually this seems to be a Puppeteer issue https://github.com/GoogleChrome/puppeteer/issues/257

**Comment by reubenmiller** [comment]
Yeah it looks that way :/ I guess we'll just have to wait for it to be fixed there.

**Comment by enapupe** [comment]
Do you guys think we can do anything in CodeceptJS side using this hint https://github.com/GoogleChrome/puppeteer/issues/257#issuecomment-372364333 ?

**Comment by reubenmiller** [comment]
Yes I’ll have one look at it in more detail. Thanks @enapupe

**Comment by enapupe** [comment]
Thank you! LMK if I can help with anything. Thanks!
