### ISSUE TITLE
QUESTION: Cucumber plugin

### ISSUE THREAD

**Issue by thxv3n0lvl** [codeceptjs/CodeceptJS#979]
Just wondering if there's a way to connect a Cucumber plugin (I don't like it but my client does)
I can't find any place that this has been done for this particular project, I know it's possible for Codeception.

Any thoughts?

**Comment by DavertMik** [comment]
Yes, it was done for Codeception. Unfortunately, I don't have much time to implement that for CodeceptJS.Sure, it's somewhere in roadmap but no estimates yet. 

If your client would like to sponsor the development of such plugin I can make it in a week or less 😉

**Comment by atrevino** [comment]
That option is on the table now :) Let's see how it moves. 
Our second option is to collaborate to your framework. As it could be a great feature, any advise on where to start investigating could be very helpful.

Let you know how it goes!

Thanks !

**Comment by DavertMik** [comment]
> Our second option is to collaborate to your framework. As it could be a great feature, any advise on where to start investigating could be very helpful.

Sure, just ask! We are at Slack https://join.slack.com/t/codeceptjs/shared_invite/enQtMzA5OTM4NDM2MzA4LTNiMTE5YzNlMjQyNWYwZjAzODE3ZTI1MmVkYjY0YTYyNDZmMWJjM2VlODg3NTQzYzM2OGE5ZmIwODFjODk1MzI
Join and I will provide you as much information as you need to get this implemented!

**Comment by dvins** [comment]
Interested in possibly pursuing the sponsorship option, what's the best way to get hold of you via email?
