### ISSUE TITLE
I.retry().see('Hello'); this function retry action not once on failure but third on failure

### ISSUE THREAD

**Issue by frantallukas10** [codeceptjs/CodeceptJS#986]
If I want to retry only once on failure I have to write retry(0) before I function... it is not good solution for everybody... 

I would like to have config where I can disable this function, I don't need it.

**Comment by reubenmiller** [comment]
Are you able to provide console output which can confirm allow worth the example that you used?

Maybe these questions are better suited for the slack channel? That way we/you can er feedback on the suggested changes to see whether other developers also have a problem with this.
