### ISSUE TITLE
fillField returns `unknown error: call function result missing 'value'`

### ISSUE THREAD

**Issue by rcr929** [codeceptjs/CodeceptJS#992]
Someone already created a similar ticket on SO (https://stackoverflow.com/questions/49175711/q-codeceptjs-unknown-error-call-function-result-missing-value), but there hasn't been a response, so I'm submitting the issue here as well. 

Anytime the WebdriverIO `fillField` method is used, it errors out with `unknown error: call function result missing 'value'`. I copied the relevant function in my test and the config file below

```js
loginWith(email, password) {
    I.say(`login with ${email} / ${password}`);
    I.fillField(this.fields.email, email);
    I.fillField(this.fields.password, password);
    I.click(this.submitButton);
}
```

### Details

* CodeceptJS version: 1.0.2
* NodeJS Version: 8.7.0
* Operating System: macOS 10.12.6
* WebDriverIO version: 4.8.0
* Configuration file:

```js
module.exports.config = {
  output: './output',
  helpers: {
    WebDriverIO: {
      host: process.env.SELENIUM_HOST || "127.0.0.1",
      port: process.env.SELENIUM_PORT || 4444,
      url: process.env.APP_URL,
      coloredLogs: true,
      browser: 'chrome',
      windowSize: '1280x800',
    },
    Mochawesome: {
      uniqueScreenshotNames: false
    },
    "TabHelper": {
      "require": "./utils/codecept-tab-helper.js"
    }
  },
  include: {
    // Root Step Files
    I: './steps_file.js',

    // Page Objects
    loginPage: './pages/Login.js',
    welcomePage: './pages/Welcome.js',
    dashboardPage: './pages/Dashboard.js',
    experimentPage: './pages/Experiment.js',
    settingsPage: './pages/Settings.js',

    // Fragment Objects
    navbar: './fragments/Navbar.js',
    menuDropdown: './fragments/MenuDropdown.js',

    // Step Objects
    adminStep: './steps/Admin.js',
    goToStep: './steps/GoTo.js',

    // Util Methods
    utils: './utils/Utils.js'
  },
  mocha: {
    reporterOptions: {
      reportDir: 'output',
      reportFilename: 'report'
    }
  },
  bootstrap: './utils/static_server.js',
  teardown: './utils/static_server.js',
  hooks: [],
  tests: './tests/**/*_test.js',
  timeout: 10000,
  name: test'
};
```

**Comment by reubenmiller** [comment]
Can you try to update to the latest version and try again? I would highly recommend upgrading as there have been some great features added and also stability improvements with the webdriverio helper. 

If that is not possible, then can you try running the `I.fillField` in an isolated test scenario without page objects and see if that works? (To try and narrow down the problem area)

**Comment by rcr929** [comment]
I upgraded to Codecept 1.1.6 and WebdriverIO 4.12.0 and am still seeing the same error

**Comment by rcr929** [comment]
Also, moving all the code into a standalone test yields the same error.

```
Scenario('Test New Report Page', { retries: 0 }, function*(
  I,
  navbar,
  goToStep,
  utils
) {

  const userName = 'test,
        password = '1';

  I.say('Open Login Page');
  I.amOnPage('/#/login');
  I.waitForText('Sign in', 30);
  I.say(`login with ${userName} / ${password}`);
  I.fillField('Email', userName);
  I.fillField('Password', password);
  I.click('Sign in');
}
```

**Comment by reubenmiller** [comment]
What chromedriver version and Selenium version are you using? It looks to be a problem with selenium and not codecept (though I might be wrong).

**Comment by vidhya0406** [comment]
wdio-selenium-standalone-service -v=0.0.10
selenium-standalone -v=6.13.0
chromedriver -v=2.36.0

verify if you have these versions. This helped to solve the issue. 
More info:  https://github.com/webdriverio/webdriverio/issues/2631#issuecomment-372875052
